### ISSUE TITLE
Summit Topic: QUIC In-Depth

### ISSUE THREAD

**Issue by jasnell** [openjs-foundation/summit#185]
**Topic of the session**
QUIC In-Depth

**Describe the session**
This will be an in-depth look at the QUIC protocol implementation being worked on for Node.js. This will dig into the internals to let folks know how it is has been implemented, why and how it works the way it does, etc.

**Session facilitator(s) and Github handle(s)**
James M Snell (@jasnell)

**Additional context (optional)**

**Comment by evahowe** [comment]
How long would you like this session to run?

**Comment by evahowe** [comment]
@jasnell Also what is the level of experience you would like people to have? What type of session is this? (workshop, collaborate, etc) What pre-requisite knowledge should people have?

**Comment by evahowe** [comment]
@jasnell --- ping!  ^^

**Comment by jasnell** [comment]
30 minutes is fine. This is a session specifically for Node.js core contributors to update them on the progress, design, and implementation of the QUIC implementation.

**Comment by WaleedAshraf** [comment]
We moved this session to
**Day 1**, at **1600**, in **Room 510AC**

**Comment by trivikr** [comment]
* Initial experimental QUIC implementation in Node.js core https://github.com/nodejs/node/pull/30943
* QUIC repo https://github.com/nodejs/quic

**Comment by trivikr** [comment]
Tweet thread of the session https://twitter.com/trivikram/status/1205595981435326465

**Comment by christian-bromann** [comment]
@jasnell are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by christian-bromann** [comment]
Closing this issue. @jasnell please submit your notes or presentations if you made any. Cheers!
