### ISSUE TITLE
Propose spreadsheet to keep track of budgets

### ISSUE THREAD

**Issue by christian-bromann** [openjs-foundation/summit#186]
For the organisers of the summit it would be nice to have a spreadsheet to maintain and follow the costs for the collab summit so that the likelihood of going over budget decreases and everything is transparent to anyone. Such spreadsheet should contain fields to note costs for:

- venue
- food
- travel
- equipment

others?

**Comment by mcollina** [comment]
Is this an issue for Montreal 2019? These should be managed by the
Foundation directly.

Il giorno mar 13 ago 2019 alle 21:55 Christian Bromann <
notifications@github.com> ha scritto:

**Comment by christian-bromann** [comment]
> Is this an issue for Montreal 2019?

For the upcoming summit this shouldn't be a big issue given that there are some things we don't need to organize. However it would be definitely useful to have it for the summit in the spring.

> These should be managed by the Foundation directly.

Yes! We are in the process of moving this to the foundation or creating a new issue (see nodejs/admin#403)

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed. @christian-bromann Feel free to reopen if needed.
