### ISSUE TITLE
add @waleedashraf to repo

### ISSUE THREAD

**Issue by WaleedAshraf** [openjs-foundation/summit#192]
Hy,

Can someone add me (@waleedashraf) to openjs-foundation org and summit repo? I was part of nodejs/summit repo.

**Comment by WaleedAshraf** [comment]
ping @mhdawson

**Comment by WaleedAshraf** [comment]
reminder @mhdawson @joesepi

**Comment by jorydotcom** [comment]
@WaleedAshraf I added you! Thank you @mcollina for surfacing this to me. Waleed - can you [join the OpenJSF Slack](https://communityinviter.com/apps/js-foundation/join-openjs-foundation-on-slack) too?

**Comment by WaleedAshraf** [comment]
Thanks, I got the invite. I also joined Slack. 🎉
