### ISSUE TITLE
Code of Conduct and Reporting Guidelines for the projects have reached Stage 1. Can the Summit express intent to use it?

### ISSUE THREAD

**Issue by keywordnew** [openjs-foundation/summit#193]
See: https://github.com/openjs-foundation/cross-project-council/tree/master/proposals/stage-1/CODE_OF_CONDUCT

It's going through a staged process to be accepted. Stages 2 and 3 are upcoming.

Can the Summit begin to use it? IMO it's a good forcing function to get this out the door.

+1s or objections to get the discussion going :-)

cc: @openjs-foundation/cpc @openjs-foundation/summit

**Comment by mhdawson** [comment]
+1

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
