### ISSUE TITLE
Summit Topic: tooling group meeting

### ISSUE THREAD

**Issue by boneskull** [openjs-foundation/summit#194]
**Topic of the session**

Node.js [Tooling Group](/nodejs/tooling) Meeting

**Type of the session**
- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Level**
- [x] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

Experience or interest in building CLI tools with Node.js.  How can Node.js better serve this use-case?

**Describe the session**

This will be a face-to-face meeting of the Node.js tooling group.  Agenda TBD

**Session facilitator(s) and Github handle(s)**

@boneskull and/or @bcoe and/or @iansu

**Comment by boneskull** [comment]
if possible, we'd like a longer session (2h) to try to do some deep diving

**Comment by christian-bromann** [comment]
@boneskull are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by boneskull** [comment]
@christian-bromann https://github.com/nodejs/tooling/blob/master/minutes/2019-12-14-openjs-collab-summit.md

**Comment by boneskull** [comment]
guess I can just copy them

**Comment by christian-bromann** [comment]
Awesome, thank you! Closing the issue then.
