### ISSUE TITLE
Summit Topic: Node.js Release working group session

### ISSUE THREAD

**Issue by BethGriggs** [openjs-foundation/summit#195]
**Topic of the session**
Node.js Release working group 

**Type of the session**
- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Follow-up / Set-up sessions (if any)**
N/A

**Level**
- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Mainly targeted at those in the Node.js Release Working group - but welcome anyone with an interest in participating in Release/LTS/CITGM teams in future.

**Describe the session**

Node.js Release working group session - we will form an agenda in advance under nodejs/release. 

**Session facilitator(s) and Github handle(s)**

Beth Griggs @BethGriggs 

**Additional context (optional)**

**Comment by evahowe** [comment]
@BethGriggs how long would you like for this session?

**Comment by BethGriggs** [comment]
@evahowe I think around 90 minutes would be ideal -  thanks

**Comment by evahowe** [comment]
@BethGriggs thanks for letting me know!

**Comment by BethGriggs** [comment]
I didn't realise at the time of submitting that the collaborator summit would be single track. The Release session is mainly targetted at members of the Working Group (plus anyone interested in contributing to the working group in future 🤞). I _think_ only 5-10 members of Release will be present at the collaborator summit, and based on that I really do not think it makes sense for us to take 90 minutes of the summit time when the time could be donated to a topic of wider interest and involvement. 

If there will be small breakout/room sessions, 60-90minutes for Release would make sense. @evahowe, perhaps we could remove this from the draft agenda for now, and if there does happen to be multiple tracks on the day/facilities for breakout rooms we can arrange this on the day?

**Comment by evahowe** [comment]
We are adding another track currently so no worries - I will make a note of this. :)

**Comment by christian-bromann** [comment]
@BethGriggs are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by BethGriggs** [comment]
@christian-bromann - I added our brief summary of discussions to https://github.com/openjs-foundation/summit/pull/234

**Comment by christian-bromann** [comment]
Thanks! Let's close this then.
