### ISSUE TITLE
Summit Topic: Streams (Node.js)

### ISSUE THREAD

**Issue by Fishrock123** [openjs-foundation/summit#196]
**Topic of the session**
Streams

**Type of the session**
- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Follow-up / Set-up sessions (if any)**
_unknown_

The QUIC session should come before this as it may set up issues to be discussed here.

**Level**
- [x] Advanced

**Pre-requisite knowledge**
It would be helpful for people to know about any of the following:
- Streams (object, transform, etc)
- http 1/2/3/quic
- sockets in general
- streaming apis (including from other languages)
- libuv
- If you have ever used streams before and encountered difficulty

**Describe the session**
TBD. Likely introduced with some slide deck about "BOB" Streams, again.

Possible split between BOB / Future Streams and existing streams problems.

Possibly taking up more than one session if there is enough Streams 1/2/3 stuff to discuss.

**Session facilitator(s) and Github handle(s)**
- @fishrock123 - me, if I am present (likely but tbd).
- @jasnell 

**Additional context (optional)**
- See this repo: https://github.com/Fishrock123/bob
- See past collab summit sessions: https://github.com/openjs-foundation/summit/issues/172, https://github.com/openjs-foundation/summit/issues/110

**Comment by Fishrock123** [comment]
Oh and in case anyone is for some reason confused, this is **not** about streams on the web, only Node.js.

**Comment by mcollina** [comment]
Count me in as well. We would probably need more than 1 slot for this.

**Comment by evahowe** [comment]
@Fishrock123 @mcollina @jasnell 
How long would you like for this session?

**Comment by mcollina** [comment]
I would like to discuss about async iterators and promises in the context of streams. I think 30-45 minutes would be enough.

**Comment by evahowe** [comment]
@mcollina ok, putting you down for an hour to make the scheduling a bit easier.  Would yours be a separate session from @Fishrock123 and @jasnell ?

**Comment by mcollina** [comment]
Likely
Il 16 nov 2019, 21:30 +0100, Eva Howe <notifications@github.com>, ha scritto:

**Comment by evahowe** [comment]
ok, made a separate session for @mcollina 

@Fishrock123 and @jasnell - how much time do you want for your session?  and will @mcollina be part of that one too?

**Comment by Fishrock123** [comment]
Please don't overlap these.

For the "Future Streams" / "BOB" initiative, I think 1hr would be best, roughly broken down:

- Refresher presentation (15m)
- Api convention enforcement
- Discuss managed state
- Discuss parallelism
- Discuss Streams3 integration

extra: discuss native-layer stuff

**Comment by evahowe** [comment]
@Fishrock123 I have made notes of all of that and updated your description.

**Comment by WaleedAshraf** [comment]
@mcollina for "async iterators and promises in the context of streams" can you open an issue for it? So it can be linked to the agenda.

**Comment by mcollina** [comment]
@WaleedAshraf  done: https://github.com/openjs-foundation/summit/issues/216

**Comment by trivikr** [comment]
Any updates to this topic from QUIC-in-depth session in https://github.com/openjs-foundation/summit/issues/185?

**Comment by Fishrock123** [comment]
Not particularly.

**Comment by Fishrock123** [comment]
My slides are available at https://fishrock123.github.io/nodejs-collab-summit-montreal-2019/#0

The repo for the slides is https://github.com/Fishrock123/nodejs-collab-summit-montreal-2019

And of course the repo for BOB is https://github.com/Fishrock123/bob
