### ISSUE TITLE
Summit Topic: OpenJS Cross Project Council introduction and update

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/summit#199]
**Topic of the session**
Learn about the OpenJS Cross Project Council

**Type of the session**
- [] Collaborate
- [] Workshop
- [x] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 
Jory Burson and I have a talk at the conference about the OpenJS CPC, but I'd like to take a moment at the Community Corner to do a brief introduction, direct attendees to our talk (so it would be good to have this CommCorn to be before our talk) and also to direct attendees to an open office hours session at the Collab Summit and potentially an open office hours at the Community Corner. (Open Office Hours meaning 1 or more people at a table answering questions and directing folks for how to get more involved.)

**Level**
- [x] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

**Describe the session**
Jory Burson and I have a talk at the conference about the OpenJS CPC, but I'd like to take a moment at the Community Corner to do a brief introduction, direct attendees to our talk (so it would be good to have this CommCorn to be before our talk) and also to direct attendees to an open office hours session at the Collab Summit and potentially an open office hours at the Community Corner. (Open Office Hours meaning 1 or more people at a table answering questions and directing folks for how to get more involved.)

**Session facilitator(s) and Github handle(s)**
@joesepi 

**Additional context (optional)**

**Comment by joesepi** [comment]
I have further fleshed out (along with others on the CPC) what I think would be ideal:

# NJSI + CommCorn + Collab Summit proposal

This is an ideal scenario according to me. It is open to suggestions.

## Key engagements in order of appearance:
- Keynote: What makes a good project
- CPC Overview at CommCorn
- 200 days of CPC talk by Jory Burson and Joe Sepi
- CPC Open Office Hours at Community Corner
- CPC Collab Summit session

### Keynote: What makes a good project
I was asked to give this keynote and can briefly mention the following engagements to “learn more” about the foundation and council.

### CPC Overview at CommCorn
10 minute slot to just highlight the Foundation and the Cross Project Council and to promote the other key engagements. Ideally on day 1 or early on day 2 as the 200 days talk is afternoon of day 2.

### 200 days of CPC talk by Jory Burson and Joe Sepi
Jory and I can promote an Open Office hours immediately after our talk.

### CPC Open Office Hours at Community Corner
It would be ideal if there was an open office hours session planned for immediately after our talk (4pm would be perfect). This time does need to usurp any planned talks at Community Corner. It would be ideal to have a corner ourselves or a room or someplace that isn’t disruptive but is inviting to folks.

### CPC Collab Summit session
The CPC would like a dedicated block of time for us to work through an agenda of items to tackle as a group in person. We have a few things to work through, but I’m not sure it makes sense to break them into hour blocks separately so we thought a larger block of time would be best and we can work through an agenda as progress allows.

#### Potential agenda items:
- transition process and support for emeritus projects
- standards working group
- infrastructure
- project progression (acceptance/rejection, silent process, onboarding/offboarding)
- bluesky thinking

**Comment by christian-bromann** [comment]
@joesepi are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by christian-bromann** [comment]
Closing this issue. @joesepi please submit your notes if you made any. Cheers!
