### ISSUE TITLE
Community Corner: Ask the CommComm Panel at NJSI

### ISSUE THREAD

**Issue by WaleedAshraf** [openjs-foundation/summit#200]
**Topic of the session**
Ask the CommComm

**Type of the session**
- Panel

**Describe the session**
We are planning to hold the CommComm Q&A session at Community Corner at Node+JS Interactive, like last year. Last year we had 5 people in the panel. Whoever is interested, please raise your hand.

We can discuss more it in coming CommComm meetings. The purpose of this session is to make CommComm more reachable to the audience. Give the opportunity to attendees to ask questions and discuss their concerns. 

**Session facilitator(s) and Github handle(s)**
@bnb
@WaleedAshraf
@keywordnew 
@joesepi

**Comment by evahowe** [comment]
@WaleedAshraf how long would you like for this session?

**Comment by WaleedAshraf** [comment]
I think 30mins should be enough. @keywordnew what you suggest? after this, we can continue with CommComm Office Hours suggested by @joesepi 

Also, @keywordnew @joesepi I'm you both to this panel.

**Comment by evahowe** [comment]
Thank you!
