### ISSUE TITLE
Summit Topic: Promises in Node.js Core

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/summit#204]
**Topic of the session**
Promises in Node.js Core

**Type of the session**
- [x] Collaborate
- [] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
> I have a talk scheduled at NJSI on Promises. There was a similar session at Berlin Collab Summit that was lively and fruitful

**Level**
- [] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**
> Awareness of Promises and their implementation helpful but not required

**Describe the session**
Working session on where we are, what our priorities should be and any open proposals related to the work

**Session facilitator(s) and Github handle(s)**
@joesepi 
Others who will likely be interested include but not limited to: @mcollina @jasnell @mhdawson and many others that I can't seem to tag (Node.js org, not OpenJS org)

**Additional context (optional)**

**Comment by benjamingr** [comment]
Did anything related to the session we had on this in Berlin actually happen in the meantime? Is there an up-to-date status document somewhere?

**Comment by evahowe** [comment]
@benjamingr I don't know.  @joesepi Do you know?

**Comment by christian-bromann** [comment]
@joesepi are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by christian-bromann** [comment]
Closing this issue. @joesepi please submit your notes if you made any. Cheers!
