### ISSUE TITLE
Community Corner: Node.js Community Committee Open Office Hours at Community Corner

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/summit#205]
**Topic of the session**
Node.js Community Committee Open Office Hours at Community Corner

**Type of the session**
- [x] Collaborate
- [] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
> None

**Level**
- [x] Beginner
- [] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> None.

**Describe the session**
We'd like to set aside some time to engage with anyone who may have an interest in the work of the Node.js Community Committee and to facilitate any on boarding efforts if applicable.

**Session facilitator(s) and Github handle(s)**
@joesepi 

**Additional context (optional)**
2 years ago, we had a great breakout session at Collab Summit for CommComm and several new people got involved out of that session. We'd love to try and repeat that success, but my thinking is that we would get more interest at the Community Corner (during the event).

And I'd like to note that I do not wish to interrupt talk at CommCorner. It would be ideal to have a little area off to the side for any open office hours sessions.

**Comment by WaleedAshraf** [comment]
@joesepi If you need anyone to help with this let me know. I'll be there.
