### ISSUE TITLE
Summit Topic: Node.js diagnostics

### ISSUE THREAD

**Issue by gireeshpunathil** [openjs-foundation/summit#206]
**Topic of the session**
 - working group: current status and team
 - working group: current priorities / agenda
 - diagnostic user journey and best practices
 - tooling: tiers and status on capability / maturity
 - call for wider participation

**Type of the session**
- [x] Collaborate
- [] Workshop
- [x] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 

**Level**
- [x] Beginner
- [x] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

NA

**Describe the session**

Present the current state, priorities and challenges of the working group

**Session facilitator(s) and Github handle(s)**

mainly @gireeshpunathil , looking for support from @mhdawson  and others who are active in the working group.

@nodejs/diagnostics - please review and propose / recommend additions or modifications.

**Additional context (optional)**

**Comment by evahowe** [comment]
@gireeshpunathil How long would you like for this session?

**Comment by gireeshpunathil** [comment]
@evahowe - an hour should be good, thanks!

**Comment by mhdawson** [comment]
@gireeshpunathil I'll definitely plan to be there.

**Comment by evahowe** [comment]
@gireeshpunathil - thanks I have you down for an hour :)

**Comment by mmarchini** [comment]
Will it be possible to join remotely?

**Comment by gireeshpunathil** [comment]
@mmarchini - I guess so. Last year we had infra and logistics to cover remote participation; this year too we could try that, wherever required. @evahowe - I guess the sessions can be enabled with zoom?

**Comment by evahowe** [comment]
@mmarchini @gireeshpunathil I had a very short chat with @christian-bromann about this.  Saucelabs provided laptops for us to do it through zoom in Berlin, but we haven't verified if this is possible this time around.

**Comment by gireeshpunathil** [comment]
@mmarchini / @hekike or anyone else interested in remote participation, here is the link: https://zoom.us/j/173804425

**Comment by trivikr** [comment]
Tweet thread about the session https://twitter.com/trivikram/status/1205946604152377345

Thanks to @gireeshpunathil for coming up with the summary!

**Comment by christian-bromann** [comment]
@gireeshpunathil are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by gireeshpunathil** [comment]
@christian-bromann - I don't have notes taken, but most of the discussions points are sitting in my head at the moment. Is there any template or something that I can use for this?

**Comment by christian-bromann** [comment]
> Is there any template or something that I can use for this?

No. We haven't really captured and documented notes and session artifacts in other collab summits but I think it would be useful to share what can be shared so we can later take a look back to see what was discussed. That said, it is totally up to you. I've seen a lot of people that took notes during the sessions and sharing these should be easy. If you think sharing a quick brain dump is worth the time feel free.
