### ISSUE TITLE
Summit Topic: Modules - An Update on Unflagged ES Modules in Node.js

### ISSUE THREAD

**Issue by guybedford** [openjs-foundation/summit#207]
**Topic of the session**

An Update on Unflagged ES Modules in Node.js

**Type of the session**
- [ ] Collaborate
- [x] Workshop
- [x] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 

**Level**
- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

To follow all the details it would be advisable to have knowledge of how CommonJS packages currently work in Node.js, and how ES modules behave in browsers. While the details and justifications can be quite complex, at the same time the overall workflows themselves are designed to be used by all users of Node.js.

**Describe the session**

ES modules are now unflagged and will hopefully be shipped too by the summit. This session will be an opportunity to share the high-level overview of the modules implementation from members of the modules team, without having to trawl through hours of meeting notes to catch up on the various complexities. We'll also update on some of the roadmap going forward into next year as well as what the advice is for userland packages that might seek to upgrade to use ES modules.

Part talk / part workshop / feedback session, the exact format is planned to be flexible and determined by the contributors and audience engagement.

**Session facilitator(s) and Github handle(s)**

@MylesBorins @GeoffreyBooth and @guybedford will be there to run the session.

Anyone else who's been involved in the modules process that I've missed out is welcome to contribute.

**Additional context (optional)**

The suggested length for the session would be 2 hours.

**Comment by guybedford** [comment]
For scheduling, ideally first day would help as @GeoffreyBooth is leaving the afternoon of the second day of the summit. A morning session on the second day might be possible but @GeoffreyBooth would have to update on his availability for that.

**Comment by evahowe** [comment]
@guybedford - How long would you like for this session?

**Comment by guybedford** [comment]
@evahowe if we could set aside two hours that would be ideal - it could go over or under that though.

**Comment by guybedford** [comment]
Actually if we need spill out discussions we can arrange that separately or move - so I don't expect it would go over at all, only possibly under that but would be nice to have the time if possible. Otherwise 1.5 hours could be fine too.

**Comment by evahowe** [comment]
@guybedford - no worries, I will put you down for two hours :)

**Comment by jkrems** [comment]
It's currently scheduled for the 13th at 13:30pm ET. I'd like to dial in if possible - is this issue the best way to learn about any potential changes in the schedule?

**Comment by ljharb** [comment]
I’d love to dial in too.

**Comment by evahowe** [comment]
Here is the link for the agenda: https://github.com/openjs-foundation/summit/blob/master/2019-12-Montreal/agenda.md

It will be probably constantly updated.  We don't have a set way to dial into a session.  However, the plan is to use zoom to record each session on the speaker's laptop so I bet if you touched base with @guybedford he could give you the link to the room.

**Comment by BridgeAR** [comment]
Just in case: @jkrems and me are in the stream. In case you already started, please check if it's possible to get us listen / join the session.

**Comment by thescientist13** [comment]
For those following along, [here is the article](https://medium.com/@nodejs/announcing-core-node-js-support-for-ecmascript-modules-c5d6dc29b663) being read, which includes links to the [NodeJS docs about ESM](https://nodejs.org/api/esm.html#esm_dual_commonjs_es_module_packages).

**Comment by christian-bromann** [comment]
@guybedford are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by christian-bromann** [comment]
Closing this issue. @guybedford please submit your notes if you made any. Cheers!

**Comment by GeoffreyBooth** [comment]
I should still have the code for the live demo I did, if you want that.

**Comment by christian-bromann** [comment]
@guybedford awesome, would you mind to create a PR and submit the code in here: https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal ?
