### ISSUE TITLE
Summit Topic: Package Maintenance working group session

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/summit#209]
**Topic of the session**

**Type of the session**
- [X] Collaborate
- [] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 

**Level**
- [] Beginner
- [X] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.
Ideally, be following/up to speed on the work of the package-maintenance team. Reading
issues in advance would help.

**Describe the session**
Working session of the package-maintenance team. Initial list of topics include:

* Express triage 
* Publishing for teams
* Support info
* Discussion of funding platforms/approaches
* CI setup recommendations

**Session facilitator(s) and Github handle(s)**
Michael Dawson @mhdawson 

**Additional context (optional)**

**Comment by evahowe** [comment]
@mhdawson how much time would you like?

**Comment by mhdawson** [comment]
Sorry I forgot to add that. We'd like 1 hour.

**Comment by lholmquist** [comment]
i know we didn't get through all the topics, but was anyone taking notes?

**Comment by christian-bromann** [comment]
@mhdawson are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by mhdawson** [comment]
There were no notes, but I believe that is was recorded. @mcollina do you know where the streams were recorded?

**Comment by brianwarner** [comment]
They should have been recorded via Zoom.  I need to trim and post them, hopefully this week if I can carve out the time.

**Comment by christian-bromann** [comment]
@brianwarner awesome, let me know if you have the link. I would like to document any artifacts to the sessions.

**Comment by brianwarner** [comment]
Will do! I'll post them to YouTube and create a playlist, as with the prior summit.

**Comment by christian-bromann** [comment]
Closing this issue. @brianwarner please submit the playlist when you get the chance. Cheers!
