### ISSUE TITLE
Community Corner: How to contribute to open source using Git and GitHub

### ISSUE THREAD

**Issue by Whizkevina** [openjs-foundation/summit#214]
**How to contribute to open source using Git and GitHub**

**Type of the session**
- [] Collaborate
- [x] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 

**Level**
- [x] Beginner
- [] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> How to use the Terminal.
> How to create a directory on System.
> Basic Programming Knowledge.

**Describe the session**
How to contribute to open source using Git and GitHub for beginner, knowing Git as Version Control System and Github as a code-hosting platform and also how to contribute to other people project and open source at large.

**Session facilitator(s) and Github handle(s)**
Aina Oluwatimilehin @Whizkevina

**Additional context (optional)**

**Comment by tniessen** [comment]
Hi @Whizkevina, is this something you would like to learn, or is this something you would like to introduce others to? According to the README, the summit is "for active contributors", so I think most people there are likely to know their way around Git(Hub) already.

**Comment by Whizkevina** [comment]
Hi @tniessen, I was planning to introduce it to others but I'm thinking it's really everyone that really knows how to use it.

**Comment by tniessen** [comment]
I am a little confused, to be honest. Have you contributed to Node.js or other OpenJS projects before? You claim on your (recently updated) GitHub profile to be a member of the Node.js organization, but GitHub does not list you as a member and you don't seem to have contributed to any of our repositories.

**Comment by ruyadorno** [comment]
hi @Whizkevina could you please change the title prefix of this issue? 😊 

from `Summit Topic:` to `Community Corner: `

/cc @evahowe

**Comment by Whizkevina** [comment]
Ok, @ruyadorno ,
I will change the title prefix of the issue.

@tniessen, I have contributed to other OpenJS projects before but not yet to Node.js, but why you seem not welcoming.

**Comment by evahowe** [comment]
@Whizkevina - hello!  We had talked about your talk possibly being part of community corner last week.  I hope you can make the meeting today and we can chat about it and a bunch of other things :)

**Comment by tniessen** [comment]
@Whizkevina I am sorry if I seemed "not welcoming", that was not my intention. As I said, I am just confused because you claim to be a "Member @nodejs", but you don't seem to be a member of the Node.js organization nor do you seem to have contributed to Node.js.

**Comment by Whizkevina** [comment]
@evahowe, I think I missed the meeting on Tuesday, I would appreciate it if I can get a re-cap.

@tniessen, No problem, I will soon find an open issue to contribute too and if you have any let me know if I will be able to resolve it.

**Comment by tniessen** [comment]
That is not what I mean, that still wouldn't make your claims true. Anyway, I don't think my confusion/concerns here will result in anything, so I will leave the conversation to others.

**Comment by evahowe** [comment]
@Whizkevina Thank you so much for your submission.  I really appreciate you taking the time to write it up.  We just had a call on the Collab Summit and Community Corner (now renamed Dev Lounge) and it has been decided to keep that space more focused on conversations rather than presentations. So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested. For example: CPC OOO (Open Office Hours), Community Committee OOO, Node.js Release WG OOO, Package Maintenance Team OOO, Express OOO, Fastify OOO and so on…

**Comment by Whizkevina** [comment]
@evahowe Okay, I will be more helpful to contribute to Dev Lounge when the "Open Office Hours" has been set up.
