### ISSUE TITLE
Summit Topic: Making single-company projects more open

### ISSUE THREAD

**Issue by morsssss** [openjs-foundation/summit#218]
**Topic of the session**
* How can the open-source community be encouraged to take more ownership of a project like AMP that was started by a company like Google? What mechanisms are needed?
* Is there a way to help open-source contributors feel more free to contribute? How must AMP change to make this possible?
* How can the community contribute more meaningfully to the direction of a project like AMP?

**Type of the session**
- [✔️] Collaborate
- [] Workshop
- [] Talk

**Level**
- [✔️] Beginner
- [] Intermediate
- [] Advanced

**Pre-requisite knowledge**
None

**Describe the session**
AMP is an open-source project. But it was started by Google, and most of the contributions and work come from Google engineers. How can this sort of project become more truly open-source?

**Session facilitator(s) and Github handle(s)**

**Additional context (optional)**

**Comment by evahowe** [comment]
@morsssss How much time were you looking for?

**Comment by morsssss** [comment]
How long is a typical session?

**Comment by evahowe** [comment]
@morsssss - about an hour usually

**Comment by morsssss** [comment]
I think you should decide this, as I have never been to this summit before!

 I could imagine this discussion being shorter than an hour. But you'd know
best.

**Comment by christian-bromann** [comment]
@morsssss did you end up running this session and are there any notes or other artifacts for it? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by morsssss** [comment]
I did, and I do have notes!

So all I need to do is convert those to markdown and create a new file in the summit directory?

**Comment by christian-bromann** [comment]
@morsssss we don't have any requirements to the format, so anything that can be source controlled would work 😉

**Comment by christian-bromann** [comment]
Notes have been added in #242, closing. Thanks @morsssss !
