### ISSUE TITLE
Community Corner: How to become an Express Triager

### ISSUE THREAD

**Issue by wesleytodd** [openjs-foundation/summit#219]
**Topic of the session**

A hands on lightning talk for people who want to get started triaging issues on Express.

**Type of the session**
- [X] Lightning Talk

**Follow-up / Set-up sessions (if any)**

https://sched.co/T5Fx

NA

**Level**
- [X] Beginner
- [X] Intermediate
- [X] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

None

**Describe the session**

Express is working on a new program to grow our contributor base.  The first step of this is getting more people involved in triaging issues.  We have established a process for how to onboard more people, and I would like to go over the process and show people how to get involved.

Links to the in progress work to setup this program: 

https://github.com/expressjs/discussions/issues/92
https://github.com/expressjs/express/pull/4055

**Session facilitator(s) and Github handle(s)**

@wesleytodd
@gireeshpunathil

**Comment by wesleytodd** [comment]
@gireeshpunathil will you be at the conference and summit? If so, and want to help run this quick session that would be great!

**Comment by gireeshpunathil** [comment]
@wesleytodd - I will be coming; and happy to work with you on this, thanks!

**Comment by evahowe** [comment]
@wesleytood and @gireeshpunathil - Thank you both so much for your submission.  I really appreciate you taking the time to write it up.  We just had a call on the Collab Summit and Community Corner (now renamed Dev Lounge) and it has been decided to keep that space more focused on conversations rather than presentations. So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested. For example: CPC OOO (Open Office Hours), Community Committee OOO, Node.js Release WG OOO, Package Maintenance Team OOO, Express OOO, Fastify OOO and so on…

**Comment by wesleytodd** [comment]
Understandable! Is there a way to officially announce and promote the Express Office Hours? We would really like to get as many participants as we can for this.

**Comment by gireeshpunathil** [comment]
> So the expectation is that we will set up more “Open Office Hours” related to the proposed topics if people are interested

@evahowe - also please will you expand a little bit on this, for my understanding? Does it operate like a `booth` or something with a fixed time duration? thanks!

**Comment by mhdawson** [comment]
And I guess is there a schedule yet?

**Comment by evahowe** [comment]
@wesleytodd - The idea is to get the people together that you would like to do the office hours with and then tweet it out with the #NodeJSInteractive so people know you are there.  Then Rachel will also tweet it out from the OpenJS account.  

@gireeshpunathil - It is much more casual than a booth.  Just a couple of people hanging out and answering questions.  You can be there for as long or short as you want.  

@mhdawson - There isn't a schedule.  It will just be whenever ya'll have a break to do it.

**Comment by christian-bromann** [comment]
@wesleytodd are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by wesleytodd** [comment]
It was pretty informal, we did [sign up quite a few members for the triage team](https://github.com/expressjs/express/blob/triage/Contributing.md#list-of-triagers), but that is the only record of what we ran.  Do you think it is worth me writing up something?  What is this directory used for?

**Comment by christian-bromann** [comment]
If there were no notes taken that is fine. Just want to make sure that we document any artefacts if there are any so they don't get lost on someones computer 😉
