### ISSUE TITLE
Summit Topic: I'm a lawyer in the Google Open Source Programs office AMA

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/summit#220]
**Topic of the session**

I'm a lawyer in the Google Open Source Programs office AMA

**Type of the session**
- [ ] Collaborate
- [x] Workshop
- [ ] Talk

**Level**
- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

None, all welcome

**Describe the session**

Do you have any questions about legal compliance and open source? Why pick certain license? Why have a CLA? What even is compliance?

I’m Max, a lawyer in Google’s Open Source Programs Office. I help set Google’s open source licensing, foundations, and compliance policies. Ask me hypothetical questions about how Google sets policies or works through tough or ambiguous problems.

**Session facilitator(s) and Github handle(s)**

@MylesBorins @sillsm

**Additional context (optional)**

This could also be run in the community corner if you think it will be a better fit there

**Comment by evahowe** [comment]
How much time would you like for this?

**Comment by MylesBorins** [comment]
30 minutes?

**Comment by WaleedAshraf** [comment]
Luis Villa @tieguy
will be leading this session.

we moved this session to Day 1, at 11:30 am in room Room 512DH.

**Comment by christian-bromann** [comment]
Do we have any notes or artifacts for this session? As far as I know there weren't, so we can close this?

**Comment by tieguy** [comment]
Right, no notes/artifacts - was not filmed or recorded. Thanks for the
last-minute opportunity, though!

**Comment by christian-bromann** [comment]
Thanks for all your input @tieguy! Will close the issue then.
