### ISSUE TITLE
Summit Topic: Marcomm Support: What's available and how to get plugged in 

### ISSUE THREAD

**Issue by RRomoff** [openjs-foundation/summit#221]
**Topic of the session**
Getting projects connected to marketing resources from the OpenJS Foundation

**Type of the session**
- [*] Collaborate
- [] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
> List the sessions that are related. 

**Level**
- [*] Beginner
- [] Intermediate
- [] Advanced

**Pre-requisite knowledge**
> List pre-requisite knowledge that it would be required for participants to have.

**Describe the session**
Getting the word out about what your project is working on, to the right audiences, is important and the OpenJS Foundation is here to help! Join this session if you'd like to ramp up communications efforts or just ready to learn what's available as a hosted project. In addition, we want to hear from projects about what's helpful in this space, and how we can best support your efforts.

**Session facilitator(s) and Github handle(s)**
Rachel Romoff @RRomoff 

**Additional context (optional)**

**Comment by christian-bromann** [comment]
@RRomoff are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by RRomoff** [comment]
> @RRomoff are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

@christian-bromann here are the slides! https://docs.google.com/presentation/d/1xWsohwo-SwKjR-GuThi0BVwz3ni7KLp3vIBTuAbMQRY/edit?usp=sharing

**Comment by christian-bromann** [comment]
Thanks @RRomoff
