### ISSUE TITLE
Summit Topic: AMP infrastructure plan

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/summit#226]
**Topic of the session**

Joint session between interested CPC members and AMP's infra WG to move forward with infrastructure-related graduation requirements.

**Type of the session**
- [✔️] Collaborate
- [] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
None

**Level**
- [] Beginner
- [] Intermediate
- [✔️] Advanced

**Pre-requisite knowledge**

An interest for learning about AMP's infrastructure and determining how to best bring it to the OpenJSF. 

**Describe the session**

Open discussion with the goal of advancing the following issues:

- https://github.com/ampproject/wg-infra/issues/18
- https://github.com/ampproject/wg-infra/issues/19

**Session facilitator(s) and Github handle(s)**

Tobie Langel (@tobie)
Jory Burson (@jorydotcom)

**Additional context (optional)**

**Comment by christian-bromann** [comment]
@tobie are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by tobie** [comment]
I *think* @jorydotcom took some notes.
