### ISSUE TITLE
Summit Topic: Implementation of the OpenJSF IP Policy

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/summit#227]
**Topic of the session**
Implementation of the OpenJSF IP Policy

**Type of the session**
- [✔️] Collaborate
- [] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
None

**Level**
- [] Beginner
- [] Intermediate
- [✔️] Advanced

**Pre-requisite knowledge**

A basic understanding of IP policy and a deep care for contributor experience.

**Describe the session**
Discuss the implementation of the IP Policy in order to improve contributor experience

- How can we make the contribution experience as frictionless as possible while preserving key legal aspects?
- Can we change the language around practices deemed unnecessary from a legal perspective to discourage them rather than make them optional? (i.e. can we be more prescriptive rather than descriptive?)
- Concerns with the DCO not being practical at all for drive-by commits nor for commits done through GitHub’s web interface.
- Why should foundation projects have to adopt either the DCO or the CLA? They're both somewhat contributor hostile.
- In which files should what go? Can we be more prescriptive, here?
- See notably issues:
  - https://github.com/openjs-foundation/cross-project-council/pull/414
  - https://github.com/openjs-foundation/cross-project-council/pull/386

**Session facilitator(s) and Github handle(s)**
@tobie (others?)

**Additional context (optional)**

**Comment by christian-bromann** [comment]
@tobie are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by christian-bromann** [comment]
Closing this issue. @tobie please submit your notes if you made any. Cheers!
