### ISSUE TITLE
Summit Topic: Joint session Board, CPC, and community members

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/summit#228]
**Topic of the session**
Joint session Board, CPC, and community members

Get the different governance bodies together so folks understand each other (and their roles) better.

**Type of the session**
- [✔️] Collaborate
- [] Workshop
- [] Talk

**Follow-up / Set-up sessions (if any)**
None

**Level**
- [] Beginner
- [✔️] Intermediate
- [] Advanced

**Pre-requisite knowledge**
None

**Describe the session**
A number of important issues (such as the IP Policy or earmarked funds) are the prerogative of the Board, which is absolutely understandable. However, these policies impact projects in a way that can sometimes be important, and it's hard for project contributors to understand who is responsible of what or feel like their voice is heard.

* While the CPC feels approachable, the Board much less so.
* Are the Board and CPC aware of this?
* How does the Board and the CPC communicate?
* How can project leads bring to the attention of the board issues that impact their projects but are the prerogative of the board?
* Etc.

If feels like this would be more productive as a joint session between the CPC and the Board (though maybe folks like me wouldn't be invited to it?). Is this something that's planned or that could be organized?

**Session facilitator(s) and Github handle(s)**
?

**Additional context (optional)**

**Comment by evahowe** [comment]
@tobie - Since this is a bit last minute I have slotted you in for 14:30 and 16:00 for your talks.  Will you be here til the end on Saturday?

**Comment by christian-bromann** [comment]
@tobie are there any notes or other artifacts for this session? If so can you share them here? I am happy to make a PR and add them to the [summit directory](https://github.com/openjs-foundation/summit/tree/master/2019-12-Montreal) or feel free to raise one by yourself. Thanks!

**Comment by tobie** [comment]
Maybe @jorydotcom has some notes. I did a terrible job of documenting those different conversations.
