### ISSUE TITLE
2020.02.11 Collab Summit Planning Meeting

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/summit#246]
## Time

**UTC Tue 11-Feb-2020 19:00 (06:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Tue 11-Feb-2020 10:00 (10:00 AM) |
| US / Mountain | Tue 11-Feb-2020 11:00 (11:00 AM) |
| US / Central  | Tue 11-Feb-2020 12:00 (12:00 PM) |
| US / Eastern  | Tue 11-Feb-2020 13:00 (01:00 PM) |
| London        | Tue 11-Feb-2020 18:00 (06:00 PM) |
| Amsterdam     | Tue 11-Feb-2020 19:00 (07:00 PM) |
| Moscow        | Tue 11-Feb-2020 21:00 (9:00 PM) |
| Chennai       | Wed 11-Feb-2020 23:30 (11:30 PM) |
| Hangzhou      | Wed 12-Feb-2020 02:00 (02:00 AM) |
| Tokyo         | Wed 12-Feb-2020 03:00 (03:00 AM) |
| Sydney        | Wed 12-Feb-2020 05:00 (05:00 AM) |

Or in your local time:
* http://www.wolframalpha.com/input/?i=06PM+UTC%2C+Feb+11%2C+2020+in+local+time

## Links

* Rolling Notes Doc: <https://docs.google.com/document/d/166t3D87CGtXpMV-ouYP9TBq2x3pZ16QackYtASPIY5g/edit>

## Agenda

1. **Meta Issues**
2. **Venue & Date Updates**
3. **Registration**
4. **Summit Programming**

## Invited

* OpenJS Foundation Cross Project Council
* OpenJS Foundation Project Maintainers & Project Community Members
* OpenJS Foundation Board of Directors

## Joining the meeting

link for participants: Zoom link: https://zoom.us/j/742726725

---

**Invitees**

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by ljharb** [comment]
@jorydotcom the agenda label seems to need renaming?

**Comment by jorydotcom** [comment]
hmm how do you mean? We have a label for cross-project-council-agenda if there's something to go to the CPC, but I hadn't intended for this to get on today's CPC meeting agenda

**Comment by ljharb** [comment]
In the OP, it says "The agenda comes from issues labelled with cross-project-council-agenda across all of the repositories in the openjs-foundation org. Please label any additional issues that should be on the agenda before the meeting starts." - this isn't the CPC meeting, so i wouldn't expect its agenda to come from the CPC agenda label.

**Comment by jorydotcom** [comment]
ahhh leftover copypasta got it yay
