### ISSUE TITLE
Travel Fund Questions for Project Community Members

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/summit#249]
We want to make sure all the project communities are informed about the summit, and about the travel fund process, when we go out to them requesting their attendance + session ideas. We want to review & confirm/verify process questions about the travel fund before we do that:

* All projects in the foundation, regardless of stage or incubation status, are eligible to use the travel fund.
* The fund can cover the costs, in whole or in part, of a contributor's hotel, airfare, and event registration (for OpenJS World and the Collab Summit)
* Fund Applicants should seek to use employer funds as a first resort. Need is a factor.
* Employees of Foundation Member companies are eligible, but we encourage the use of internal funds that may be available to them first.
* Any member of a project community, who has had recent, sustained contributions to the project for the past 90 days or more is eligible.
* Are there other guidelines to give 1) applicants or 2) project maintainers for applying and reviewing requests?

Related issues/PRs:
* https://github.com/openjs-foundation/cross-project-council/issues/397
* https://github.com/openjs-foundation/cross-project-council/pull/441

**Comment by mcollina** [comment]
I absolutely agree on all the above.

**Comment by mhdawson** [comment]
I think this are a good starting point. I would be nice to be more specific than `sustained contributions to the project for the past 90 days` but I don't have a better suggestion.

**Comment by ruyadorno** [comment]
I find that being more specific than that is quite difficult since the definition of `contributions` can be very different depending on each project, WG, etc

**Comment by joesepi** [comment]
With the merging of PR https://github.com/openjs-foundation/cross-project-council/pull/492 I believe we can close this issue.
