### ISSUE TITLE
How to encourage projects to surface discussions they would like to have with others

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/summit#250]
During our [Feb. 11](https://github.com/openjs-foundation/summit/pull/247/files) meeting, we briefly discussed how to encourage or create session proposals that promote cross-project engagement. One idea was to encourage people to suggestion topics that they would like to discuss with others, without requiring them to provide a facilitator in the session proposal. 

Feedback from @mcollina:
>From previous summits experience, having a facilitator for most session means that the sessions and topics are prepared up-front and curated. I highly discourage removing this.
>We might want to keep a few slots as "unconference" / "open" if we want to have more spontaneous discussions

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
