### ISSUE TITLE
New Contributor Orientation Track

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/summit#251]
The Collab Summit Planning Team has decided to move forward with this 'Track' of programming!

**Available Details**
This track is planned to run on Monday, June 22, ahead of the OpenJS Conference.
This track is online-only. 
We will provide session facilitation support and guidance. 
We will be using a scheduling tool to find optimal times given timezones and availability.
We will have tooling demos / platform walk-throughs for presenters.
We are working through questions and issues as they arise - please reply here or in the slack channel if you have things you want to bring up.

**Current Session Proposals in this Track:**
* #263 - Introduction to Fastify
* #264 - Introduction to WebdriverIO
* #281 - Dojo
* #283 - Contributing to Express
* #285 - Building nodes with Node-RED

To support new contributors, we are also looking for resources we can provide them ahead of the event that will help them feel more confident and oriented (#269). If you are proposing a session for this track, please include any reference materials you would like attendees to view in advance along with your proposals.

_original message_
At our Feb. 11 planning meeting, we discussed how to make sure new contributors would also find value in the Collab Summit (while also not detracting from the value of collab summit for core maintainers). We came up with the idea to have a 'New Contributor Orientation Track' programmed with more introductory sessions. 

We're looking for session ideas that could be added to this track - e.g. "Understanding the Open Source PR workflow" or "Intro to Express" or "Dojo Workshop". Please give this some thought and add your ideas to this [hackmd document](https://hackmd.io/@ra-6t4fuRmeQNH1J5Rzv3A/Skob34Em8).

**Comment by joesepi** [comment]
We can "trial" some of these ideas potentially in my open office hours thing that I'm trying to ramp up. https://github.com/openjs-foundation/cross-project-council/issues/465

**Comment by keywordnew** [comment]
This template would need to be updated with tracks:

https://github.com/openjs-foundation/summit/blob/master/.github/ISSUE_TEMPLATE/summit-topic-proposal.md

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
