### ISSUE TITLE
Session space for jQuery Core contributors

### ISSUE THREAD

**Issue by timmywil** [openjs-foundation/summit#254]
**Topic of the session**
jQuery Core Team & Maintainer Session

**Type of the session**
- [x] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**
This is up for discussion. Whatever you think is reasonable.

**Level**
- [ ] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**
Participants are the jQuery Core team.

**Describe the session**
This would be an informal session where the core maintainers and other contributors could hack on certain upcoming features (such as the event system rewrite) and discuss some of the changes that we have brewing. It would not have a presentation.

**Session facilitator(s) and Github handle(s)**
@timmywil 

**Additional context (optional)**

No specific time, and it's all in-persion.

**Comment by jorydotcom** [comment]
Hey @timmywil it looks certain that the Collab Summit will be online only, and we expect to announce that sometime in the next week or two. Can you update your issue to include your timezone info if you are still able / interested in hosting this session?

**Comment by jorydotcom** [comment]
@timmywil we're looking to put the sessions on the schedule next week, does 9 a.m. GMT-5 on June 25 work for your availability?

**Comment by timmywil** [comment]
@jorydotcom that should be fine

**Comment by jorydotcom** [comment]
[Notes to from the session room](https://docs.google.com/document/d/1jW4HKxF65bGIYcAoNyTBIxhWjMagef9E0ip4IXvsG1w/edit)

This session was not recorded.
