### ISSUE TITLE
Session Proposal: Introduction to Fastify

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/summit#263]
### Proposal

**Topic of the session**

Introduction to Fastify

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

(I can also arrange this as a "code-and-learn" style workshop, where I would ask participants to contribute a PR.

**Estimated duration of the session**

30 minutes for the "talk", 1-2 for the workshop format

**Follow-up / Set-up sessions (if any)**

None so far, likely there will be another one on Fastify.

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

- Node.js
- HTTP

**Describe the session**

In this session we will cover the basics of the Fastify framework, its key features and how they map to its dependencies. We will also cover its plugin architecture and who we reached having hundreds of plugins in the span of a few year.
Finally, we will cover how to get started in contributing to the framework.

**Session facilitator(s) and Github handle(s)**

Matteo Collina - @mcollina 

**Additional context (optional)**

This is likely going to be a remote session, as I expect to _not_ be able to travel to the US in June.
I'm the CEST timezone.

I would schedule this is in the "new contributors track"

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [x] New Contributor Orientation Track
- [ ] Regular Track

**Triage**

- [x] Track chosen
- [x] Scheduled

**Comment by mcollina** [comment]
cc @delvedor

**Comment by benjamingr** [comment]
This sounds fun, maybe relevant for you and the initiative @neta-kedem ?

**Comment by jorydotcom** [comment]
Hi @mcollina - I'd like to confirm that you're available to run this session at 9 a.m. GMT-5 on Monday, June 22. Let me know if that works and we will get it added on the website!

Also, please share any information you would like to surface to attendees prior to the session. If there are links, install directions, etc that would be great to include!

**Comment by mcollina** [comment]
Confirmed! Nothing really, it would likely be a chat.

@delvedor would you be able to attend as well?

**Comment by jorydotcom** [comment]
[Notes from the session room](https://docs.google.com/document/d/1Za7hfIGpUUjcot7OfoDlAaF2eSeJy5sUT3uu286__4o/edit)

@mcollina do you recall if this session was recorded?

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
