### ISSUE TITLE
Session Proposal: Contributing to WebdriverIO

### ISSUE THREAD

**Issue by christian-bromann** [openjs-foundation/summit#264]
### Proposal

**Topic of the session**

Contributing to WebdriverIO

**Type of the session**

- [ ] Collaborate
- [x] Workshop
- [x] Talk

The session will contain an introduction talk followed by a workshop that aims to help people understand the framework and how to contribute to the project.

**Estimated duration of the session**

30 minutes for the "talk", 1-2 for the workshop format

**Follow-up / Set-up sessions (if any)**

n/a

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Besides some basic coding skills there are no specific pre-requisite knowledge required.

**Describe the session**

There are thousand ways if not more how you can setup your automation testing environment. It is often crucial when it comes to stability and maintainability. While you can build a custom framework that fits your needs there are often already sophisticated setups or frameworks available that get you up and running very quickly.

WebdriverIO is one of these frameworks that is written in Node.js. It gets you up and running within minutes and allows you to scale up your test suite while maintaining your execution time by running tests in parallel. With its huge project community it is an ideal choice for small as well as big projects that use modern frameworks such as React, Angular or Vue.js.

In this session you will learn everything you need to know to run a successful, stable and maintainable WebdriverIO framework. The maintainer team will tell you everything from the basic concepts up to complex testing strategies you can do with WebdriverIO like frontend performance testing as well as complex browser interaction with Puppeteer.

**Session facilitator(s) and Github handle(s)**

Christian Bromann - @christian-bromann 

**Additional context (optional)**

Depending on the interest I am happy to also make this a Code&Learn style workshop to teach people how to contribute to the project.

I am located in __Central European Time (CET)__

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [x] New Contributor Orientation Track
- [ ] Regular Track

**Triage**

- [x] Track chosen
- [x] Scheduled

**Comment by jorydotcom** [comment]
@christian-bromann will you update your issue to include your timezone? realizing we should probably update the issue template to gather that info...

**Comment by christian-bromann** [comment]
@jorydotcom updated the issue post. I will draft a PR for adding the timezone.

**Comment by jorydotcom** [comment]
Hi @christian-bromann - I'd like to confirm that you're available to run this session at 10 a.m. GMT-5 on Monday, June 22. Let me know if that works and we will get it added on the website!

Also, please share any information you would like to surface to attendees prior to the session. If there are links, install directions, etc that would be great to include!

**Comment by christian-bromann** [comment]
I can confirm. Looking forward to it!

**Comment by designMoreWeb** [comment]
Is there a link to attend this?

**Comment by christian-bromann** [comment]
@designMoreWeb you need to sign up for https://collabsummit.qiqochat.com/ and join the session.

@jorydotcom any objections sharing the Zoom link in here?

**Comment by jorydotcom** [comment]
[Notes from the session room](https://docs.google.com/document/d/1nZG6DFfPLlCK7fL1TQZPTW14xnteYfQu25uj4caJvh4/edit)

[Link to the recording](https://youtu.be/QaA5C1Y4BH0)
