### ISSUE TITLE
Update Session Facilitator Guide to include Online-First Guidance

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/summit#268]
We need to update our [Session Facilitator guides](https://github.com/openjs-foundation/summit/blob/master/SESSION_FACILITATOR_GUIDE.md) to reflect and support the reality of a distributed event. @darcyclarke has volunteered to help with this as well. 

Some of the things we want to capture include: 
* Using teleconference moderation tools
* Best practices for remote presentations
* Making your presentation artifacts accessible, localized, and available
* Facilitating remote discussions
* Recording your sessions
* Producing collaborative artifacts (meeting notes, shared code)

**Comment by darcyclarke** [comment]
@jorydotcom can we set up a time to do a call/test of some of these tools? I think you have my email already but I should have some time next week to schedule something.

**Comment by jorydotcom** [comment]
@darcyclarke sounds good to me; how about next Friday?

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
