### ISSUE TITLE
Create 'New Contributor Resources' to support new contributor track

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/summit#269]
To best support new community members who may join is for our "New Contributor Track" of programming, we are looking to compile high quality resources such as:

* "First Timers Only" materials
* Getting Started Guides
* Terms & Phrases
* Git / GitHub 101...

and other reference materials that would be useful to a new participant in our projects. We would like to package this up for registrants before the event so they have a way to orient themselves prior to the sessions. 

See #251 for more info on the New Contributor Track

**Comment by mcollina** [comment]
Really good idea. Ideally it should include a few tutorials and Do&Dont's on how to contribute to GH to JS projects.

**Comment by joesepi** [comment]
Coincidentally, I've started sketching out an "OpenJS New Contributor's Handbook here: https://hackmd.io/JLEWCkatT_qNNsKmRb_4BQ

I'm happy to move the small amount of work I have there to a repo if others would prefer and contribute.

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
