### ISSUE TITLE
Session Proposal: Promises developer exprience

### ISSUE THREAD

**Issue by benjamingr** [openjs-foundation/summit#272]
### Proposal

**Topic of the session** Promises developer exprience

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator** I am in GMT+2 but I am used to sessions in quirky times.

**Estimated duration of the session** 1-2 hours probably

**Level** C

- [ ] Beginner
- [ ] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

I am looking specifically for core collaborators (ping @mcollina @BridgeAR @addaleax ) and other involved parties in order to figure out together ideas for improving the promises debugging situation.

Participants that are not node-core are welcome

I specifically don't want to discuss the unhandled rejection issue if possible and focus on other things like Matteo's initiatives.

Also maybe @ronag would be a good person to collaborate on this with?

**Describe the session**

Mostly an open discussion of where we are in terms of promises debugging and how are things progressing. Maybe share some information about async iterator usage and how that's working out

**Session facilitator(s), Github handle(s) and timezone(s)** @benjamingr , although I am open to another facilitator I just want the discussion to happen :]

**Additional context (optional)** Looking forward to this :]

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [x] Regular Track
- [ ] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by benjamingr** [comment]
I opened this - but I am entirely fine with other people working on this and picking this up if they want. I just want the discussion to be had.

This was effective in the 2018 and 2019 summits :]

**Comment by mcollina** [comment]
Count me in!

**Comment by mmarchini** [comment]
I'm interested!

**Comment by mmarchini** [comment]
@jorydotcom would it be possible to change the schedule so this session doesn't overlap with diagnostics? There's a good intersection across folks interested in both topics.

**Comment by mmarchini** [comment]
Also, `Promises Developer Experience` and "`AbortController` in core" overlap (first ends at 10:30, second starts at 10:00), but both are hosted by @benjamingr (if this was discussed and resolved already, please ignore this comment).

**Comment by benjamingr** [comment]
@mmarchini I sent @jorydotcom an email about it a few days ago but haven't gotten a response so my plan is: either end one session early or start another late.

**Comment by benjamingr** [comment]
@mmarchini this has been resolved (thanks Jory!) and the sessions no longer overlap.

**Comment by benjamingr** [comment]
Proposed (rough) agenda (feedback and modifications welcome.
 - Promises survey status and our plans with it and unhandled rejections (cc @mmarchini )
 - Async iterator support in all our API, `pipeline` and the explosion of async-iterator adoption
   - Namely: I'm interested in any insights people have regarding issues people find when using them
 - Debugging experience: what can we do to improve the developer experience of people using promises?
 - Education: can/should we take a more active role educating our users on how to write safe / performant promises code in Node.js?

**Comment by benjamingr** [comment]
https://docs.google.com/document/d/19lEj6h1xDe1I2lEvW_HSoyYG1OfAJO2PLe4dNE7gJ0w/edit?usp=sharing

**Comment by jorydotcom** [comment]
[Notes from session room](https://docs.google.com/document/d/1q7V-3Y0wLQ_JRIw6WeS3BXA7FYZmvfnLDzKKJcBHP7I/edit)

@benjamingr do you recall if this session was recorded?

**Comment by benjamingr** [comment]
This session was recorded with Zoom (cloud) :]

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
