### ISSUE TITLE
Session Proposal: Package Maintenance Working Group For Maintainers

### ISSUE THREAD

**Issue by wesleytodd** [openjs-foundation/summit#275]
### Proposal

**Topic of the session**

The Package Maintenance Working Groups will present what we are working on for project maintainers. 

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [X] Talk

**Session facilitator(s), Github handle(s) and timezone(s)**

- @wesleytodd (Pacific US Time)
- @ghinks, you are interested right? (Eastern US Time)
- Other members of @nodejs/package-maintenence TBD (discussion: https://github.com/nodejs/package-maintenance/issues/335)

**Estimated duration of the session**

1 hour

**Follow-up / Set-up sessions (if any)**

**Level**

- [ ] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

None, but we hope to reach project maintainers.

**Describe the session**

The Package Maintenance will present some of our work to open a conversation with project maintainers (OpenJSF member projects or external).  We hope to find partners to work with on our programs, as well as get feedback from important projects in the ecosystem.

**Additional context (optional)**

See here for our team discussion: https://github.com/nodejs/package-maintenance/issues/335

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [x] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by ghinks** [comment]
I'm signing on with you @wesleytodd

**Comment by ghinks** [comment]
@wesleytodd I'm going to start a draft document. It will at least be a starting point.

**Comment by ghinks** [comment]
@jorydotcom Jory how long are these talks? Previously we have talked, when I say **we** I mean @wesleytodd , for about 10 minutes then opened the floor up to questions. As the format is remote and what we have done previously in person may be difficult I find myself wondering how format the presentation.

**Comment by jorydotcom** [comment]
@ghinks they can be as long as you want or need, but I'm encouraging shorter 'talks' so that there's more time for discussion. It would be better to think about it less as a 'Talk' and more like a short presentation that frames a discussion. You will have as much (or as little) time as you need!

**Comment by ghinks** [comment]
🙏🏻

**Comment by wesleytodd** [comment]
I see [this doc got merged](https://github.com/openjs-foundation/summit/blob/master/2020-06-23-Austin/agenda.md), so disregard!

**Comment by ghinks** [comment]
@wesleytodd I sent you access to the slides and the talk notes.

I have incorporated the talk notes into the slides and I have emailed you access to them on slides.com

**Comment by wesleytodd** [comment]
Yep, that email was buried, but I just logged in and it looks like a good structure.  I will add some comments into the slides.com comments tonight!

**Comment by ghinks** [comment]
Excellent, we will almost certainly have to get on a call together to align before we present

**Comment by ghinks** [comment]
@jorydotcom, apologies just read the instructions can you add me to the QIQO access list for the event. Sorry @wesleytodd just reading these instructions for Friday.

**Comment by wesleytodd** [comment]
@ghinks You just need to register for the event.  There were some issues with it on Monday, but I assume those are worked out and just registering on both platforms with the same email (like the instructions detail) should work.

**Comment by wesleytodd** [comment]
Closing, as session is complete and went well.  Thanks all!

**Comment by jorydotcom** [comment]
[Notes from the session](https://docs.google.com/document/d/1-WWpR2suSr8ShQ_kbhEq7sdRkGGCUNIURGBOERmphPs/edit)

@wesleytodd do you recall if this session was recorded?
