### ISSUE TITLE
Session Proposal: HTTP/2/3 evolution

### ISSUE THREAD

**Issue by Ethan-Arrowood** [openjs-foundation/summit#278]
### Proposal

**Topic of the session**

The topic of this session is to discuss the evolution of HTTP, HTTP2, and HTTP3 in Node.js. We want to invite frameworks maintains and Node.js collaborators so we can share perspectives and make progress together. 

cc [@nodejs/web-server-frameworks](https://github.com/orgs/nodejs/teams/web-server-frameworks) [@nodejs/quic](https://github.com/orgs/nodejs/teams/quic) [@nodejs/http](https://github.com/orgs/nodejs/teams/http) [@nodejs/http2](https://github.com/orgs/nodejs/teams/http2)

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**

Facilitators are in multiple different time zones. Please favor the European based ones for scheduling purposes.

**Estimated duration of the session**

1 hour

**Follow-up / Set-up sessions (if any)**

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Familiarities with the [web-server-frameworks](https://github.com/nodejs/web-server-frameworks) working group. 

> will update this section when we have relevant issues in our repo

**Describe the session**

This session will be a discussion on the status of http/2/3 in Node core. The main discussion points will be focussed around "whats coming next" for each of these modules. We will hear from @jasnell on how QUIC is doing. One of the other key talking points will be about adoption of http 2 and 3 in real-world scenarios. The WG has discussed this previously so it'll be great to revisit this discussion and see what we can do to better support developers. 

If you have other topic ideas please feel free to comment them on this issue and we'll bring them up in the discussion. 

**Session facilitator(s), Github handle(s) and timezone(s)**

Ethan Arrowood (@Ethan-Arrowood) - EST 
Matteo Collina (@mcollina) - CEST

**Additional context (optional)**

I do not need to be facilitator for this if someone else is better suited. Just putting my name down because I'm more than happy to do so, and I've been facilitating the web-server-framework working group calls.

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [x] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

----

TCQ: https://tcq.app/meeting/5kWx

**Comment by benjamingr** [comment]
This looks cool, is the goal to gather feedback from framework authors and make decisions on APIs or how to push [QUIC](https://github.com/nodejs/quic)? What sort of feedback would be helpful? 

(In any case I'd ping James and nodejs/quic if the goal is to get feedback to people working on http3 in Node.js and I can think of some other people in core :])

**Comment by Ethan-Arrowood** [comment]
Ahh yes! I knew I forgot something. Meant to cc quic, http, and the other groups here as well. 

@benjamingr and yes that is very much what we are interested in doing. We've had some conversations already during the WG calls about supporting things like QUIC. One of the main pain points we have identified is how users actually are using the http/2/3 apis being built. We hope this session would allow us to really focus on it for a whole hour and make some actionable moves to improving userland things.

**Comment by benjamingr** [comment]
Ah, I can't ping Node teams from here apparently because it's a different organization. That's an interesting result of being the OpenJS foundation but having Node in nodejs/node :]

**Comment by Ethan-Arrowood** [comment]
I'll make a note to ping them through twitter/email then 😉

**Comment by mcollina** [comment]
count me in!

**Comment by Ethan-Arrowood** [comment]
@mcollina i can add you as a facilitator, what is your time zone?

**Comment by jasnell** [comment]
No worries about notifying me, I spotted it ;-) ... yes I'll definitely attend and can give an update on where we are at with the implementation and current thinking around the API.

**Comment by mcollina** [comment]
I’m in CEST.

**Comment by Ethan-Arrowood** [comment]
Do we know if this is happening or not, and if so when it'll be? Just looking to set aside the time to attend and give my team at work the heads-up I might be out.

**Comment by benjamingr** [comment]
@Ethan-Arrowood - it appears to be [on the agenda](https://github.com/openjs-foundation/summit/pull/298/files#diff-e7574fa224465363dc667df0f9cfead1R114) so I'd assume so :]

**Comment by Ethan-Arrowood** [comment]
I must've missed that notification. I'll make sure to set aside the time 😄 looking forward to it!

**Comment by Ethan-Arrowood** [comment]
If anyone would like to have a short call prior to the conference to do a little bit of planning for this session please let me know! My schedule is flexible and can support multiple timezones. 

Additionally, if you have thoughts you'd like to share but may not be able to attend please comment here and I'll do my best to include them in the sessions discussion.

**Comment by jasnell** [comment]
When is this session?

**Comment by Ethan-Arrowood** [comment]
https://github.com/openjs-foundation/summit/blob/master/2020-06-23-Austin/agenda.md#collaborator-summit-day-three-cross-project-summit-day-26-june-2020

Day 3, 14:00-15:00 GMT-5

**Comment by jorydotcom** [comment]
[Notes from the session room](https://docs.google.com/document/d/15ubsehzqhU_3YoLFBH_sxGj-ZJyVNAjC6oNkONWj9FE/edit)

@Ethan-Arrowood do you recall if this session was recorded?

**Comment by Ethan-Arrowood** [comment]
Yes it was! I sent over the recording too. Let me know if you need my help
tracking it down.
-- 


Ethan Arrowood

GitHub <https://github.com/Ethan-Arrowood> | Twitter
<https://twitter.com/ArrowoodTech>

**Comment by jorydotcom** [comment]
@Ethan-Arrowood great! I'll get it from Celia.

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
