### ISSUE TITLE
Session Proposal: Node.js the next 10 years - kickoff

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/summit#279]
### Proposal

**Topic of the session**

Planning for a successful next 10 years of Node.js

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**

- EST

**Estimated duration of the session**

1.5 to 3 hours depending on how much time we can get.

**Follow-up / Set-up sessions (if any)**

**Level**

- [ ] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

**Describe the session**

Node.js the next 10 years - kickoff. The TSC has been discussing how to do a summit on what we should focus on to repeat the success of the 10 years of Node.js (see https://github.com/nodejs/TSC/issues/797#issuecomment-595960246 for proposed agenda).  Originally we were thinking of in person but given the current situation we discussed virtual in https://github.com/nodejs/TSC/issues/836 but there are many challenges.

What we have agreed is that we'd like to do a kickoff as part of the OpenJS World Collaborator summit.   Ideally covering:

* Retrospective (1-2 hours?)
  * What were the key things that made Node.js successful in the last 10 years
  * What were the key values that supported that success
  * What worked in the management of the project, what did not

* Looking Forward
  * Review of Key technologies/trends that will influence what we should do in Node.js and
    agree on prioritized list of those we should do further deep dives on.

**Session facilitator(s), Github handle(s) and timezone(s)**

Michael Dawson (@mhdawson)

**Additional context (optional)**

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [ ] Cross-Project Track

**Triage**

- [ ] Track chosen
- [ ] Scheduled

**Comment by mmarchini** [comment]
I'll miss this session, unfortunately :/

Will there be recordings for folks to watch later?

**Comment by mhdawson** [comment]
I think it uses zoom so we should be able to record.

**Comment by mhdawson** [comment]
@mmarchini here is the link: https://youtu.be/Xuk5Rq7q7LM

**Comment by jorydotcom** [comment]
[Link to room notes](https://docs.google.com/document/d/1lm8xPzoEpayzPaSM5r0KBnryamR3IvRszZdoxC4YJxw/edit)

[Link to recording](https://www.youtube.com/watch?v=Xuk5Rq7q7LM&feature=youtu.be)
