### ISSUE TITLE
Session Proposal: TC53 meeting

### ISSUE THREAD

**Issue by dtex** [openjs-foundation/summit#280]
### Proposal

**TC53 - ECMAScript Modules for Embedded Systems Meeting**

**Quarterly, "in-person" meeting for [ECMA TC53](https://www.ecma-international.org/memento/tc53.htm)** 

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**

- Pacific Time (US) PDT UTC-7

**Estimated duration of the session**

Typically in-person TC53 meetings last a full two days, but this virtual agenda is TBD.

**Follow-up / Set-up sessions (if any)**

Resuscitating IoT with JavaScript - Peter Hoddie & Lizzie Prader (Peter is the TC53 Chair)

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

None

**Describe the session**

TC53 is the ECMA standards body charged with supporting activities that would lead to an ECMAScript-based platform for embedded systems and extensions to ECMAScript. This includes defining requirements, harmonizing user communities, and studying the impact on privacy and security. 

**Session facilitator(s), Github handle(s) and timezone(s)**

Peter Hoddie (@phoddie) - PDT

**Additional context (optional)**

This meeting was originally scheduled to take place in Austin during the Summit to facilitate participation for attendees. Once the Summit became virtual we chose to do the same for TC53, but we still want the event to be available for anyone who is interested.

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [x] Regular Track
- [x] Cross-Project Track

**Triage**

- [x] Track chosen
- [x] Scheduled

**Comment by jorydotcom** [comment]
This is on the schedule! 
- Starting June 25 at 10 a.m.
- Continuing June 26 at 10 a.m.

**Comment by jorydotcom** [comment]
[Notes from the meetings](https://docs.google.com/document/d/1UBotuzqLDFVGz8cZ2RPN_cGm0oHibuA8cTVQDlXM3Xs/edit)

@dtex do you recall if this was recorded?

**Comment by dtex** [comment]
Yes, at least some of it was. I believe @phoddie or @lizzieprader will know where to find it

**Comment by phoddie** [comment]
I have a video file recording of each day. Ecma doesn't usually post recordings of meetings, so I'm not sure what to do with them. I'm happy to follow the sense of the committee.

**Comment by jorydotcom** [comment]
@phoddie @dtex the foundation is posting recorded summit sessions on its YouTube Channel, we're happy to post them there if you want. My assumption is that it would be ok sense it was mostly an open meeting but up to you! 🤷

**Comment by phoddie** [comment]
How about one of you post to the TC53 mailing list that we intend to post these early next week? Give people an opportunity to object, and then we can move ahead.  

FWWI - we did announce during the meeting when recording began, so it was known. 

@jorydotcom - meanwhile, let me know where to upload the files. Or maybe we just put theme on the spiffy new [EcmaTC53 YouTube channel](https://www.youtube.com/channel/UCEhkWFxgZbJQ7cFMAVdJBSg)?

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
