### ISSUE TITLE
Session Proposal: Dojo track

### ISSUE THREAD

**Issue by dylans** [openjs-foundation/summit#281]
### Proposal

We would like to offer a mini-track for those interested in getting started with using and/or contributing to Dojo. This would be in addition to our Dojo workshop.

**Topic of the session**

* Part 1: Introduction to modern Dojo
* Part 2: Making your first contribution to Dojo
* Part 3: Office hours/support for questions from the Dojo workshop

**Type of the session**

- [x] Collaborate
- [x] Workshop
- [x] Talk

**Timezone of facilitators**

Mix of BST and PDT

**Estimated duration of the session**

* 1 hour for introduction
* 1 hour for first contribution
* TBD for office hours/support

**Follow-up / Set-up sessions (if any)**

We see this as a track/progression which is why we proposed it as one issue. Let me know if we need to split this up.

**Level**

- [x] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

* Modern JavaScript and TypeScript development is beneficial.
* Attending the conference Dojo workshop is beneficial.

**Describe the session**

Part 1: An introduction to the features and key APIs of building applications with modern Dojo, a progressive and reactive TypeScript framework.

Part 2: Learn the steps to identify an issue, make a contribution, test, open a PR, review the CI results, and then request a review.

Part 3: Need help either building your first Dojo app or making your first Dojo contribution? The Dojo team will be available to answer your questions and review your code.

**Session facilitator(s), Github handle(s) and timezone(s)**

Dylan Schiemann (@dylans) - PDT, Matt Gadd (@matt-gadd) - BST, Anthony Gubler (@gubler) - BST

**Additional context (optional)**

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [x] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [ ] Cross-Project Track

**Triage**

- [x] Track chosen
- [x] Scheduled

**Comment by jorydotcom** [comment]
@dylans were you imagining this would be better run on the new contributor day or on the project day? I think it works either day!

**Comment by dylans** [comment]
Hi @jorydotcom I agree that it works either way, or we could split it across days if that's better. We're flexible!

**Comment by jorydotcom** [comment]
Hi @dylans @matt-gadd @gubler - I'd like to confirm that you're available to run this session at 11 a.m. GMT-5 on Monday, June 22. Let me know if that works and we will get it added on the website!

Also, please share any information you would like to surface to attendees prior to the session. If there are links, install directions, etc that would be great to include!

**Comment by gubler** [comment]
I think there is some confusion. I know nothing about Dojo and I have not volunteered to do _anything_ for your foundation. I assume this is a case of mistaken identity. I am Daryl Gubler, not Anthony Gubler.

**Comment by jorydotcom** [comment]
Terribly sorry Daryl!

**Comment by gubler** [comment]
Mistakes happen - no worried :) 

I hope you event goes well.

**Comment by dylans** [comment]
This works for us @jorydotcom

**Comment by jorydotcom** [comment]
[Notes from the session room](https://docs.google.com/document/d/1l2tgJgUa4r9h-oXNQEzr9Cd-4bqyfoC1M_jRJPpdUGc/edit)

@dylans do you recall if this session was recorded?

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
