### ISSUE TITLE
Session Proposal: npm OpenRFC meeting

### ISSUE THREAD

**Issue by ruyadorno** [openjs-foundation/summit#282]
### Proposal

**Topic of the session**
npm open rfc meeting

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**
- Eastern Time Zone, North-America

**Estimated duration of the session**
1 hour

**Follow-up / Set-up sessions (if any)**
N/A

**Level**

- [x] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**
Anyone interested in the future of npm - that said, people can also head to [rfcs](https://github.com/npm/rfcs) repo in order to familiarize with proposals or send their own.

**Describe the session**
npm open rfc session - will have an agenda composed of the active rfc proposals, recap of state of things in the npm cli, onboard new collaborators.

**Session facilitator(s), Github handle(s) and timezone(s)**
@darcyclarke and @ruyadorno

**Additional context (optional)**
@npm has been holding virtual open rfc meetings in order to better communicate with the broader community and this collaboration session is an opportunity to discuss some of the ongoing topics with active members of the summit while also onboarding new folks that want to participate in the development of the npm cli.

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [ ] Cross-Project Track

**Triage**

- [ ] Track chosen
- [ ] Scheduled

**Comment by jorydotcom** [comment]
Would ya'll rather put this on the project track or cross-project track?

**Comment by jorydotcom** [comment]
[Notes from the session room](https://docs.google.com/document/d/1X87rH-P2rHRP6OWEDufDBmie3SeYJLUQBTDsf5ckiL0/edit)

[Link to the session recording](https://www.youtube.com/watch?v=2tlQjyfjSek)
