### ISSUE TITLE
Session Proposal: Contributing to Express

### ISSUE THREAD

**Issue by wesleytodd** [openjs-foundation/summit#283]
### Proposal

**Topic of the session**

Express has a growing contributor base, learn different ways to contribute to the project.

**Type of the session**

- [X] Collaborate
- [X] Workshop
- [X] Talk

**Timezone of facilitator**

- Pacific Time

**Estimated duration of the session**

1 hour or less, open for discussion

**Follow-up / Set-up sessions (if any)**

None

**Level**

- [X] Beginner
- [X] Intermediate
- [X] Advanced

**Pre-requisite knowledge**

None.

**Describe the session**

We will talk though the work Express is doing to grow it's community, focusing on the Triage team and other proposals Express has in the works to grow.

**Session facilitator(s), Github handle(s) and timezone(s)**

- Wes Todd (@wesleytodd) PT
- Other interested Express Triagers? Will post this in our issues to see who is interested.

**Additional context (optional)**

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [x] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [ ] Cross-Project Track

**Triage**

- [x] Track chosen
- [x] Scheduled

**Comment by jonchurch** [comment]
Count me in for this

**Comment by jorydotcom** [comment]
Hi @wesleytodd @jonchurch - I'd like to confirm that you're available to run this session at 11 a.m. GMT-5 on Monday, June 22. Let me know if that works and we will get it added on the website!

Also, please share any information you would like to surface to attendees prior to the session. If there are links, install directions, etc that would be great to include!

**Comment by jonchurch** [comment]
Room link https://qiqochat.com/breakout/5/zyljofoKNjYrDudmvllbksYuR

**Comment by wesleytodd** [comment]
The session went well.  I think we can close this.

**Comment by jorydotcom** [comment]
[Notes from the session](https://docs.google.com/document/d/17stn5q0nQf9lv3tlyNISAtH6xeRsXCQ-BIsriCNXBPs/edit)

@wesleytodd do you recall if this session was recorded?
