### ISSUE TITLE
Session Proposal: Mocha Contributors' Meeting

### ISSUE THREAD

**Issue by boneskull** [openjs-foundation/summit#284]
### Proposal

A Meeting about Mocha

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

UTC-7

- 1hr

**Estimated duration of the session**

n/a

**Level**

- [ ] Beginner
- [x] Intermediate
- [x] Advanced

Attendees should, at minimum, have used Mocha.

**Pre-requisite knowledge**

This collaboration session will likely focus on issues of concern to current & prospective contributors, but we're also happy to talk with users.  We can also talk about how to start contributing, and have Q&A if time allows.

- Christopher Hiller (@boneskull) - UTC-7
- (potentially another who would be UTC)

**Session facilitator(s), Github handle(s) and timezone(s)**

I would be leading this session from my house, yeah.

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [x] Regular Track
- [ ] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by jorydotcom** [comment]
hello @boneskull - looking to put this session in a time slot; would 3 p.m. GMT-5 on June 25 (1 p.m. GMT-7) work for ya'll?

**Comment by boneskull** [comment]
pinging @craigtaub who may also attend

**Comment by craigtaub** [comment]
Yep i'm registered and plan to be there. UK is GMT+1 right now so believe thats 9pm Thurs 25th.

**Comment by boneskull** [comment]
That works for me then

**Comment by ghinks** [comment]
@boneskull  et al I have been working with @wesleytodd and the package maintenance group. We have been successful in creating an ExpressJS triage team which labels issues for the express project. The aim is to create a group of repo maintainers that graduate through the ranks.
Does the Mocha project need assistance? I am asking I am trying to organize at the company I work for and we have started engaging with the OpenJS org. We want to get our developers more involved in contributing to existing projects. 

The package maintenance team and the express maintainers have talks and I think that I may be able to help with a pipeline of able developers.

Glenn Hinks ( @ghinks )

**Comment by boneskull** [comment]
@ghinks thanks Glenn. tbh our issues get triaged pretty regularly, but we could always use help from people who understand the codebase and are able to merge PRs... not sure what the scope of the effort is

**Comment by jorydotcom** [comment]
[Notes from the session room](https://docs.google.com/document/d/1mtgbG6Sj7W1jB7HI6y9Kdv95ONslvdJGwhlGhzh5ZbA/edit)

@boneskull do you recall if this session was recorded?

**Comment by boneskull** [comment]
I don’t know, I just used the built-in thing. If I was supposed to do something to record it, I didn’t know...

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
