### ISSUE TITLE
Session Proposal: Building nodes for Node-RED

### ISSUE THREAD

**Issue by knolleary** [openjs-foundation/summit#285]
### Proposal

**Topic of the session**

Building Nodes for Node-RED

**Type of the session**

- [ ] Collaborate
- [x] Workshop
- [ ] Talk

**Timezone of facilitator**

- UTC+1

**Estimated duration of the session**

2 - 3 hours

**Level**

- [ ] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Participants should be familiar with:
 - Node-RED
 - Node.js/JavaScript

Ideally, they will have an idea for a node they want to create. Maybe they already have one started, but are looking for advice.

**Describe the session**

This workshop will run through the process of creating a node for Node-RED. Introducing the concepts involved, how to setup a development environment and how to create tests for the result.

**Session facilitator(s), Github handle(s) and timezone(s)**

 - Nick O'Leary (@knolleary) UTC+1
 - Dave Conway-Jones (@dceejay) UTC+1

**Additional context (optional)**

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [x] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [ ] Cross-Project Track

**Triage**

- [x] Track chosen
- [x] Scheduled

**Comment by jorydotcom** [comment]
Hi @knolleary @dceejay - I'd like to confirm that you're available to run this session at 9 a.m. GMT-5 on Monday, June 22. Let me know if that works and we will get it added on the website!

Also, please share any information you would like to surface to attendees prior to the session. If there are links, install directions, etc that would be great to include!

**Comment by dceejay** [comment]
OK with me.

**Comment by knolleary** [comment]
OK - I think we've dropped the ball on this one as I've been heads down getting my talk for the event sorted.

@jorydotcom how are these sessions going to run? Where are they hosted? What facilities are available? Is it a live-stream video, how do we interact with participants?

I'm slightly nervous this close to the event that we don't really know what the plan is. We haven't promoted it in the node-red community yet as we aren't sure what to promote.

**Comment by knolleary** [comment]
Thanks for the email @jorydotcom - that answers all my questions. May need to rejig what we had planned slightly, but looking forward to it.

**Comment by jorydotcom** [comment]
[Notes from the Session Room](https://docs.google.com/document/d/1Df5W3bDKxdG0h8rd1Z84dekpCRwUQ_rRViDl0udSw0o/edit)

@knolleary do you recall if this session was recorded?

**Comment by knolleary** [comment]
No, it was not recorded.
