### ISSUE TITLE
Session Proposal: WebdriverIO Contributors' Meeting

### ISSUE THREAD

**Issue by christian-bromann** [openjs-foundation/summit#287]
### Proposal

**Topic of the session**

All [project committers](https://github.com/webdriverio/webdriverio/blob/master/AUTHORS.md#project-collaborators) meet to get to meet each other and talk about current and future initiatives on WebdriverIO. Goal of the session is to get to hang out and talk about testing.

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**

- I will create a Doodle to provide some time slots that would be optimal for this session.

**Estimated duration of the session**

1 hour

**Follow-up / Set-up sessions (if any)**

For everyone interested in getting to know how to contribute to WebdriverIO please join the #264 session where we both will introduce WebdriverIO as framework as well as help people onboard and contribute.

**Level**

- [ ] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

While this session is mainly aimed to current contributors we welcome everyone who is interested to get to know the team behind WebdriverIO.

**Session facilitator(s), Github handle(s) and timezone(s)**

Christian Bromann (@christian-bromann) - CEST

**Additional context (optional)**

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [x] Regular Track
- [ ] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by jorydotcom** [comment]
[Notes from the Meeting Room](https://docs.google.com/document/d/14tPAVssYGh4NLpkQudODQEFEgVAtzW9W92-sAqSSjiQ/edit)

[Link to recording](https://youtu.be/HqIstZSsCTA)
