### ISSUE TITLE
Session Proposal: MDN — frameworks update, and JS beyond the browser

### ISSUE THREAD

**Issue by chrisdavidmills** [openjs-foundation/summit#290]
### Proposal

**Topic of the session**

MDN — frameworks update, and JS beyond the browser

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**

- UK, BST

**Estimated duration of the session**

Probably an hour would be sufficient.

**Follow-up / Set-up sessions (if any)**

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

I've said beginner, but really people of any level would be really helpful in this session.

**Pre-requisite knowledge**

It would be good for attendees to review the materials I will be discussing before they attend:

* https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools
* https://wiki.developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks

**Describe the session**

I would like to discuss the material I've ended up publishing on MDN about client-side tooling and JS frameworks, especially seen as last year's JS collab summit was such a significant event in terms of helping me research it.

For those who have already looked over the material, I'd like to spend some time getting their thoughts on it. For others, I'd like to solicit feedback on how they think it could be improved.

To solicit feedback:

* [Fill in the questionnaire](https://docs.google.com/forms/d/e/1FAIpQLScW9qAVwcS5YXHsBPNjkC9CfETrr2pGxmGxpSdt6NUtcSM_Wg/viewform)
* Write freeform feedback on my [JS collab summit feedback doc](https://docs.google.com/document/d/1Xjm9VN3T5vYsGTvN1Y6p4lMFwIIx9JhPnFPAAheyHOk/edit?usp=sharing)
* [Tweet me](https://twitter.com/chrisdavidmills) or [email me](mailto:cmills@mozilla.com)

In the second half of the session, I'd like to talk a bit about JS beyond the browser — is it appropriate for coverage on MDN, and if so, in what way? At the moment we have the module [Express web framework (Node.js/JavaScript)](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs) 

**Session facilitator(s), Github handle(s) and timezone(s)**

Chris Mills (@chrisdavidmills), BST

**Additional context (optional)**

I guess all the sessions are going to be held remotely now? I am happy to run it at any time, as long as it doesn't get too early or late for my timezone. Some time up to about 8pm is OK.

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [x] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by jorydotcom** [comment]
there were no notes on this session and it was not recorded.
