### ISSUE TITLE
Session Proposal: Internationalization & Globalization support for Node.js

### ISSUE THREAD

**Issue by obensource** [openjs-foundation/summit#292]
### Proposal

**Topic of the session**

"Get up to date with Internationalization and Globalization support for Node.js! 🌍🌎🌏"

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [x] Talk

**Timezone of facilitator**

- UTC-7 (PDT)

**Estimated duration of the session**

Likely 1 hour, but open for discussion.

**Follow-up / Set-up sessions (if any)**

**Level**

- [x] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

This open session will be hosted by members of the [Node.js i18n](https://github.com/nodejs/i18n) WG, and welcomes everyone who is interested in understanding more about the following topics:
* **Globalization**: making all things accessible to all people through Unicode (ICU & CLDR), and the ECMA-402 specification (which defines JavaScript's [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) object).
* **Internationalization & Localization**: Making all of node's official information (eg. nodejs.dev and nodejs.org) available to everyone, in every language.

**Describe the session**

The format of this session will be divided into 3 parts:
* A brief overview of the history of Globalization's evolution as achieved through projects of the [Unicode Consortium](https://home.unicode.org/) (Unicode, ICU, CLDR), from its beginnings on through to exciting new developments like [ICU4X](https://github.com/unicode-org/icu4x). This will also cover how this work has enabled localization initiatives like [i18n](https://github.com/nodejs/i18n) in node, and what the new relationship between the OpenJS Foundation and the Unicode Consortium means for projects like ICU, CLDR, and their scaling role within the JavaScript ecosystem.
* A discussion on the current status of the i18n initiative in node.
* A call for participation in the i18n WG: to support both Globalization in node core, and the localization of node's resources (websites, documentation, etc).

**Session facilitator(s), Github handle(s) and timezone(s)**
Confirmed:
* Ben Michel (@obensource) – UTC-7 (PT)
* Steven Loomis (@srl295) – UTC-7 (PT)
* [Zeke Sikelianos](https://github.com/zeke) (@zeke) – UTC-7 (PT)
* [Alexandr Tovmach](https://github.com/alexandrtovmach) (@alexandrtovmach) – UTC+3 (EET)
* [Eemeli Aro](https://github.com/eemeli) (@eemeli) – UTC+3 (EET)

Potential:
* [José J. Pérez Rivas](https://github.com/JoseJPR) (@JoseJPR) – UTC+1 (WEST)
* [Richard Littauer](https://github.com/richardlitt) (@RichardLitt) – UTC-4 (ET)
* [Nick Schonning](https://github.com/nschonni) (@nschonni) – UTC-4 (ET)
* Anyone who's interested from the [Node.js i18n](https://github.com/orgs/nodejs/teams/i18n) and [i18n-api](https://github.com/orgs/nodejs/teams/i18n-api) teams! 🎉

**Additional context (optional)**

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [x] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by obensource** [comment]
@eemeli would love to have your participation in this as well! 🙌🙏😄

**Comment by zeke** [comment]
I'm in! Is there a date already?

**Comment by obensource** [comment]
@zeke haven't nailed down the official date yet (beyond it being on either June 22, 25, or 26). @joesepi do you know offhand if there's a day/date that will likely be the best fit for our session? 🙏

**Comment by joesepi** [comment]
@obensource I think the expectation would be that this session would be on the last day as we are trying to plan the "cross-project" sessions on day 3, Friday June 26. I think an internationalization session could be beneficial and interesting to a variety of projects and we should work to bring other projects into the session somehow if that works for you all.

**Comment by obensource** [comment]
@zeke there ya go^, the June 26th. 🎉

**Comment by obensource** [comment]
@joesepi definitely, that sounds perfect! 🙌🍻

**Comment by obensource** [comment]
@littledan would love to have your participation in this as well if you're available! 🙌🙏😄

**Comment by leobalter** [comment]
> Anyone who's interested from the Node.js i18n and i18n-api teams!

I'm not part of these teams but I'm interested in at least watching this. Should I sign in somewhere?

**Comment by benjamingr** [comment]
@leobalter it is typically fine to attend summit sessions without being a part of the organizing team. In summits in the past some of the most meaningful contributions came from "outside folk".

Just make sure to [sign up for the summit itself](https://www.cvent.com/events/openjs-collaborator-summit-2020/registration-71e4281e54dd46a0a0e2da15013e52db.aspx?_ga=2.164120568.674445174.1588801738-1126120395.1571424999&fqp=true) (it's free), if you have any issues signing up please contact one of the organizers, or if you have an issue signing up feel free to email me directly (email is in the nodejs/node readme or moderation team list) and we can register you together.

**Comment by alexandrtovmach** [comment]
I'm in :+1:

**Comment by joesepi** [comment]
@leobalter and others: there is some more information on the site here:
https://events.linuxfoundation.org/openjs-world/features/openjs-collaborator-summit/

You can add on the registration to your OpenJS World registration or register for only the Collab Summit. Both links are on that page.

And I think both events are free, if I'm not mistaken.

**Comment by JoseJPR** [comment]
@joesepi I have completed all the steps of the registration form and confirm that the event is free. Add a cost 0 at the end. ;)

**Comment by eemeli** [comment]
@obensource Would be very happy to participate in this. I'm in Finland, so at UTC+3 currently.

**Comment by srl295** [comment]
Registered…

**Comment by obensource** [comment]
@eemeli 🎉🎉🎉

Added you to the facilitator's list! Thanks for joining! 🙏

**Comment by romulocintra** [comment]
+1 Registered

**Comment by jorydotcom** [comment]
[Notes from the Room](https://docs.google.com/document/d/1xtK-w1W_DOQAcepInUOw8nZF1xgKnmLcwRC7Z3GQu_0/edit)

@obensource do you know if the session was recorded?

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
