### ISSUE TITLE
Session Proposal: Unifying hook systems in Node.js

### ISSUE THREAD

**Issue by Qard** [openjs-foundation/summit#294]
### Proposal

**Topic of the session**

Unifying the disparate efforts around building hook systems into Node.js

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**

UTC-8, but I'm available basically any time.

**Estimated duration of the session**

1-2 hours

**Follow-up / Set-up sessions (if any)**

#273 and #293 are likely to be relevant.

**Level**

- [ ] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

Awareness of any hook systems would be helpful

**Describe the session**

Over the years the number of needs emerging for hooking into the API call lifecycle has increased. There are many parallel efforts that could use some unified vision to ensure we come to the most flexible yet performant solution we can.

We've had async_hooks for awhile now, providing an identifying hook into the async stack graph. There was also discussion about a generic diagnostics channel for APIs to communicate diagnostic data to any interested consumers such as APMs. More recently, we've seen efforts around policy enforcement, es module loader hooks, input validation or modification, and mocking.

I would like to discuss what the numerous needs are for a hook system in Node.js, where needs intersect, and chart a path forward to implement something that can satisfy those needs as effectively and as efficiently as possible.

**Session facilitator(s), Github handle(s) and timezone(s)**

Stephen Belanger (@qard) - PST

**Additional context (optional)**

Any exposure to any existing or prior hook-related efforts is helpful, including:

- async_hooks
- [fs hooks](https://github.com/nodejs/tooling/issues/63)
- [audit hooks](https://github.com/nodejs/security-wg/issues/626)
- [child process hooks](https://github.com/nodejs/tooling/issues/48)
- [loader hooks](https://github.com/nodejs/modules/issues/508)
- [policy enforcement](https://github.com/nodejs/node/pull/33504)
- [diagnostics channel](https://github.com/nodejs/diagnostics/issues/180)
- mocking

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [ ] Cross-Project Track

**Triage**

- [ ] Track chosen
- [ ] Scheduled

**Comment by vdeturckheim** [comment]
Huge +1 on this.

**Comment by Qard** [comment]
If anyone is interested in continuing the discussion, I'm arranging another meeting here: https://github.com/nodejs/diagnostics/issues/401

**Comment by jorydotcom** [comment]
[Notes from the session](https://docs.google.com/document/d/1n4-o0XPoRhkoeIxhroo3aW0-V8Oc8S9c-79Z3wmmq-Q/edit)

@Qard do you know if this session was recorded?

**Comment by Qard** [comment]
Hmm...I don’t think it was, unfortunately.

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
