### ISSUE TITLE
Session Proposal: Contributing to `npm`

### ISSUE THREAD

**Issue by darcyclarke** [openjs-foundation/summit#296]
### Proposal

**Topic of the session**

Contributing to `npm`

**Type of the session**

- [x] Collaborate
- [x] Workshop
- [x] Talk

**Timezone of facilitator**

- EDT UTC-4 

**Estimated duration of the session**

1 hour

**Follow-up / Set-up sessions (if any)**

- *Relevant-ish* to @wesleytodd's "Contributing to Express": https://github.com/openjs-foundation/summit/issues/283

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

- Experienced in Node.js/JavaScript
- Comfortable around the command line & debugging
- Familiarity w/ `node-tap` or similar test framework (although `tap` has some fairly unique attributes)
- Have participated in or are familiar with the Node.js [Package Maintenance](https://github.com/nodejs/package-maintenance/), [Tooling](https://github.com/nodejs/tooling) & [Release](https://github.com/nodejs/release/) WGs or our own [Open RFC process](https://github.com/npm/rfcs)
- [Familiarize themselves with our release process](https://github.com/npm/cli/wiki/Release-Process)

**Describe the session**

`npm` is a bundled dependency of **Node.js** & provides some powerful tools to create, install & manage your own project's dependencies; Let's dive into working with & making your first contribution to the `npm` cli.

**Session facilitator(s), Github handle(s) and timezone(s)**

Darcy Clarke (@darcyclarke) - ET  ([Session Guide](https://github.com/openjs-foundation/summit/blob/master/SESSION_FACILITATOR_GUIDE.md))

**Additional context (optional)**

- Let's have some fun!

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [x] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [ ] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by benjamingr** [comment]
Sorry I'm not great at keeping up to date - Is NPM now part of the OpenJS foundation?

**Comment by jorydotcom** [comment]
@benjamingr no - we (collab summit organizers) thought that a session like this would fit the New Contributor theme though

**Comment by jorydotcom** [comment]
[Room Notes](https://docs.google.com/document/d/1TAcCXzkf2By0vll6lNi6U1neXLQtKZrIW6IEMxKU7eU/edit)

@darcyclarke do you recall if this was recorded?

**Comment by darcyclarke** [comment]
@jorydotcom unfortunately not. I remembered about half way in and then couldn't find an option so we continued on without. I have a slide deck we've shared on social as an artifact though.
