### ISSUE TITLE
Session Proposal: Is our approach to consensus working

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/summit#297]
### Proposal

We use various forms of building consensus in our projects. What is your consensus model? What are the challenges to these models? How could we improve them?

**Topic of the session**

Cross Project discussion

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**

- ET / PT

**Estimated duration of the session**

1 hour

**Follow-up / Set-up sessions (if any)**

TBD

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Consensus Seeking Models
Open Source Governance

**Describe the session**

Discuss current consensus seeking models and explore alternatives (such as rough consensus). Possible focus could be on ways our current process enforces unsustainable work structures.

**Session facilitator(s), Github handle(s) and timezone(s)**

@MylesBorins - ET
@maggiepint - PT

**Additional context (optional)**

This has been inspired by a variety of conversations I've had. Some related to burn out of existing contributors, and others related to ways we drive away potential collaborators. It might also be worth exploring if there is a correlation between our consensus models and lack of diversity in our project spaces.

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [x] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by MylesBorins** [comment]
Discussion topics:

* Review [value + mission of OpenJS Foundation](https://openjsf.org/about/)
  * "To create a center of gravity for open source projects throughout the end-to-end JavaScript ecosystem guiding them toward open governance and diverse collaborator bases."
* Do our decision making processes align with our values?
  * How does your project make decisions
  * What are negative patterns of engagement caused by your decision making process
* What kinds of structural changes can we make to better align with the foundation's mission?

**Comment by jorydotcom** [comment]
[Notes from the room](https://docs.google.com/document/d/1KkrDaNYJ3rFeOrzRccrU61CViwOcBlZMNFdGi9n62XM/edit)

Session was not recorded.
