### ISSUE TITLE
Session Proposal: Node.js Tooling Group Collaboration Session

### ISSUE THREAD

**Issue by boneskull** [openjs-foundation/summit#299]
### Proposal

Node.js Tooling Group Collaboration Session

A meeting of the Node.js tooling group, and other interested parties

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**UTC-7**

- I have stuff going on Tuesday at 9-11a and at 1-2p.  We also have a Mocha session Thurs at 1p.  Can't really do anything before 9a (all times UTC-7)

**1 HOUR**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

Attendee should be, at minimum, interested in writing command-line tools in Node.js

TBD

Christopher Hiller (@boneskull) UTC-7
Benjamin Coe (@bcoe) UTC-7

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [ ] Cross-Project Track

**Triage**

- [ ] Track chosen
- [ ] Scheduled

**Comment by boneskull** [comment]
cc @nodejs/tooling

**Comment by jorydotcom** [comment]
[Notes from the Room](https://docs.google.com/document/d/14ZM2pt1WY46DMplwlV72ouO-C8irCbZXZWiD1UNP134/edit)

@boneskull do you recall if this was recorded?

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
