### ISSUE TITLE
Session Proposal: OpenJS Foundation Marketing Support

### ISSUE THREAD

**Issue by RRomoff** [openjs-foundation/summit#300]
### Proposal

**Topic of the session**
Resources available to projects as it relates to marketing and communicating about your milestones.

**Type of the session**

- [* ] Collaborate
- [ ] Workshop
- [ ] Talk

**Timezone of facilitator**
Central time

- Put me where I fit. 

**Estimated duration of the session**
30- 45 mins

**Follow-up / Set-up sessions (if any)**

**Level**

- [* ] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

**Describe the session**
In this session, Rachel from the OpenJS Foundation will talk through marketing opportunities for projects wanting 1. Support in this area 2. Guidance in marcom strategy. This is also an opportunity to learn more about what offerings are available and the best ways to take advantage.

**Session facilitator(s), Github handle(s) and timezone(s)**
Rachel Romoff (@rromoff) Central Time

**Additional context (optional)**

----

### This section is for contributors handling Collaborator Summit logistics

**Track**

- [ ] New Contributor Orientation Track (see #251)
- [ ] Regular Track
- [x] Cross-Project Track

**Triage**

- [x] Track chosen
- [ ] Scheduled

**Comment by jorydotcom** [comment]
@RRomoff doesn't look like we took any notes from this session; do you recall if it was recorded?

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
