### ISSUE TITLE
In-person Collaborator Summit in Austin 2022

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/summit#307]
Hey Folks,

I hope to see you all in Austin next year.  I was wondering if we should _slowly_ start planning for this to happen.

(hoping that travel bans would be lifted by then).

**Comment by benjamingr** [comment]
> Specifically, until all children can be vaccinated,

Children are being vaccinated here - hopefully by 2022 that is also the case in other areas of the world.

On the other hand - it looks like the vaccine has a ±6 months deadline (both due to new strains and just time) and we're already getting the third shot.

**Comment by ljharb** [comment]
@benjamingr what age group? In the US it’s only 12+ so far, and the next group will be 5-12, so my kids still won’t be eligible.

**Comment by WaleedAshraf** [comment]
We have started planning for it. Check [#collabsummit-planning](https://openjs-foundation.slack.com/archives/C035X3296QZ) channel in OpenJS slack.

**Comment by WaleedAshraf** [comment]
@mcollina I'll close this in favor of https://github.com/openjs-foundation/summit/issues/310.
Feel free to re-open if needed. :)
