### ISSUE TITLE
Session Proposal: Introduction to new collaborators

### ISSUE THREAD

**Issue by ghost** [openjs-foundation/summit#308]
### Proposal

**Introduction to new collaborators**

The idea behind the proposed session is to gather new collaborators and motivate them to collab with the OpenJS community, showcasing experiences, special community moments, hows-to, etc. I personally think this kind of meeting would lead to a continuous growth of interest for collab to the opensource community in general.

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

- EST UTC - 5

**2 hours sesion**

**New collaborators**

- [ x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Comment by WaleedAshraf** [comment]
Closing this issue as no further action is needed.
