### ISSUE TITLE
Collaborator Summit 2022 - June 9, 10 - Austin

### ISSUE THREAD

**Issue by WaleedAshraf** [openjs-foundation/summit#310]
The Austin 2022 Collab Summit is coming.

## Event Details
**Location:** JW MARRIOTT AUSTIN, TEXAS
**Main Event Page:** https://events.linuxfoundation.org/openjs-world/
**Collab Summit Page:** https://events.linuxfoundation.org/openjs-world/features/add-on-programming/#day-0-training-sessions
**Dates:**
- Thursday, June 9 (9:00 am – 5:00 pm CDT)
- Friday, June 10 (9:00 am – 12:00 pm CDT)

## Schedule
https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

### Attending OpenJS World + Collab Summit In-person
You can [sign-up for Collab Summit](https://events.linuxfoundation.org/openjs-world/features/add-on-programming/#day-0-training-sessions) when [registering for OpenJS World](https://events.linuxfoundation.org/openjs-world/)

### Attending only Collab Summit In-person
If you are not attending OpenJS World 2022, and just want to register for Collab Summit In-Person, register here:
https://cvent.me/M2mG4a

### Attending only Collab Summit Remotely
If you are only attending Collab Summit remotely, then you don't need to register. You can join the sessions through meeting links shared by the session facilitator.

## Cost
**In-person attendance:** $15 (includes access for both days)
**Remote attendance:** Free

We also have travel funds for the participants of OpenJS projects to cover their travel expenses. See [the documentation on travel funds](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/project-resources/MEMBER_TRAVEL_FUND.md) for details.

## Slack
- OpenJS Foundation Slack: https://slack-invite.openjsf.org/
- #collabsummit channel: https://openjs-foundation.slack.com/archives/CPE10404W

## Virtual Meeting Links
We have created a pool of Zoom meeting links to host sessions virtually for remote attendees. These Zoom meeting links will be open for everyone, and Session Facilitator should join as the first person and claim the meeting host. All the meetings will be recorded in the LinuxFoundation Zoom account in the cloud and will be shared later on. Session Facilitator should end the meeting after each session so that we have separate recordings for each session. Note that we have limited meeting links, so they will be shared among all sessions. We'll make sure that sessions happening at the same time are using different meeting links.
Please reach out to [waleedashraf](https://openjs-foundation.slack.com/archives/DQQK5BFHN) in OpenJS Slack for the Zoom meeting link.

## See also
- [Collab Summit Welcome Guide](https://github.com/openjs-foundation/summit/tree/main/2022-06-09-Austin#welcome-to-the-openjs-collaborator-summit)
- [Session Facilitator Guide](https://github.com/openjs-foundation/summit/blob/main/SESSION_FACILITATOR_GUIDE.md#-session-facilitator-guide)

cc @jorydotcom @christian-bromann

**Comment by tniessen** [comment]
Have there been any discussions about moving OpenJS World to a different location, similar to what [AWS has done in a short time frame](https://twitter.com/QuinnyPig/status/1504994276345724928)? It's probably way too late to realistically talk about that at this point, I am just wondering if this has been discussed.

**Comment by ljharb** [comment]
AWS isn’t a non-profit; i suspect the finances of that would be untenable for OpenJS unless someone offered to bear the financial burden.

**Comment by tniessen** [comment]
I think the infeasibility of relocating this year's event does not remove the possibility of related discussions, which is what I was asking about. The same discussion could be relevant for planning future events.

**Comment by ljharb** [comment]
https://twitter.com/openjsf/status/1504210050117681156 may be relevant - specifically,
> Our events in Texas this year were contracted in 2019 & 2020. Unable to hold them then due to the pandemic, they were postponed to June and October of 2022.
> Beyond the events already contracted to take place this year, we will not host future events in Texas or other locations where anti-equality efforts are underway

**Comment by benjamingr** [comment]
I'm not sure what's wrong with having an event in Texas (not really that well versed in US politics) but a summit in Europe would help the non-US folk with little kids attend.

I'd love to attend Austin physically but since I am a primary caretaker of my baby and he is still small (1yr) i can't realistically take the 7 days it'd take me to travel to and attend the conference (I tried!).

**Comment by mhdawson** [comment]
In terms of the collaborator summit itself, if I remember correctly, we used to have 2 summits a year. One in N/A lined up with the conference and 1 in Europe. I'd be +1 on us trying to plan a second one in Europe later in the year.

**Comment by Qard** [comment]
Perhaps we should add a @nodejs/diagnostics session to the schedule?

**Comment by WaleedAshraf** [comment]
Closing the issue as the event has passed.
