### ISSUE TITLE
Session Proposal: Node.js - Next-10 

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/summit#315]
### Proposal

We'd like this session to be in the common Node.js section (the common track were we have all collaborators)

Next-10 update and progress.  The next-10 effort has defined the technical-values, and technical-priorities and has been
working on deep dives in each of the technical priorities. Come learn out progress so far and how to get involved.  It's critical
to the future success of the Node.js project.

**Topic of the session**

Next-10 update and progress. Planning for the next 10 years of Node.js

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [X] Talk

**Estimated duration of the session**

20 mins

**Level**

- [X] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

**Describe the session**

The next 10 team will give an update on progress so far and how collaborators can get involved. It's important to make
sure as many collaborators are aware of the effort and get involved.

**Session facilitator(s), Github handle(s) and timezone(s)**

Michael Dawson, @mhdawson, EDT (will be at conference in Austin)

**Meeting notes and Virtual Meeting Link**

Will be added once accepted/scheduled

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by WaleedAshraf** [comment]
Hi,

I have created an initial draft for time schedule. Let me know if you are Ok with it. We can try to have the least amount of collapse with other sessions (though we can't avoid all). Feel free to share your suggestion/preference.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by mhdawson** [comment]
Looks reasonable to me.

**Comment by WaleedAshraf** [comment]
Closing the issue as the event has passed. We haven't received the recordings from OpenJS Foundation. If we do in the future, I'll share the links here.
