### ISSUE TITLE
Session Proposal: Node.js - Next 10 - Deep dives ESM and Observability

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/summit#316]
### Proposal

**Topic of the session**

Session space for Node.js collaborators - Next 10 - Deep dives ESM and Observability

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

3 hours

**Level**

- [ ] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

**Describe the session**

Working session to do a deep dive on ESM and Observably. Key questions we will work through for
each include:
  * Is the state of our ESM/Observability mplementations good enough to ensure future success or are there things
    the project should be doing to improve them
   * If the answer to 1) is that significant improvements are needed, document specific things that we should
     do to improve the current state.

**Session facilitator(s), Github handle(s) and timezone(s)**

Michael Dawson, @mhdawson, ET (Will be in Austin for conference)

**Meeting notes and Virtual Meeting Link**

Will be added if accepted/scheduled

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by WaleedAshraf** [comment]
Hi,

I have created an initial draft for time schedule. Let me know if you are Ok with it. We can try to have the least amount of collapse with other sessions (though we can't avoid all). Feel free to share your suggestion/preference.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by GeoffreyBooth** [comment]
Spoiler alert:

> Is the state of our ESM/Observability implementations good enough to ensure future success or are there things
the project should be doing to improve them

Observability still needs work. I don’t know of any instrumentation vendors who support Node ESM yet (?) and for the most part this is due to loaders being incomplete.

> If the answer to 1) is that significant improvements are needed, document specific things that we should
do to improve the current state.

Most of the loaders roadmap items apply to this: https://github.com/nodejs/loaders#status

See also https://github.com/nodejs/loaders/blob/main/doc/use-cases.md

**Comment by mhdawson** [comment]
Link to doc for minutes - https://docs.google.com/document/d/1hvujpuWgxiVfWNOQpoWXtGTavL2QamYFLuK-n3IrtbI/edit

**Comment by mhdawson** [comment]
Will add links to PRs for minutes before closing. Hope to do that this week.

**Comment by mhdawson** [comment]
PR for minutes, please review and help if there are omissions, additional key points etc. - https://github.com/nodejs/next-10/blob/7e644201503d80429ce504aae5ab49da38f13460/meetings/summit-jun-2022.md

**Comment by GeoffreyBooth** [comment]
Is there some central place to put these large roadmap items, like improving ESM VM support, finishing loaders, etc.? I’ve been adding stuff to the [loaders roadmap](https://github.com/nodejs/loaders#status) but that’s only for loaders; do we have anything similar for the project as a whole?

Likewise, it would be good to document some of the decisions that were made, like that we want to add first-class support for import maps. I can always open an issue like “Support import maps” that sits open until it’s done, or is there a better way?
