### ISSUE TITLE
Session Proposal: Node.js HTTP-next (undici)

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/summit#317]
### Proposal

**Topic of the session**

In this session we are going to discuss the status of [undici](https://undici.nodejs.org), its `fetch` implementation and try to assemble a specific roadmap for integrating it in core / exiting experimental.

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1 hour max

**Level**

- [ ] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

* Familiarity with undici
* Familiarity with Node.js
* Familiarity with streams

**Describe the session**

**Session facilitator(s), Github handle(s) and timezone(s)**

Matteo Collina (@mcollina) -  I'll on site.

**Meeting notes and Virtual Meeting Link**

TBD

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by Ethan-Arrowood** [comment]
I will be on site and am happy to facilitate if you need me to. Will 100% participate of course 😄

**Comment by mcollina** [comment]
It would be great if you could facilitate a session on fetch() spec status.

**Comment by Ethan-Arrowood** [comment]
done deal - that'll be great content for my talk too and then the session can be a deeper dive 

should that be apart of this session or should I make a new one focussed specifically on fetch?

**Comment by WaleedAshraf** [comment]
Hi,

I have created an initial draft for time schedule. Let me know if you are Ok with it. We can try to have the least amount of collapse with other sessions (though we can't avoid all). Feel free to share your suggestion/preference.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by WaleedAshraf** [comment]
Closing the issue as the event has passed. We haven't received the recordings from OpenJS Foundation. If we do in the future, I'll share the links here.
