### ISSUE TITLE
Session Proposal: Fastify v4 launch and Q&A

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/summit#318]
### Proposal

**Topic of the session**

In this session we would like to talk about the Fastify v4 launch, gather feedback and do Q&A.

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

1 hour max (can do 30 minutes)

**Level**

- [x] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Familiarity with [Fastify](https://www.fastify.io).

**Describe the session**

TBD

**Session facilitator(s), Github handle(s) and timezone(s)**

Matteo Collina (@mcollina) - in-person

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by mcollina** [comment]
cc @jsumners

**Comment by jsumners** [comment]
I'm on board if I can make it there.

**Comment by WaleedAshraf** [comment]
Hi,

I have created an initial draft for time schedule. Let me know if you are Ok with it. We can try to have the least amount of collapse with other sessions (though we can't avoid all). Feel free to share your suggestion/preference.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by jsumners** [comment]
> I'm on board if I can make it there.

I cannot attend in person. If a session happens, it is possible that I could attend via Zoom.

**Comment by eduardoroliveira** [comment]
The zoom is not working

**Comment by WaleedAshraf** [comment]
Closing the issue as the event has passed. We haven't received the recordings from OpenJS Foundation. If we do in the future, I'll share the links here.
