### ISSUE TITLE
Session Proposal: Future of Node.js & TypeScript

### ISSUE THREAD

**Issue by Ethan-Arrowood** [openjs-foundation/summit#319]
### Proposal

**Topic of the session**

TypeScript!

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

TBD

**Level**

- [ ] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

TypeScript

**Describe the session**

There are a couple of larger topics we want to discuss such as:
- Future of node type files `@types/node`
  - can we start including types directly with node distribution?
  - should types continue to live in Definitely Typed? 
- Automatic typescript support: `node script.ts` 
  - Executing TypeScript files without the use of tools such as `ts-node`
  - Easy solution could be to just vendor `ts-node` since its the pretty much "standard" way to execute ts files without a build step

**Session facilitator(s), Github handle(s) and timezone(s)**

@Ethan-Arrowood

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by Ethan-Arrowood** [comment]
For example: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/59286#discussioncomment-2361939

When issues with the types are found, and a long list of folks are mentioned by the bot, it goes completely ignored. There are pros and cons to keeping our types in `@types/node` - this session should be sure to provide examples of both

**Comment by benjamingr** [comment]
It'd be awesome to implement the type annotations proposal experimentally in node core on top of something like swc for Node https://github.com/tc39/proposal-type-annotations

**Comment by ljharb** [comment]
That seems exceedingly premature when it’s still in stage 1 and likely to either stall or change drastically; but it’d be interesting as a project outside of core!

**Comment by benjamingr** [comment]
> That seems exceedingly premature when it’s still in stage 1 and likely to either stall or change drastically; but it’d be interesting as a project outside of core!

We've added (and removed) command line flags for very early features in the past and I think the sort of feedback the project would get would be very valuable. I am not suggesting anything that isn't strictly "experimental, may break don't rely on this" and if the proposal changes/stalls it can be moved to a third-party tool.

**Comment by ljharb** [comment]
@benjamingr sure, but this is language syntax - wouldn't v8 would have to support it anyways?

**Comment by mhdawson** [comment]
> When issues with the types are found, and a long list of folks are mentioned by the bot, it goes completely ignored. There are pros and cons to keeping our types in @types/node - this session should be sure to provide examples of both.

In advance it might be good to reach out to people at DT to see if the Node.js project collaborators could become "approvers"  for @types/node.

**Comment by ljharb** [comment]
That's easy - you just have to make a PR and add the github usernames you want, and I'm sure they'll approve it.

**Comment by mhdawson** [comment]
@ljharb good to hear, what I thought was important was to see if the project could "own" getting things approved without having to move out of DT.  Not advocating one way or the other right now, just understanding our options.  In terms of ongoing management of the list do you think we'd be able to sync the Node.js collaborators into the list who can approve? (ie when somebody becomes a Node.js collaborator they also gain the ability to approve DT PRs related to Node.js?)

**Comment by ljharb** [comment]
@mhdawson the users listed as owners in a DT package can land changes without TS team intervention - except for "important packages" tho, which would surely include node. However, they're pretty responsive to those.

I'm not sure how automateable keeping that list in sync would be, but doing it manually is certainly feasible.

**Comment by mhdawson** [comment]
@ljharb I think the discussion was about the types for node.js itself not other packages so a bit confused by your answer. I thought the complaint was that approvals for changes to the Types for Node.js itself streched out.

**Comment by ljharb** [comment]
Yes, I know - `@types/node` is an npm package.

**Comment by mhdawson** [comment]
It was this comment that confused me ` except for "important packages" tho, which would surely include node. However, they're pretty responsive to those.`

**Comment by ljharb** [comment]
Sorry for the confusion :-) i meant that `@types/node` is an important package.

**Comment by WaleedAshraf** [comment]
@Ethan-Arrowood How much would you need for this session? Ideal guess?

**Comment by Ethan-Arrowood** [comment]
Assuming you are asking about time, I'd say whatever the default is. People have _opinions_ about this, but I imagine if we come in with some structured questions/talking points we can keep to the normal time limit.

**Comment by WaleedAshraf** [comment]
Sorry for the typo. @Ethan-Arrowood 
There is no default time. Minimum is 30min slot, max is you can run for 2 days. I suggest having some time limit defined. That will help attendees who are interested in this + other sessions.

**Comment by WaleedAshraf** [comment]
Hi,

I have created an initial draft for time schedule. Let me know if you are Ok with it. We can try to have the least amount of collapse with other sessions (though we can't avoid all). Feel free to share your suggestion/preference.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by Ethan-Arrowood** [comment]
Yes 30 minutes should be fine. Thank you!

**Comment by WaleedAshraf** [comment]
Closing the issue as the event has passed. We haven't received the recordings from OpenJS Foundation. If we do in the future, I'll share the links here.
