### ISSUE TITLE
Session Proposal: NativeScript v8 usage/understanding Q&A

### ISSUE THREAD

**Issue by NathanWalker** [openjs-foundation/summit#322]
### Proposal

**Topic of the session**

Discuss how NativeScript uses v8 to enable platform API usage to flourish within the JavaScript ecosystem.

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

1 hour or less.

**Level**

- [ ] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

Familiarity with the JavaScript language and beneficial to have some prior understanding of [v8](https://v8.dev/).

**Describe the session**

We will discuss how NativeScript utilizes the v8 engine for iOS and Android platform development.

In particular, we will highlight the metadata generator and how it's approach could be used to enable rich platform development (even beyond mobile).

**Session facilitator(s), Github handle(s) and timezone(s)**

Nathan Walker, @NathanWalker, in-person
Eduardo Speroni, @edusperoni, in-person
Igor Randjelovic, @rigor789, virtual

**Meeting notes and Virtual Meeting Link**

https://zoom.us/j/99212567614

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

**Comment by WaleedAshraf** [comment]
Hi,

I have created an initial draft for time schedule. Let me know if you are Ok with it. We can try to have the least amount of collapse with other sessions (though we can't avoid all). Feel free to share your suggestion/preference.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by WaleedAshraf** [comment]
Closing the issue as the event has passed. We haven't received the recordings from OpenJS Foundation. If we do in the future, I'll share the links here.
