### ISSUE TITLE
Session Proposal: Future of `npm` cli roundtable

### ISSUE THREAD

**Issue by ruyadorno** [openjs-foundation/summit#324]
### Proposal

**Topic of the session**

Open discussion on the future of package management and `npm`'s place within it. Bring your best ideas and suggestions!

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

TBD (~ 1h)

**Date and Time of the session**

TBD / Open for discussion

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

- Experienced in Node.js/JavaScript
- Familiarity w/ the package management & build tooling ecosystem
- Desire to help improving the ecosystem
- Bring your best ideas and suggestions!

**Describe the session**

`npm` is a bundled dependency of Node.js & provides some powerful tools to create, install & manage your own project's dependencies; This session is a great opportunity for folks to bring their ideas and suggestions to the ecosystem.

**Session facilitator(s), Github handle(s) and timezone(s)**

Darcy Clarke (@darcyclarke) - ([Session Guide](https://github.com/openjs-foundation/summit/blob/master/SESSION_FACILITATOR_GUIDE.md))

- Note: would prefer a session timeslot on Thursday if possible

**Comment by WaleedAshraf** [comment]
Hi,

I have created an initial draft for time schedule. Let me know if you are Ok with it. We can try to have the least amount of collapse with other sessions (though we can't avoid all). Feel free to share your suggestion/preference.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by mhdawson** [comment]
I think a lot of people from the Node.js project may be interested in this one as well. I see there is still times where there are no Node.js sessions on day 2, if possible it might be good to schedule this session in one of those slots.

**Comment by WaleedAshraf** [comment]
Moved this one to the end of day 2. Let me know if it works.

**Comment by mhdawson** [comment]
+1 from me but we should hear from @ruyadorno who proposed it.

**Comment by ruyadorno** [comment]
that works for me 😊 thanks @WaleedAshraf

**Comment by MylesBorins** [comment]
hey @WaleedAshraf. It seems like a few of the npm folks may not be around that late in the day on Friday, we had initially requested a preference for Thursday... would it be possible to move the session?

Maybe to 11:00 - 12:00 on thursday? I notice that would conflict with the Node.js & Typescript content, but perhaps we could swap? Especially if @ethan-arrowood is ok with it. Would help our team a bunch!

**Comment by Ethan-Arrowood** [comment]
Happy to shift, I won't be around late Friday afternoon myself. If we can't find a new time for the TypeScript one I'm sure someone else can facilitate in place of me

**Comment by MylesBorins** [comment]
FWIW the future of npm session would be 11-12 on Friday if that is early enough for you

**Comment by ljharb** [comment]
Unfortunately being on Thursday might conflict with TC39, so if so, unless TC39 ends early, i wouldn’t be able to make it :-/

**Comment by WaleedAshraf** [comment]
@MylesBorins What if we move the tooling group day 2, 1 hour forward? Can you check with @joesepi if he's fine with it?
And then keep npm session as first on day 2.

**Comment by joesepi** [comment]
@WaleedAshraf I'm confused as to what is being asked. It looks like currently the Tooling session on day 2 is 2 hours long from 9-11am. Are you asking if we would move it to 8-10am? If so, that might be too early for some folks. :)

Please confirm what you are asking for and I can look into any movement. /cc @MylesBorins

**Comment by WaleedAshraf** [comment]
@joesepi I meant to make the second session from 10 - 12.
That will give the npm session the first hour (9 - 10)

**Comment by WaleedAshraf** [comment]
I have talked with Joe and we moved the Tooling Group Day 2 session. Please see the updated schedule.
Now there is a slot free on day 2, from 0900 - 1000

We have two options,
1. npm cli session can take this slot (9 -10, day 2)
 
 OR
 
2. I can move Typescript session to this slot (9:30 - 10, day 2)
 and move npm session to (11 - 12, day 1)
 
 It's up to @MylesBorins and @Ethan-Arrowood to decide.

**Comment by Ethan-Arrowood** [comment]
If it helps the npm session, do option 2. That early slot will work for me; I'll be leaving midday Friday for my flight home

**Comment by WaleedAshraf** [comment]
Thanks, Ethan.

I have updated the schedule as per option 2. 🎉 
https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0

**Comment by darcyclarke** [comment]
Closing as this session & the conference have now passed.

**Comment by MylesBorins** [comment]
If we can keep npm on day 1 that would be preferable
