### ISSUE TITLE
Session Proposal: Node.js Tooling group summit Pt 2

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/summit#326]
### Proposal

**Node.js Tooling group summit Pt 2**

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

2hrs

**Date and Time of the session**

Would prefer Thursday to accommodate key contributor involvement

**Level**

- [x] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

- Knowledge of Node.js/JavaScript is good
- Experience with building or maintaining Node.js based tooling is good (CLI implementations, for example)
- familiarity with past and current work could be helpful: https://github.com/nodejs/tooling (review issues/PRs)

**Describe the session**

What do we want to do next? (Include discussion of the scope of the work of this group)

**Session facilitator(s), Github handle(s) and timezone(s)**

* @joesepi, @darcyclarke, @ruyadorno, Ian Sutherland, Ben Coe

**Meeting notes and Virtual Meeting Link**

TBD

**Follow-up / Set-up sessions (if any)**

The Tooling meeting meets every other week. https://github.com/nodejs/tooling

**Comment by WaleedAshraf** [comment]
Hi,

I have created an initial draft for time schedule. Let me know if you are Ok with it. We can try to have the least amount of collapse with other sessions (though we can't avoid all). Feel free to share your suggestion/preference.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by joesepi** [comment]
CONFIRMED

Summit issues:
https://github.com/openjs-foundation/summit/issues/325
https://github.com/openjs-foundation/summit/issues/326

Tooling issue:
https://github.com/nodejs/tooling/issues/140

Collab Summit schedule doc:
https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0

Virtual details:
https://docs.google.com/spreadsheets/d/1rdROZMUuBWFpobbgCuCT8r6h9V5G4shqWt9pLGI3Clg/edit?usp=sharing

**Comment by darcyclarke** [comment]
Closing as this session & the conference have now passed.
