### ISSUE TITLE
Open Visualization Collaborator Summit 2022 - Sept 22, 23 - Madrid

### ISSUE THREAD

**Issue by chrisgervang** [openjs-foundation/summit#328]
The first Open Visualization Collaborator Summit is coming soon!

## Event Details

**Location:** [CARTO’s office](https://goo.gl/maps/snSz2yae7v4LyHmd6) in Madrid.
**Dates:**
- Thursday, September 22nd (9:30 am - 5:30 pm GMT+2)
- Friday, September 23rd (9:00 am - 1:30 pm GMT+2)

## Schedule

This is a great opportunity to get together and be productive. Use the time to talk about important project topics, pair with each other, resolve bugs, build consensus, or tinker on new ideas. It's also a great time to collaborate with peers from other projects and learn more about what they are doing and how the OpenJS Foundation can support your work.

[Schedule](https://docs.google.com/spreadsheets/d/1jSON771slyxp2PyM3u9qxgkdoB13QvS8ZQR2MnPcZDw/edit#gid=0)

## Registration

This is an open event, but is geared towards contributors of the deck.gl framework, as well as other frameworks in the vis.gl and kepler.gl OpenJS projects. Please apply to register here as space is limited:
[Register Here](https://forms.gle/GnLb8oZb78HTCod46)

We'll try to record the talks and workshops, and upload them to our [youtube channel](https://www.youtube.com/channel/UCaIkUubXmTNFn8V8eM7jQUQ).

## Cost

This is an in-person event in Madrid, Spain. There is no registration fee.

We also have travel funds for the participants of OpenJS projects to cover their travel expenses. See [the documentation on travel funds](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/project-resources/MEMBER_TRAVEL_FUND.md) for details.

## Slack
- OpenJS Foundation Slack: https://slack-invite.openjsf.org/
- #open-visualization channel: https://openjs-foundation.slack.com/archives/C03JT1N6NS1

## Important for all participants ☝
We want everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion or lack thereof, to feel welcome and safe and collaborate with each other in a harassment free environment. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks. Summit participants violating these rules may be sanctioned or expelled.

## Code of Conduct
The [Linux Foundation Events Code of Conduct](https://events.linuxfoundation.org/about/code-of-conduct/) applies to all event spaces.

**Comment by alasarr** [comment]
@chrisgervang thanks a lot for setting this up 💪 . You can check the first version of the schedule [here](https://docs.google.com/spreadsheets/d/1jSON771slyxp2PyM3u9qxgkdoB13QvS8ZQR2MnPcZDw/edit?usp=sharing). We've great speakers! During the following days, I'll complete the title of each section as soon as the speakers will provide me with that info

**Comment by rginn** [comment]
Hi! Please register for this awesome, free event here: https://www.eventbrite.com/e/openjs-foundation-open-visualization-collaborator-summit-tickets-410567808367

**Comment by im28** [comment]
What an awesome event! really looking forward to attending online, where will the event be streamed to? on [this youtube channel](https://www.youtube.com/channel/UCaIkUubXmTNFn8V8eM7jQUQ)?

**Comment by im28** [comment]
@kylebarron, Yeah I got it, Thank you!

**Comment by WaleedAshraf** [comment]
@chrisgervang I think this can be closed now as the event has passed.

**Comment by alasarr** [comment]
yes!

**Comment by WaleedAshraf** [comment]
I'll close the issue. Feel free to reopen if needed. :)
