### ISSUE TITLE
Session Proposal: Diagnostics WG Mini-Summit

### ISSUE THREAD

**Issue by Qard** [openjs-foundation/summit#330]
### Proposal

A bunch of Diagnostics working group members will be at the summit. We should talk diagnostics tools. 🔧 

**Topic of the session**

See: https://github.com/nodejs/diagnostics/issues/583

So far eBPF and llnode look like big topics.

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

TDB

**Date and Time of the session**

TBD

**Level**

I'd like to keep this relatively friendly for newbies, though the diagnostics tools category does tend to have a bit of domain knowledge involved.

- [ ] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

Awareness of debuggers, profilers, tracing, etc. Anything related to application performance and diagnostics.

**Describe the session**

Discussion about the current state of diagnostics tools in Node.js and what the roadmap should be for future diagnostics tools work.

**Session facilitator(s), Github handle(s) and timezone(s)**

Stephen Belanger (@qard) - PST

(If anyone else wants to volunteer, let me know!)

**Meeting notes and Virtual Meeting Link**

----

**Comment by WaleedAshraf** [comment]
I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by WaleedAshraf** [comment]
Here are the recordings.
- Main room - Day 1 - Before lunch - [Recording](https://zoom.us/rec/share/lWy6zZ0BoF0RoL_U2W89rhXTSv_vZ2VHisSaNS5jK6BBPqw_RATzw2AAJsIYnCOg.8p4j2lvdYDleN36a?startTime=1664610301000)
- Main room - Day 1 - After lunch - [Recording](https://zoom.us/rec/share/1LRHpZO3VCiHj_Rxo6H9zrNLHEmlz078qVV1RM04D-xS4_0p93stwmYgCJh2DYvX.fqwHsW3fkxyiRAgc?startTime=1664626292000)
- Main room - Day 2 - Before lunch - [Recording](https://zoom.us/rec/share/qMdX1GbYYZSKe-OENy1z50u0GFYx48cRZbu3nisDDbEw0iw5BTwLfJfeJaI0i4pa.nz-AH4JGQNeoK99X?startTime=1664698603000)

I've also added the recording links in the [schedule sheet](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0). Sorry, we couldn't record the sessions in the second room. Hopefully next time we'll prepare better.

I'll close this issue as the event has passed. Thanks, everyone for being part of it and for the support.
