### ISSUE TITLE
Session Proposal: Node.js: Next-10 - Technical Priority Review

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/summit#333]
### Proposal

**Topic of the session**

The project maintains a list of Technical Priorities in - https://github.com/nodejs/node/blob/main/doc/contributing/technical-priorities.md which we need to update/revalidate on a periodic basis.  This session will include:

* Brainstorm of what people believe current technical priorities should be using easy retro style collaboration
* Review/discussion of brainstorm output against the current priorities 
* Documentation of next steps on how to update the technical priorities

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

2 hours

**Date and Time of the session**

**Level**

- [ ] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

View/thoughts on what you believe is important to the future sucess of Node.js

**Describe the session**

* Brainstorm of what people believe current technical priorities should be using easy retro style collaboration
* Review/discussion of brainstorm output against the current priorities 
* Documentation of next steps on how to update the technical priorities

**Session facilitator(s), Github handle(s) and timezone(s)**

Jean Burellier (in person) - @sheplu
Ruy Adorno (in person) - @ruyadorno
Michael Dawson (in person) - @mhdawson

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

https://github.com/nodejs/node/blob/main/doc/contributing/technical-priorities.md
From initial priority discussion:
https://user-images.githubusercontent.com/4048656/106966137-95bccb80-66f9-11eb-860c-cd6fe7d82790.png

----

**Comment by WaleedAshraf** [comment]
I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by mhdawson** [comment]
This is the agenda we put together in the next-10 meeting today

# Agenda

* Technical prioriites brainstorm - 
  * Board for thjis year - https://easyretro.io/publicboard/J7hq238p2gSasf0xP3zuGfGU4Jr2/7133f400-4af1-4133-8f5f-7b4f5adf2283
  * Last year results - https://easyretro.io/publicboard/cLBIBu3wA2Um7qIziXq1zmC4gdi1/1db5ea23-fee3-4da0-bb7b-a5ea49d810e7?sort=votes

* Community brainstorm 
  * Board for brainstorm - https://easyretro.io/publicboard/J7hq238p2gSasf0xP3zuGfGU4Jr2/6dfc326f-a253-4268-b320-6cda3f4e300c
  * Last year results - https://user-images.githubusercontent.com/4048656/106966137-95bccb80-66f9-11eb-860c-cd6fe7d82790.png

* Enabling the project
  * Communication/sharing of priorities with collaborators
  * Helping people feeling empowed to pick up/run with priorities

* Review of technical priorities against the existing list - https://github.com/nodejs/node/blob/main/doc/contributing/technical-priorities.md

* Have constituencies/needs changed ?
  * https://github.com/nodejs/next-10/blob/main/CONSTITUENCIES.md
  * https://github.com/nodejs/next-10/blob/main/CONSTITUENCY-NEEDS.md

* Next Steps

**Comment by WaleedAshraf** [comment]
<img width="1779" alt="Screenshot 2022-10-01 at 11 01 09" src="https://user-images.githubusercontent.com/8335457/193404108-be5d1d0c-2be6-4020-b78d-5956fb2cb2bc.png">

**Comment by WaleedAshraf** [comment]
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/8335457/193413188-1fe74e07-b385-443e-b2cb-1793817a1963.png">

**Comment by WaleedAshraf** [comment]
Here are the recordings.
- Main room - Day 1 - Before lunch - [Recording](https://zoom.us/rec/share/lWy6zZ0BoF0RoL_U2W89rhXTSv_vZ2VHisSaNS5jK6BBPqw_RATzw2AAJsIYnCOg.8p4j2lvdYDleN36a?startTime=1664610301000)
- Main room - Day 1 - After lunch - [Recording](https://zoom.us/rec/share/1LRHpZO3VCiHj_Rxo6H9zrNLHEmlz078qVV1RM04D-xS4_0p93stwmYgCJh2DYvX.fqwHsW3fkxyiRAgc?startTime=1664626292000)
- Main room - Day 2 - Before lunch - [Recording](https://zoom.us/rec/share/qMdX1GbYYZSKe-OENy1z50u0GFYx48cRZbu3nisDDbEw0iw5BTwLfJfeJaI0i4pa.nz-AH4JGQNeoK99X?startTime=1664698603000)

I've also added the recording links in the [schedule sheet](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0). Sorry, we couldn't record the sessions in the second room. Hopefully next time we'll prepare better.

I'll close this issue as the event has passed. Thanks, everyone for being part of it and for the support.
