### ISSUE TITLE
Session Proposal: Node.js: SEA team Mini-summit

### ISSUE THREAD

**Issue by jviotti** [openjs-foundation/summit#334]
### Proposal
**Topic of the session**

A session on the current state and future of Node.js SEAs.

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

2 hours

**Date and Time of the session**

TBD

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Familiarity with the problem of creating single-executable packaged Node.js applications. If you don't have a lot of context on the problem space, you can read through many of the discussions and documents in https://github.com/nodejs/single-executable. 

We have a comprehensive introduction to the problem here: https://github.com/nodejs/single-executable/blob/main/blog/2022-08-05-an-overview-of-the-current-state.md.

**Describe the session**

Go over the current state, attempt to make conceptual progress and draft out a more concrete plan for SEAs.

**Session facilitator(s), Github handle(s) and timezone(s)**

Juan Cruz Viotti (@jviotti) - GMT (in-person)
Claudio Wunder (@ovflowd) - CEST (in-person)
Tierney Cyren (@bnb) - GMT-4 (????)
Darshan Sen (@RaisinTen) - IST (joining virtually)

**Meeting notes and Virtual Meeting Link**

TBD

**Additional context (optional)**

@jviotti (me) will attempt to carry the session from Dublin, remote otherwise.

**Comment by RaisinTen** [comment]
Could you also add me to the "Session facilitator(s), Github handle(s) and timezone(s)" section? I'd love to help out!

**Comment by jviotti** [comment]
Done!

**Comment by WaleedAshraf** [comment]
I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by jviotti** [comment]
Thanks! I can also confirm my in-person attendance.

**Comment by RaisinTen** [comment]
@overflowd expressed interest in participating in-person in https://github.com/nodejs/single-executable/issues/32#issuecomment-1245199960. @jviotti could you add him to the session facilitators list also?

**Comment by jviotti** [comment]
I think you meant [ovflowd](https://github.com/ovflowd) :P

**Comment by RaisinTen** [comment]
@jviotti I spoke to @bnb on twitter and he said that he too would be happy to help as a facilitator. Let's add him!

**Comment by bnb** [comment]
in-person :)

**Comment by WaleedAshraf** [comment]
Here are the recordings.
- Main room - Day 1 - Before lunch - [Recording](https://zoom.us/rec/share/lWy6zZ0BoF0RoL_U2W89rhXTSv_vZ2VHisSaNS5jK6BBPqw_RATzw2AAJsIYnCOg.8p4j2lvdYDleN36a?startTime=1664610301000)
- Main room - Day 1 - After lunch - [Recording](https://zoom.us/rec/share/1LRHpZO3VCiHj_Rxo6H9zrNLHEmlz078qVV1RM04D-xS4_0p93stwmYgCJh2DYvX.fqwHsW3fkxyiRAgc?startTime=1664626292000)
- Main room - Day 2 - Before lunch - [Recording](https://zoom.us/rec/share/qMdX1GbYYZSKe-OENy1z50u0GFYx48cRZbu3nisDDbEw0iw5BTwLfJfeJaI0i4pa.nz-AH4JGQNeoK99X?startTime=1664698603000)

I've also added the recording links in the [schedule sheet](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0). Sorry, we couldn't record the sessions in the second room. Hopefully next time we'll prepare better.

I'll close this issue as the event has passed. Thanks, everyone for being part of it and for the support.
