### ISSUE TITLE
Session Proposal: Recreating a JavaScript runtime from Scratch - Understand the magic behind the Node.js Core

### ISSUE THREAD

**Issue by ErickWendel** [openjs-foundation/summit#335]
### Proposal

**Topic of the session**
Recreating a JavaScript runtime from Scratch - Understand the magic behind the Node.js Core

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

35 minutes / Open for discussion

**Date and Time of the session**

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Experienced JavaScript and Node.js knowledge

**Describe the session**

Bun, Deno, and many other JavaScript runtimes have been hype, but do you know why? Is it that easy to make a runtime from scratch? 

I've been researching the secret behind Node.js' power and why there are so many new JavaScript runtimes coming up. Breaking down each key component used on Node.js I've come to interesting conclusions that many people used to say whereas in practice it works a bit differently.

In this talk, attendees will learn the concepts used to create a new JavaScript runtime. They're going to go through an example of how to make a JavaScript runtime by following what's behind the scenes on the Node.js project using C++. They'll learn the relationship between Chrome's V8 and Libuv and what makes one JavaScript runtime better than others.

**Session facilitator(s), Github handle(s) and timezone(s)**
Erick Wendel (@ErickWendel)

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by WaleedAshraf** [comment]
I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by ErickWendel** [comment]
> I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.
> 
> https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

Hey! This means that the proposal was accepted, right?

**Comment by ErickWendel** [comment]
Hey, I thought through and I changed my mind. I think this talk fits more for a meetup/conference (and I'm not sure if I'll be able to finish this in time).

Thank you! See you at the Collab Summit o/
