### ISSUE TITLE
Session Proposal: Node.js: Next-10 - Documentation

### ISSUE THREAD

**Issue by sheplu** [openjs-foundation/summit#336]
### Proposal

**Topic of the session**

The documentation was a priority during the next-10 discussion. We already talked a bit about how we can improve it linked to the type system. 
Another discussion would be around the current state of the documentation, how we can improve it and in which part.
Idea of the current discussion: Current state of the documentation, user friendly / newcomer, search function, real life example and i18n

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

2 hours

**Date and Time of the session**

**Level**

- [ ] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Knowing the documentation of Node.js
Experience using documentation from others technologies
View / thoughts on the current state and how it could be improved

**Describe the session**

- Gather thought on the current state of the documentation
- Difficulties using it ? How can we improve
- Examples: How can we present some real use case
- API documentation : current state of the documentation, how can we add some examples, more information, search ...
- User documentation: easier way for newcomer to use the documentation
- should we work on i18n for the documentation ? 
- Next steps to be decided

**Session facilitator(s), Github handle(s) and timezone(s)**

- Jean Burellier (in-person) - @sheplu
- Ruy Adorno (in person) - @ruyadorno
- Michael Dawson (in person) - @mhdawson
- Claudio Wunder  (in-person) - @ovflowd

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

Initial discussion with @ovflowd  https://github.com/nodejs/next-10/issues/153
Another topic about examples: https://github.com/nodejs/next-10/issues/154

**Comment by sheplu** [comment]
@ovflowd : I added you on the facilitator as we discussed about it - and I saw that you are coming in person. If not I can remove you

@mhdawson & @ruyadorno : added you too as we discussed about that during the last next-10

**Comment by mhdawson** [comment]
@sheplu I think you should update the title from Session Proposal: <Project Name> <Session Title>

**Comment by ovflowd** [comment]
Thanks, @sheplu!

**Comment by WaleedAshraf** [comment]
I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by sheplu** [comment]
Thanks @WaleedAshraf 

To not split the this session would it be possible to give the 11.00-11.30 slot to the Next-10 Technical Priorities while the Next-10 Documentation is held the afternoon (on the slot you already put)

It can also be put on the next day morning on the 2nd track (if possible) to arrange more people

Do you know in which session you will be @ovflowd @mhdawson @ruyadorno ?

**Comment by ovflowd** [comment]
For now I know I'll be attending Next-10 and I wish to attend this one too.

**Comment by WaleedAshraf** [comment]
@sheplu Yes, it's possible. The reason I put it all in one track is that we are expecting 20/30 in-person attendees. We have seen that keeping everyone in one room is better for discussion vs splitting.
My idea was that Next-10 Tech Prio and Docs will discuss the most important topics in one room. With everyone. And then after lunch, you can continue the discussion in the 2nd room (least priority topics).

I'm happy to make any changes you like. Let's see what @mhdawson thinks and we can update it.

**Comment by mhdawson** [comment]
Like always I want to be in `alll the sessions`. I think our best best is to see what we cover/or not in the initial session and then plan for a breakout in the second room as needed.

**Comment by WaleedAshraf** [comment]
Here are the recordings.
- Main room - Day 1 - Before lunch - [Recording](https://zoom.us/rec/share/lWy6zZ0BoF0RoL_U2W89rhXTSv_vZ2VHisSaNS5jK6BBPqw_RATzw2AAJsIYnCOg.8p4j2lvdYDleN36a?startTime=1664610301000)
- Main room - Day 1 - After lunch - [Recording](https://zoom.us/rec/share/1LRHpZO3VCiHj_Rxo6H9zrNLHEmlz078qVV1RM04D-xS4_0p93stwmYgCJh2DYvX.fqwHsW3fkxyiRAgc?startTime=1664626292000)
- Main room - Day 2 - Before lunch - [Recording](https://zoom.us/rec/share/qMdX1GbYYZSKe-OENy1z50u0GFYx48cRZbu3nisDDbEw0iw5BTwLfJfeJaI0i4pa.nz-AH4JGQNeoK99X?startTime=1664698603000)

I've also added the recording links in the [schedule sheet](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0). Sorry, we couldn't record the sessions in the second room. Hopefully next time we'll prepare better.

I'll close this issue as the event has passed. Thanks, everyone for being part of it and for the support.
