### ISSUE TITLE
Session Proposal: Community Health Analytics Discussion

### ISSUE THREAD

**Issue by No9** [openjs-foundation/summit#338]
### Proposal

**Topic of the session**

Following on from the [CHAOSS](https://chaoss.community/) sessions during the Open Source Summit EU this year there has been a substantial growth in Open Source Community management tooling that enables communities to monitor the vitality of project. 
This session seeks to start the conversation to see if this work is useful to the nodejs project.
- Provide some background on the CHAOSS community
- Walk through the [node.js stats](https://cauldron.io/project/6810?from_date=2021-09-13&to_date=2022-09-13&tab=performance-overview&repo_url=https://github.com/nodejs/node)
- Discuss implication of the numbers and possible actions

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**
30 mins 

**Date and Time of the session**

**Level**
- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**
Interest in community management

**Describe the session**
- Provide some background on the CHAOSS community
- Walk through the [node.js stats](https://cauldron.io/project/6810?from_date=2021-09-13&to_date=2022-09-13&tab=performance-overview&repo_url=https://github.com/nodejs/node)
- Discuss implication of the numbers and possible actions
- Is there value in creating stats for key modules?

**Session facilitator(s), Github handle(s) and timezone(s)**
Anton Whalley (In Person) @no9 

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

Open Source Community Health Project https://chaoss.community/ 

----

**Comment by No9** [comment]
@BethGriggs If you are coming to the summit can I put you in as a session facilitator given all the work you've done in this area?

**Comment by kayleachampion** [comment]
I had a chance to meet @No9 via OSS EU and I'm eager to partner with Node folks as they consider embarking on this journey :). My research is focused on working with communities to detect, measure, and mitigate risk in software components. Node has a lot of advantages in terms of the quality of data you have to work with compared to some other environments. 

Here's background on the [previous phase of a project I did to measure risk in Debian](https://blog.communitydata.science/detecting-at-risk-software-infrastructure/) and [this is the presentation I did at OSS EU](https://youtu.be/jF3TGN_FGMk) to begin to track down sources of risk. I'd be happy to help in whatever ways make sense.

**Comment by WaleedAshraf** [comment]
I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by WaleedAshraf** [comment]
Here are the recordings.
- Main room - Day 1 - Before lunch - [Recording](https://zoom.us/rec/share/lWy6zZ0BoF0RoL_U2W89rhXTSv_vZ2VHisSaNS5jK6BBPqw_RATzw2AAJsIYnCOg.8p4j2lvdYDleN36a?startTime=1664610301000)
- Main room - Day 1 - After lunch - [Recording](https://zoom.us/rec/share/1LRHpZO3VCiHj_Rxo6H9zrNLHEmlz078qVV1RM04D-xS4_0p93stwmYgCJh2DYvX.fqwHsW3fkxyiRAgc?startTime=1664626292000)
- Main room - Day 2 - Before lunch - [Recording](https://zoom.us/rec/share/qMdX1GbYYZSKe-OENy1z50u0GFYx48cRZbu3nisDDbEw0iw5BTwLfJfeJaI0i4pa.nz-AH4JGQNeoK99X?startTime=1664698603000)

I've also added the recording links in the [schedule sheet](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0). Sorry, we couldn't record the sessions in the second room. Hopefully next time we'll prepare better.

I'll close this issue as the event has passed. Thanks, everyone for being part of it and for the support.
