### ISSUE TITLE
Session Proposal: Security WG Mini-Summit

### ISSUE THREAD

**Issue by RafaelGSS** [openjs-foundation/summit#339]
### Proposal

**Topic of the session**

We're going to present what's happening in the Security WG. The idea is to provide a big picture of the current initiatives, thus, creating a brainstorming session to plan future steps for the Node.js Ecosystem.

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [X] Talk

**Estimated duration of the session**

TBD

**Date and Time of the session**

TBD

**Level**

- [X] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

In order to discuss the Permission System implementation, would be great to have some awareness of the Node.js codebase. However, the session after the presentation (brainstorming) doesn't require any prior experience. Any thought is valid.

**Describe the session**

The roadmap should be pretty similar to the following list:
  * Quick overview of the Security WG
  * Node.js Vuln Assessment workflow
  * Threat Model initiative
  * Node.js Security Best Practices document
  * Permission System
  * Brainstorming

**Session facilitator(s), Github handle(s) and timezone(s)**

Rafael Gonzaga (@rafaelgss) - GMT-3

**Comment by WaleedAshraf** [comment]
I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by WaleedAshraf** [comment]
Here are the recordings.
- Main room - Day 1 - Before lunch - [Recording](https://zoom.us/rec/share/lWy6zZ0BoF0RoL_U2W89rhXTSv_vZ2VHisSaNS5jK6BBPqw_RATzw2AAJsIYnCOg.8p4j2lvdYDleN36a?startTime=1664610301000)
- Main room - Day 1 - After lunch - [Recording](https://zoom.us/rec/share/1LRHpZO3VCiHj_Rxo6H9zrNLHEmlz078qVV1RM04D-xS4_0p93stwmYgCJh2DYvX.fqwHsW3fkxyiRAgc?startTime=1664626292000)
- Main room - Day 2 - Before lunch - [Recording](https://zoom.us/rec/share/qMdX1GbYYZSKe-OENy1z50u0GFYx48cRZbu3nisDDbEw0iw5BTwLfJfeJaI0i4pa.nz-AH4JGQNeoK99X?startTime=1664698603000)

I've also added the recording links in the [schedule sheet](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0). Sorry, we couldn't record the sessions in the second room. Hopefully next time we'll prepare better.

I'll close this issue as the event has passed. Thanks, everyone for being part of it and for the support.
