### ISSUE TITLE
Collaborator Summit 2023 - Vancouver, Canada (OpenJS World)

### ISSUE THREAD

**Issue by ovflowd** [openjs-foundation/summit#343]
## Collaborator Summit 2023

**Date:** May 9, 2023
**Venue:** [Open Source Summit Venue - Vancouver Convention Center](https://goo.gl/maps/wNdYptLVVy1aQLSXA)
**Cost:** Free
**Schedule:** [Google Sheet](https://docs.google.com/spreadsheets/d/1ujP4dV8ui8Rn562ksdOjvcDQpC7hWRjDBPGjC10zDMM/edit?usp=sharing)
**Registration:** **To be defined**. Everyone must register.
**Session Proposal:** Please submit your session by opening a [new issue](https://github.com/openjs-foundation/summit/issues/new?assignees=No9%2C+waleedashraf%2C+ovflowd%2C+mcollina&labels=Vancouver+2023%2C+Collaborator+Summit%2C+Session+Proposal&template=summit-topic-proposal.md&title=Session+Proposal%3A+%3CProject+Name%3E+%3CSession+Title%3E)

OpenJS Foundation Slack: https://slack-invite.openjsf.org/
#collabsummit channel: https://openjs-foundation.slack.com/archives/CPE10404W

## See also
- [Collab Summit Welcome Guide](https://github.com/openjs-foundation/summit/tree/main/2022-10-01-Dublin)
- [Session Facilitator Guide](https://github.com/openjs-foundation/summit/blob/main/SESSION_FACILITATOR_GUIDE.md#-session-facilitator-guide)

## Local Transportation

To be defined

## OpenJS World at Open Source Summit

**Date:** May 10 - May 12
**Venue:** [Vancouver Convention Center, Vancouver, Canada](https://goo.gl/maps/wNdYptLVVy1aQLSXA)
**Registration:** https://events.linuxfoundation.org/open-source-summit-north-america/

## Zoom Info
The online event platform, Zoom, will be open to all attendees starting on Tuesday, May 9 at 8:50 AM PST.

Attendees who would like to utilize live captioning in English while watching sessions are encouraged to take advantage of Google Captioning.

See below for the Zoom session links for the event. Enter the event through the direct Zoom link, followed by the code.

[Main Room / Keynotes](https://zoom.us/j/92465376973?pwd=Z1ovQTZETkVoWEZXdEUzNmsyV1NGUT09)
Passcode: 120268
[Breakout Room](https://zoom.us/j/99248042579?pwd=K2RLNmllaUlaVkdpbm42VzlrSHZpdz09)
Passcode: 193091

**Comment by mhdawson** [comment]
@WaleedAshraf I know you have helped organize the sumits in the past. Wondering if you have the cycles/interest to do so again?

**Comment by WaleedAshraf** [comment]
Hi @mhdawson 
I'm not well this year (recovering). So will not be able to get involved this year. @ovflowd can take the lead this year and maybe @christian-bromann can also help.

**Comment by ovflowd** [comment]
Oh no @WaleedAshraf :( whatever you have, I hope you get well soon. I don't mind helping with organising this year.

**Comment by mhdawson** [comment]
@WaleedAshraf sorry to hear you are not feeling well, best wishes in your recovery.

**Comment by mcollina** [comment]
Unfortunately I cannot commit to additional meetings, but I will be there and I can coordinate during the day too.

**Comment by targos** [comment]
I won't be able to come to Vancouver.
Will it be possible to join remotely?
If yes, do I have to register for remote access?

**Comment by mcollina** [comment]
I would not bother frankly.

**Comment by mhdawson** [comment]
I can confirm I'll be there, and happy to help coordinate the day of the summit if additional help is needed.

**Comment by targos** [comment]
Thanks for the clarifications! Btw, the Google Sheet in https://github.com/openjs-foundation/summit/issues/343#issue-1520317958 says "Saturday, Oct 1".

**Comment by ovflowd** [comment]
Gotta update that sheet 😅 

Also, ty, Michael (Dawson), for volunteering! ❤️

**Comment by ovflowd** [comment]
Hey all 👋 a preview (draft) of the schedule is already available [here](https://docs.google.com/spreadsheets/d/1ujP4dV8ui8Rn562ksdOjvcDQpC7hWRjDBPGjC10zDMM)

**Comment by santigimeno** [comment]
I just managed to have my ticket for the conference and I was planning to attend the collab summit but it says is already full. Is there a chance to attend regardless?

**Comment by mcollina** [comment]
Show up. I don't think we won't let a Node collaborator in.

cc @rginn

**Comment by ovflowd** [comment]
As Matteo said, I doubt you would be blocked from entering if you have a conference ticket. + Even if a lot of people "registered" for Collab Summit, I doubt all of these people that registered will come.

And I as the organiser wouldn't block you either, please come!

**Comment by rginn** [comment]
We have space! Please attend. I'm working with the event organizers to update our registration page.

**Comment by ovflowd** [comment]
Hey @marypcbuk, yes. They should be recorded :)

**Comment by sagirk** [comment]
Hi @ovflowd, how to access the recorded sessions?

**Comment by ovflowd** [comment]
Afaik they should be uploaded to YouTube :)

**Comment by sagirk** [comment]
@ovflowd They're not up on YouTube yet (I've checked both channels, OpenJS and Node.js), but I'll keep an eye out.

**Comment by ovflowd** [comment]
@sagirk I didn't say they were, I said they will.

**Comment by ovflowd** [comment]
Hey, all 👋 all the sessions are not available [here on YoutTube](https://www.youtube.com/playlist?list=PLyspMSh4XhLO15jJD9Sj069fN18j12AbQ) and all the photos taken within the Collab Summit are available on [this Flickr album](https://flic.kr/s/aHBqjAC2fo).

Thank you for this beautiful Collaborator Summit. It was a pleasure to collaborate with all of you!
