### ISSUE TITLE
Session Proposal: Node.js | Let's automate Node's dependency updates!

### ISSUE THREAD

**Issue by marco-ippolito** [openjs-foundation/summit#345]
### Proposal

**Topic of the session**

The main topics of the talk are:

- Security: explain why it is important to update dependencies:  supply chain attacks, vulnerabilites, patching.
- Automate dependency update in Node: show how we are migrating from manual to scripts and lately github actions.
- How to automate dependency updates, dependabot, actions etc..

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

Open for discussion but probably ~30m 

**Date and Time of the session**

TBD / Open for discussion

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Not really, just generic knowledge of ci, github actions.

**Describe the session**

I want to focus on how important it is to automate dependency update and spread best practices. I want to inform about security risks of manual dependency updates (or none at all) and I want to show an insight on how we are migrating in node from manual/bash script to automatic.

**Session facilitator(s), Github handle(s) and timezone(s)**

Marco Ippolito @marco-ippolito CEST 

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by ovflowd** [comment]
Hey Marco 👋 thank you for submitting a Collab Summit Session.

This talk sounds like it is targeted at Node.js's end-users and not at contributors and maintainers of Node.js. Even tho if that's not the case, the talk doesn't seem to fit the Collab Summit's model.

I'm afraid we will not be able to proceed with this talk on our agenda.

**Comment by mhdawson** [comment]
@ovflowd This is related to work in the Node.js project.  Node.js includes dependencies and this topic is related to automating how the Node.js projects updates those depdendencies. High level tracking/discussion is in - https://github.com/nodejs/security-wg/issues/828

**Comment by mhdawson** [comment]
re-opening for some additional discussion as my take is that it could be a way to encourage additional people to help out with working through the list that we need to automate and could fit the summit model in that context. @marco-ippolito is that what you had in mind?

**Comment by marco-ippolito** [comment]
Yes I wanted to talk about the work we did in the security working group for the dependency update automation and explain why it is important, and maybe gather more people 😁

**Comment by ovflowd** [comment]
If that's the case, then that's something completely different! You could have explained it to me @marco-ippolito and not simply blindly accepted my closure of the issue 🙈 

Thanks, @mhdawson for noticing this 🙇

**Comment by tniessen** [comment]
@marco-ippolito We usually try to make collab summit sessions not only informative, but also about actionable topics. Is this expected to still be actionable for contributors after the collab summit? Based on the list in https://github.com/nodejs/security-wg/issues/828, it looks like most Node.js dependency updates are automated already, and the remaining ones are either close to being automated (ngtcp2, zlib, googletest, ...) or unlikely to be fully automated in the near future due to the amount of manual work that is usually required (V8).

**Comment by tniessen** [comment]
I assume that sessions that mostly review existing work are still in scope; https://github.com/openjs-foundation/summit/issues/346 and https://github.com/openjs-foundation/summit/issues/355 sound like they are mostly going to go over existing work, too.

**Comment by ovflowd** [comment]
**FYI:** This session got approved and added to our agenda ✅ 🎉
