### ISSUE TITLE
Session Proposal: Node.js - Node.js HTTP parser, what's going on?

### ISSUE THREAD

**Issue by ShogunPanda** [openjs-foundation/summit#350]
### Proposal

**Topic of the session**

Node.js HTTP parser, what's going on?

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

30min + Q/A and or discussion

**Date and Time of the session**

TBD

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Node.js internal HTTP stack knowledge

**Describe the session**

Node.js HTTP relies on llhttp parser, which is a both a semi-obscure piece of code and semi-abandoned project.
As the parser is a critical part of Node.js, do we have better alternatives for easier maintainability? Let's find out.
 

**Session facilitator(s), Github handle(s) and timezone(s)**

Paolo Insogna (@ShogunPanda) - CEST (but will be in Vancouver)

**Meeting notes and Virtual Meeting Link**

TBD

**Follow-up / Set-up sessions (if any)**

TBD

----

**Comment by ovflowd** [comment]
**FYI:** This session got approved and added to our agenda ✅ 🎉
