### ISSUE TITLE
Session Proposal: Keeping the Node.js project healthy for the mext 10 years

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/summit#351]
### Proposal

**Topic of the session**

Discussion on key initiatives for keeping the project healthing led by the Next-10 team including:
* How can we identify, help and build long term contributors
* How can we encourage companies/people to support the project

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

Example: 1 hour

**Date and Time of the session**

TBD

**Level**

- [ ] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

N/A

**Describe the session**

An open discussion on key areas that we should focus on to keep the project healthy.  Two initial ones on the list include building long term collaborators and encouraging companies/people to support the project but the first topic will be to build out the list to be discussed in the second part.

**Session facilitator(s), Github handle(s) and timezone(s)**

Michael Dawson (@mhdawson)
Jean Burellier (@sheplu)

**Meeting notes and Virtual Meeting Link**

Meeting Notes: <ADD YOUR LINK HERE>
Virtual Meeting link: <ADD YOUR LINK HERE>

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

Both fasciliators intend to be at summit in person.

**Comment by ovflowd** [comment]
**FYI:** This session got approved and added to our agenda ✅ 🎉

**Comment by mhdawson** [comment]
Deck for session, including agenda -https://docs.google.com/presentation/d/1nJFk8Zc906Vu8dONGiunpgzhr2W8nR-0oy5eEhjGrMk/edit#slide=id.g20a270fdded_0_109

**Comment by mhdawson** [comment]
pdf version of deck since I can't share the google presentation itself broadly - 
[keeping the project healthy.pdf](https://github.com/openjs-foundation/summit/files/11347490/keeping.the.project.healthy.pdf)
