### ISSUE TITLE
Session Proposal: jQuery, Too Much of a Good Thing?

### ISSUE THREAD

**Issue by codyzu** [openjs-foundation/summit#352]
### Proposal

**Topic of the session**
jQuery, Too Much of a Good Thing?

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**
45 minutes / Open for discussion

**Date and Time of the session**

Open for discussion

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

* familiarity with jQuery
* modern JS web APIs

**Describe the session**

jQuery undeniably powers the web… Today, over 82 million websites use jQuery. jQuery changed the way developers built web applications and played a crucial role in JavaScript’s world domination. This talk reveals some of the startling statistics and analysis of the impact jQuery has on today’s internet and the history of what made this library the powerhouse of the web.

In 2023, new frameworks, such as react, have taken over web development, but jQuery still lives on. Are there security risks? What would a world look like without jQuery? Are there modern alternatives and web standards to this library? What would be the reasons to switch to them and how? Is it possible to have too much of a good thing?

Imagine a future where the world relies less on this fundamental building block and why we might want to work towards that future.

**Session facilitator(s), Github handle(s) and timezone(s)**

Cody Zuschlag (@codyzu) - CEST (Note, I'll be in Vancouver for the summit)

**Meeting notes and Virtual Meeting Link**

TBD

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by ovflowd** [comment]
Hey @codyzu 👋 thank you for submitting a Call for Session. I have a few questions regarding your submission:

- Are more jQuery maintainers/contributors planning to attend to Collab Summit?
- What's the intended collaboration model within this talk? Is it to raise awareness among the other maintainers? Showcase accomplishments?

Just by reading the session description, it doesn't sound much suitable for the Collab Summit model.

Thank you!

**Comment by ljharb** [comment]
This seems more like an Open JS World talk to me, and the CFPs for that closed on February 5th (https://openjsf.org/blog/2022/12/20/openjs-world-2023-is-on-call-for-papers-cfps-now-open/ )

**Comment by ovflowd** [comment]
Agreed. I'm closing this issue for now as I honestly don't think we're going to accept this session, but OP, please feel free to reopen the issue if seem deemed.
