### ISSUE TITLE
Session Proposal: Node.js Technical Priorities for the Next 10 years

### ISSUE THREAD

**Issue by sheplu** [openjs-foundation/summit#354]
### Proposal

**Topic of the session**

Presentation of the current initiatives of the Next-10 and review the previous task done since the last summit. 
A discussion about the current technical priorities and the result of the survey during the month of April

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

2 hours

**Date and Time of the session**

**Level**

- [ ] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Knowing the current technical priorities

**Describe the session**

- Quick overview of the current initiatives
- Discussion about the current technical priorities
- Presentation and review of the feedbacks from the April survey

**Session facilitator(s), Github handle(s) and timezone(s)**

- Jean Burellier (in-person) - @sheplu
- Michael Dawson (in person) - @mhdawson

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

**Comment by ovflowd** [comment]
@sheplu is this different from https://github.com/openjs-foundation/summit/issues/351?

**Comment by ovflowd** [comment]
@sheplu I can't allocate more than 1h and 30 minutes for this session. Do you think that's enough?

**Comment by ovflowd** [comment]
Okay, I was able to allocate 2 hours!

**Comment by ovflowd** [comment]
@mhdawson @sheplu sadly with other sessions being added I had to reduce this session to a grand of 1 hour. But this still gives Next-10 a gran total of 2 hours for all the Next-10 content.

**Comment by ovflowd** [comment]
**FYI:** This session got approved and added to our agenda ✅ 🎉

**Comment by mhdawson** [comment]
@nodejs/collaborators
