### ISSUE TITLE
Session Proposal: Performance Team Review of the work done

### ISSUE THREAD

**Issue by sheplu** [openjs-foundation/summit#355]
### Proposal

**Topic of the session**

Presentation of the current initiatives of the Performance team and review the previous task done since the december. 
Talk about the next step, and specific implementation (ADA)

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1 hours

**Date and Time of the session**

**Level**

- [ ] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Knowing the current technical priorities

**Describe the session**

- Quick overview of the wins
- Discussion about the current initiatives
- ADA / URL parser

**Session facilitator(s), Github handle(s) and timezone(s)**

- Jean Burellier (in-person) - @sheplu
- Yagiz Nizipli (remote) - @anonrig 

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

**Comment by ovflowd** [comment]
**FYI:** This session got approved and added to our agenda ✅ 🎉

**Comment by sheplu** [comment]
@anonrig if you want to add some specific points before the event ?

**Comment by anonrig** [comment]
> @anonrig if you want to add some specific points before the event ?

I can/want to talk about points like:

- [ ] Ada - url parser changes
- [ ] V8 Fast API usages
- [ ] Adding fast paths and how we should look for optimizations
- [ ] Reducing CPP/JS calls and moving certain functions to CPP

**Comment by tniessen** [comment]
In my experience, for the format of a collaborator summit, it is great to discuss actionable initiatives and ideas. I realize that the session title is _review of the work done_, but I believe that next steps and future directions are the most valuable information for collaborators, contributors, and potential contributors :)
