### ISSUE TITLE
Node.js Collaborator Summit 2023 - Bilbao, Spain (OpenJS World EU)

### ISSUE THREAD

**Issue by ovflowd** [openjs-foundation/summit#360]
# Node.js Collaborator Summit 2023

**Date:** September 18, 2023
**Venue:** [Open Source Summit Venue - Euskalduna Conference Center](https://goo.gl/maps/MzdQcXfTxUQSwWuS9)
**Cost:** $15,00 (US Dollars)
**SCHEDULE/AGENDA:** [Google Sheet](https://docs.google.com/spreadsheets/d/1YFVmFzEk7sEA8jFaxcNiXF43_zrsdkn5gbCfrlXti_U/edit?usp=sharing)

### Registration

**If you ARE attending Open Source Summit Europe**, you should first register for the main event (Open Source Summit) and then add "Node.js Collaborator Summit" as an add-on during your registration. **If you already registered** to Open Source Summit, you can update your registration and add the Collaborator Summit add-on (Co-located event).

- Open Source Summit Registration: https://events.linuxfoundation.org/open-source-summit-europe/register/
  - Note that this registration is only for in-person attendees! If you're attending OSSEU remotely, please use the "Virtual Attendee" registration link below.

**If you are NOT attending Open Source Summit Europe** (Only attending the Node.js Collaborator Summit), please register via one of the following links:

- In-Person Attendee: https://cvent.me/kRkreN
- Virtual Attendee: https://cvent.me/e4OqnV

### Connect with us!

**OpenJS Foundation Slack:** https://slack-invite.openjsf.org/
#collabsummit channel: https://openjs-foundation.slack.com/archives/CPE10404W

### Submit a session proposal!

The Collaborator Summit welcomes Node.js contributors and collaborators to submit sessions to this Collaborator Summit [through this link](https://github.com/openjs-foundation/summit/issues/new?assignees=ovflowd%2C+mcollina%2C+ruyadorno&labels=Vancouver+2023%2C+Collaborator+Summit%2C+Session+Proposal&projects=&template=summit-topic-proposal.md&title=Session+Proposal%3A+%3CProject+Name%3E+%3CSession+Title%3E).

Please keep in mind that the format of the Collab Summit is for collaboration, so we highly suggest submitting sessions that include collaboration (Panels, Fire-side chats, Discussions).

One of the goals of the Node.js Collaborator Summit is to enable collaborators to discuss and collaborate on long-term and critical strategic initiatives and topics of the Node.js project.

#### Why a 15 USD fee?

Different from the last Event, this Collab Summit will have independent registration from OpenJS World/Open Source Summit, Meaning that you don't need a ticket for the main event to attend to Collab Summit.

The 15 EUR registration fee is a form to avoid having no-shows, provide the Event SWAG, coffee break, snacks and support the infrastructure for the summit.

#### Why Node.js Collaborator Summit?

We've noticed (after organizing a few Collaborator Summits) that most of the submitted sessions are related to Node.js.

To better the scope of the Summit, we should rebrand it as Node.js Collaborator Summit. More details are available [here](https://github.com/nodejs/TSC/issues/1399).

#### I want to submit a session

This edition will only accept submissions from existing collaborators or contributors around the Node.js space. The topics also need to be related to Node.js, and the format of the submissions needs to intentionally be a panel, fire-side chat, or any discussion format.

We will not be accepting virtual speakers/hosts of sessions, given that the logistics of mixing the collaboration virtually and in-person is complex. You'll still be able to attend virtually, as Zoom links will be provided.

## OpenJS World at Open Source Summit EU

**Date:** September 19 - September 20
**Venue:** [Euskalduna Conference Center](https://goo.gl/maps/MzdQcXfTxUQSwWuS9)
**Registration:** https://events.linuxfoundation.org/open-source-summit-europe/

Note.: You don't need to register for OpenJS World EU to attend the Collab Summit.

## Zoom Info

Attendees who want to utilize live captioning in English while watching sessions are encouraged to use Google Captioning.

Zoom session links will be added to this issue later on.

**Comment by ovflowd** [comment]
I sadly still haven't gotten an ack from the LF, regarding:

- Upload of the sessions during the Summit
- Photo Albums

I'm not sure for how long it is worth to keep this issue open....

**Comment by ovflowd** [comment]
@kyliewd have we gotten yet the pictures of our last Summit? 🤔

**Comment by mcollina** [comment]
Can we close this?

**Comment by ovflowd** [comment]
> Can we close this?

Waiting input from Kylie

**Comment by trivikr** [comment]
I think this can be closed.
