### ISSUE TITLE
Session Proposal: Get GYP Gud

### ISSUE THREAD

**Issue by bnoordhuis** [openjs-foundation/summit#362]
**Abstract**: GYP is dead and we're stuck with the corpse. It's starting to smell. What do we do?

**Format**: Bilbao summit; 15 minute talk, followed by 45 minutes discussion. Talk covers how we got here, previous attempts at moving away, quick overview of alternatives, biggest roadblocks (as I see 'em.)

**Target audience**: everyone who hates the build system as much as I do. I expect a huge turnout.

**Comment by targos** [comment]
Is this about moving away from GYP for native addons, for the Node.js build, or both?

**Comment by bnoordhuis** [comment]
Both, although the outcome may be that we're only going to tackle one.

**Comment by ruyadorno** [comment]
👍 Sold!

**Comment by ovflowd** [comment]
That sounds interesting 👀

**Comment by bnoordhuis** [comment]
I regret that I won't be able to attend due to upcoming surgery of one of my kids. Hopefully next year.
