### ISSUE TITLE
Session Proposal: Security - Next Initiatives

### ISSUE THREAD

**Issue by RafaelGSS** [openjs-foundation/summit#364]
### Proposal

**Topic of the session**

* Next initiatives of the Security WG
* Security discussions of existing features
* Overview of the node.js ecosystem and what can we do it support it more

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

Open for discussion

**Date and Time of the session**

TBD

**Level**

- [X] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Familiarity with current security features, the process of the security wg

**Describe the session**

The idea is to have an open discussion around the current state of the art, what's missing, and what can be improved, and eventually talk about the next initiatives for the working group

**Session facilitator(s), Github handle(s) and timezone(s)**

@RafaelGSS (in person)

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by tniessen** [comment]
Nit: it's not a real WG :)
