### ISSUE TITLE
Call for Sessions for the Open Visualization Collab Summit 2023 in New York City

### ISSUE THREAD

**Issue by chrisgervang** [openjs-foundation/summit#373]
![OpenJS_OpenVisualizerCollaboratorSummit-03](https://github.com/openjs-foundation/summit/assets/2461547/010e1ae1-cd89-4578-869c-74a73b3aed25)

Hey, y'all 👋 I would like to formally announce that we're opening our Call for Session Proposals for this year's [Open Visualization Collab Summit](https://www.eventbrite.com/e/2023-open-visualization-collaborator-summit-tickets-641499340797).

**Submitting a new Session is available through [here](https://github.com/openjs-foundation/summit/issues/new/choose), and the discussion of this year's summit is happening [here](https://github.com/visgl/deck.gl/discussions/7928).**

The OpenJS Foundation and Foursquare will host the 2023 Open Visualization Collaborator Summit on September 6-7 in Foursquare's New York City office. You must register to attend the Summit and be able to attend in-person in New York City. Snacks and refreshments will be provided.

For this year's summit, **we invite contributors and applications in the vis.gl / deck.gl / kepler.gl visualization ecosystem to take part in submitting sessions** with topics varying from interactive workshops, informational talks, and panel discussions. The venue will provide equipment such as microphones and projectors.

Unfortunately, we will not be able to provide a live stream, however a recording will be available after the event.

We're asking for all submissions before August 17th.

If you're in doubt about submitting a session proposal, please feel free to reach the OpenVis members at openvizsummit@openjs.org, as we would love to hear your thoughts.

Thank you so much and we hope to see you in person for our Collaborator Summit!

**Comment by mcollina** [comment]
Can we close this?
