### ISSUE TITLE
Session Proposal: Node.js Package Maintenance WG 2023

### ISSUE THREAD

**Issue by darcyclarke** [openjs-foundation/summit#374]
### Proposal

This session is intended to [share status updates on the work](https://github.com/nodejs/package-maintenance/projects/1) of the [Node.js Package Maintenance WG](https://github.com/nodejs/package-maintenance/) as well as discuss priority issues related to support & sustainability efforts of the broader ecosystem. 

**Topic of the session**

- **~15min** Presentation
  - Introduction to the Working Group & it's Charter
  - [Highlight "Help Wanted" Issues & Opportunities](https://github.com/nodejs/package-maintenance/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
  - Initiative 1: [`package.json` creation/linting/formatting/validation via `@pkgjs/create`](https://github.com/nodejs/package-maintenance/issues/458) Updates & Next Steps
  - Initiative 2: [ESM/CJS Support Documentation](https://github.com/nodejs/package-maintenance/issues/542) Updates & Next Steps
  - Initiative 3: [Impactful Projects Statusboard](https://github.com/nodejs/package-maintenance/issues/569) Updates & Next Steps
- **~45min** Freeform Q&A, Discussions, Collaboration & determing Next Steps

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

- **1 hour**

**Date and Time of the session**

- TBD

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

See the ["Package Maintenance WG Goals" Section](https://github.com/nodejs/package-maintenance/#goals)

**Describe the session**

This is a somewhat free-form collaborative session where we'll try to both share updates on projects in-flight as well as determine next-steps for the various initiatives we have. Successful outcomes from this session will be increased activity/interest of WG projects as well as broader insight into our activities & renewed interest in creating tooling, guidelines & on/off-ramps to support the ecosystem.

**Session facilitator(s), Github handle(s) and timezone(s)**

- @darcyclarke (in-person)
- @mhdawson (in-person)
- @wesleytodd (in-person)
- @ruyadorno (virtually ET)
- @rxmarbles (virtually, PT)
- @Ethan-Arrowood (virtually, MT)

**Meeting notes and Virtual Meeting Link**

- Meeting Notes: TBD
- Virtual Meeting link: https://zoom.us/j/431077278 
(this is the Nodes.js Package Maintenance WG Zoom Link - a meeting will go live during this session)

**Follow-up / Set-up sessions (if any)**

- Recurring Meetings: https://github.com/nodejs/package-maintenance/#meetings

----

**Comment by Ethan-Arrowood** [comment]
Mark me as virtual 💻

**Comment by wesleytodd** [comment]
I will be in-person! Excited to see everyone!

**Comment by Ethan-Arrowood** [comment]
Even though it's probably the exact same people, can we also include the new Package Metadata Interoperability Collab Space in this session? Would love to discuss package.json research 😄

**Comment by ljharb** [comment]
What is the exact date/time of this meeting, so I can try to attend virtually?

**Comment by mhdawson** [comment]
Schedule is here - https://docs.google.com/spreadsheets/d/1YFVmFzEk7sEA8jFaxcNiXF43_zrsdkn5gbCfrlXti_U/edit#gid=0

**Comment by ovflowd** [comment]
Note that virtual attendee's will only be able to collaborate on the 2nd room if any of the people participating the session has a device to do an online call, such as Google Meet.

The main room only supports seeing the content as a virtual attendee.

**Comment by mhdawson** [comment]
As per @ovflowd support for interactive virtual attendee's will depend on a volunteer starting/streaming a meeting for each session. I suggest we ask for such a volunteer for each session and if they start a zoom/google meet, etc. post the link the issue for the session.

**Comment by mhdawson** [comment]
Google meet @Ethan-Arrowood if you want to join  - https://meet.google.com/azo-ahwv-sir
