### ISSUE TITLE
Session Proposal: Node.js Website Team Mini-Summit

### ISSUE THREAD

**Issue by ovflowd** [openjs-foundation/summit#378]
### Proposal

**Topic of the session**

This session is divided into two parts. The first one is a short talk of 15-20 minutes explaining the significant milestones the Website Team achieved in this last year (2022-2023). The second part is a more extended collaboration session (open to the community) about the following priorities of the Website Team, Greet & Meet and debate some of the technical challenges we've had in the past.

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

Talk: 15-20 minutes
Collaborative Session: 45 minutes

**Date and Time of the session**

TBD

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

A little bit of knowledge regarding the Node.js Website Team and/or Project would be recommended, but not needed.

**Describe the session**

The Talk will cover the main challenges and achievements of the Website Team in the last year; Whereas the Collaborative Session aims to be a space for discussion future and past work.

**Session facilitator(s), Github handle(s) and timezone(s)**

@ovflowd

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

A few Website Team members will attend, such as Harkunwar Kochar and Brian Muenzenmeyer

----

**Comment by AugustinMauroy** [comment]
Is it possible to join/participate virtually?

**Comment by ovflowd** [comment]
> Is it possible to join/participate virtually?

Just to watch.
