### ISSUE TITLE
Session Proposal: Node.js - Milo, a new HTTP parser for Node.js

### ISSUE THREAD

**Issue by ShogunPanda** [openjs-foundation/summit#379]
### Proposal

**Topic of the session**

Milo, a new HTTP parser for Node.js

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

30 - 60 min

**Date and Time of the session**

Open for discussion

**Level**

- [ ] Beginner
- [ ] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

Node.js HTTP source code (both JS and C++ layer). Not strictly required but preferrable.

**Describe the session**

Last January I announced I was working on a new HTTP parser for Node.js which can replace llhttp (which is hard to maintain).
The moment has come and I'd like to introduce to you `milo`, a Rust based, no dependencies, statically linked HTTP parser.

**Meeting notes and Virtual Meeting Link**

None

**Follow-up / Set-up sessions (if any)**

None

**Additional context (optional)**

None

**Comment by ovflowd** [comment]
@ShogunPanda you forgot to update the title of this Issue 👀

**Comment by ShogunPanda** [comment]
@ovflowd 🤦‍♂️ Thanks for noticing my friend. Fixed :)
