### ISSUE TITLE
Open Visualization Session Proposal: Open Source with AWS Geospatial

### ISSUE THREAD

**Issue by hy9be** [openjs-foundation/summit#381]
### Proposal

**Topic of the session**
Support open-source geospatial communities at AWS

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [X] Talk

**Estimated duration of the session**

30 minutes

**Date and Time of the session**
First option: Day 1 3:30pm EST. Open for discussion.

**Level**

- [X] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

N/A

**Describe the session**

Introduce how AWS Geospatial support and contribute to projects like MapLibre, Overture Maps, and plan for supporting vis.gl.

**Session facilitator(s), Github handle(s) and timezone(s)**

Haowen You, @hy9be, EST

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by chrisgervang** [comment]
Hey @hy9be, apologies for the radio silence! We have open slots on Day 2 for a presentation, but if it needs to be Day 1 at 3:30 we may be able to move a panel we had scheduled for that time. If you're still available to give a talk we'd happily accept.

**Comment by chrisgervang** [comment]
2pm EST on Day 2 is open. I reached out on LinkedIn to coordinate. Hope we can make something work!

**Comment by mcollina** [comment]
Can we close this?
