### ISSUE TITLE
Open Visualization Session Proposal: Beautiful 3D Tiles Rendering Regardless of Tileset Source

### ISSUE THREAD

**Issue by justinmanley** [openjs-foundation/summit#382]
### Topic of the session

Beautiful 3D Tiles Rendering Regardless of Tileset Source

### Type of the session

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

### Estimated duration of the session

30 minute talk + Q&A

### Date and Time of the session

1-2pm on September 7, if that timeslot is still available

### Level

- [ ] Beginner
- [x] Intermediate
- [x] Advanced

### Pre-requisite knowledge

People with prior experience with 3D tiles or a similar format (e.g. I3S) will get the most out of this session.

### Describe the session

One of the formats loaders.gl supports is Cesium's [3D tiles specification](https://github.com/CesiumGS/3d-tiles) (loaders.gl includes both a 3D tiles [renderer](https://github.com/visgl/loaders.gl/tree/684dd0d51599a4bd2f5264713f7a810a35a2e513/modules/3d-tiles) and [indexer](https://github.com/visgl/loaders.gl/tree/master/cpp/Model3DTiler)). Ideally, any renderer should be able to beautifully render any spec-conforming tileset, regardless of who produced the tileset -- that's the whole point of using an open specification! However, in practice, tileset rendering quality can vary depending on how the tileset was produced.

_Geometric error_ is a key concept in the 3D tiles specification. This is a number associated with each tile which renderers use to determine the set of tiles to display at each viewpoint. Unfortunately, the spec is vague about how exactly indexers should compute geometric error. Even for a single data type (pointclouds or meshes) there are multiple valid ways of computing geometric error.

Based on @sensat's experience migrating from rendering pointclouds using potree to rendering both pointclouds and meshes using 3d tiles (using the loaders.gl 3d-tiles renderer), this talk offers tips and tricks for harmonizing geometric error across 3d-tiles renderers and indexers to make pointclouds and meshes look great.

### Session facilitator(s), Github handle(s) and timezone(s)

@justinmanley, @Kaapp in-person at collaborator summit in NYC

**Comment by chrisgervang** [comment]
Hey @justinmanley, just confirming we've got your talk scheduled for 2:30EST on Day 2. Looking forward to seeing you next week!

**Comment by justinmanley** [comment]
fantastic - we're looking forward as well!

**Comment by chrisgervang** [comment]
Could you please confirm name, picture, and talk title for our event page?

We're staging it at https://pessimistress.github.io/deck.gl/events/new-york-summit-2023/index.html

**Comment by justinmanley** [comment]
sure!

Title: The question everyone’s asking about 3d tiles
Speakers: Justin Manley and Chris Kapp

Justin Manley (me!):

![justin](https://github.com/openjs-foundation/summit/assets/1668487/efebd413-abf9-475f-90ce-979dff13be26)

Chris Kapp (@Kaapp):

![chris kapp](https://github.com/openjs-foundation/summit/assets/1668487/fdc41076-eeb4-451a-8134-c60a1e0ae8c7)

**Comment by mcollina** [comment]
Can we close this?
