### ISSUE TITLE
Session Proposal: we need to make the CI green again

### ISSUE THREAD

**Issue by joyeecheung** [openjs-foundation/summit#383]
### Proposal

We need to fix the reliability of the Node.js CI (mostly https://ci.nodejs.org/job/node-test-pull-request/, we can cover others if we have time)

**Topic of the session**

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1h

**Date and Time of the session**

Sep 18, 15:15 CET.

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

How to write/run Node.js core tests and launch CI.

**Describe the session**

20-30min walkthrough about the status of the CI. The rest would be discussions about how we can fix this, or we will just have a hackathon to fix the outstanding flakes.

Will try to make remote participation possible. If Zoom does not work, we will use a slack room to communicate. (It's mostly about having a time to direct people's attention to the CI, whether we can communicate using our vocal cords is less important)

**Session facilitator(s), Github handle(s) and timezone(s)**

@joyeecheung 

**Meeting notes and Virtual Meeting Link**

https://meet.google.com/qgy-owbp-zmo

Use the `#nodejs-ci-flakes` channel on slack for async communication.

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by joyeecheung** [comment]
@ovflowd @ruyadorno Is it possible to let people participate via Zoom? It would not be quite useful if only people in the room can participate.

**Comment by ovflowd** [comment]
Sorry @joyeecheung this time we're not prepared for having virtual attendance.

People can still watch it remotely, but remote participation is kinda impossible.

If this was requested beforehands we probably could have arranged it.

cc @bensternthal

**Comment by joyeecheung** [comment]
OK if Zoom does not work we could also just use a slack room or something.

**Comment by tniessen** [comment]
We've had these kinds of sessions before (in a less formal manner) and it usually resulted in a few tests getting fixed by collaborators, so this sounds great!

**Comment by joyeecheung** [comment]
Oh yeah good old memory https://twitter.com/addaleax/status/1002279690445484033

**Comment by ovflowd** [comment]
> OK if Zoom does not work we could also just use a slack room or something.

That's not the issue. The Summit uses infrastructure provided by the event. At least on the main room. So there's no real way of adjusting these settings there.

Now, during the collaboration room, that's another story. Feel free to setup your computer or else, and do a call if you will.

**Comment by marco-ippolito** [comment]
I think we can keep informal, just like any wg meeting 🙂 I will be at the Collab Summit and happy to help

**Comment by joyeecheung** [comment]
Is the main room going to be like a conference hall or something? I don't think we need that, just a regular meeting room is enough. (technically we could do just it over a dinner table...)

**Comment by ovflowd** [comment]
@joyeecheung I've updated the agenda, lmk if the format I've chosen works for you :)

**Comment by joyeecheung** [comment]
I have some slides here https://docs.google.com/presentation/d/134HwI-2mf0V-ghuyXjfBCnwz0KYB9xIbalXOmjnJi7s/edit though I am not sure how important the talk part is. It's just CI 101.

**Comment by joyeecheung** [comment]
Created a link at google meet https://meet.google.com/qgy-owbp-zmo (it's only usable for 60 minutes, if this somehow takes longer, we need to create a new one).

**Comment by joyeecheung** [comment]
Notes/next steps: https://hackmd.io/upAw5aWcQb66ZRMx4tQDrA
