### ISSUE TITLE
Node.js Collaborator Summit 2024 / London

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/summit#387]
# Node.js Collaboration Summit 2024 / London

**Date:** April 3-4, 2024
**Venue:** Bloomberg London, 3 Queen Victoria Street, London EC4N 4TQ, United Kingdom 
**Cost:** 0.
**Agenda:** https://docs.google.com/spreadsheets/d/1-4hm3OQ4HGfvOdFR-5pm9fHz6O2k-wbqpK-41fcS1Yw/edit?usp=sharing

---

### Registration

Since we are borrowing a space in an office building, for security reasons, in-person attendance is reserved to collaborators or people who can find a collaborator to vouch for them. 

EDIT: registration for in-person attendance has closed on Mar 29.

If you are attending CityJS London, there's a 30% discount code available upon request. (Ask @mcollina). The Summit registration is unrelated to the registration of CityJS. **The location of the summit is different from where CityJS London is**. CityJS London Registration: https://london.cityjsconf.org/buytickets

### Attending in person

[The Linux Foundation Events Code of Conduct](https://events.linuxfoundation.org/about/code-of-conduct/) applies to all event spaces.

1. The Bloomberg London office is above the Walbrook exit of the Bank Underground Station ([Google Map](https://maps.app.goo.gl/eNgQ4GwYiTMKcTbL8)), entrance is at the intersection between Queen Victoria Street and Bucklersbury street  ([Street view of entrace](https://www.google.com/maps/@51.5129613,-0.0903739,3a,68y,234.12h,86.01t/data=!3m6!1e1!3m4!1sYwgFbOg6kWonzOaoCA2gxg!2e0!7i16384!8i8192?entry=ttu)).
1. For security reasons, at the reception of the office building, attendees will be asked to show an ID and take a photo. The information is limited to the host's security system and won't be shared externally. To make the check-in process easier, please use the name on your ID when filling the registration form. If you feel uncomfortable about sharing your legal name via the form, please let us know and we can arrange something at the reception.
1. We plan to have a camera capturing the room for the Zoom call. According to local regulations, we need to collect the consent from those who appear on camera and get recorded. This applies especially to session facilitators.
1. We won't be able to provide an all-masked environment, so it's not mandatory to wear a mask, but it's also totally fine to wear one during the event.
1. We plan to improve hybrid attendance this time. The host will provide A/V setup for us and we plan to bring backup equipment as well. There will be one (or more) microphone. People in the room should join the Zoom call and mute themselves. Those who wish to speak during the sessions should raise their hands using Zoom first and wait for their turn, so that remote participants can join the queue virtually and we can have a productive hybrid discussion. In the room we'll pass the microphone to the person who is in turn to speak.
1. Breakfast and lunch are sponsored by Bloomberg on both days. We will have catering in the room. We have a dinner table reserved on Wednesday, check out the slack channel for details.
1. Since we are using a space in an office building, attendees should stay in the area where the summit happens. If you want to walk out of the area, please ask one of the Bloomberg employees on the spot or a security personnel to accompany you.
1. The summit starts at 9:00 with a breakfast,  sessions start at 9:30 and ends at 17:00 each day. After the summit we should leave the building by 18:00.

### Attending remotely

If you want to speak in the sessions, you can get an invitation as panelist beforehand. Ask @joyeecheung (either an email or ping Joyee Cheung on the OpenJS slack with your email to receive a link).

To only attend the sessions remotely (not sure if you are speaking), register using the following links. A link will be sent to your email for actually joining the webinar. You'll also receive email notifications if there are updates to the Zoom setup. As regular attendees you'll need to be promoted to panelist to speak. Ask in the [#collab-summit-london-2024 Slack channel](https://openjs-foundation.slack.com/archives/C06S8MG9DU6) or say something in the Q&A.

Day1: https://zoom.us/webinar/register/WN_l1ywqf1jTaO-ZSVnoXchGg#/registration
Day2: https://zoom.us/webinar/register/WN_3FJCCjgiRseMunHFhb8NoA#/registration

1. Remote attendance is open to everyone.
1. <del>Please check out the session proposals in this issue tracker and leave comments about your timing preference.</del> Agenda is settled. 
1. We won't be streaming the summit due to complexities from local regulations (same reason why we need camera appearance consent for those attending in person). We plan to release recordings after the summit.
1. Remote participants can use Zoom to raise their hands to be in the same queue with those in the room to speak.
1. This is the first time we make a serious attempt at hyprid attendance (in past summits remote participation was usually non-existent or did not work well). We'll get some help from Bloomberg folks (who had experience hosting TC39 hybrid meeting) and try to make it work this time, but please, lower your expectations :)

### Links for notes:

Day 1 notes: https://hackmd.io/erevKHb6RVihtWpdPgFWCw?edit
Day2 notes: https://hackmd.io/poOBiqFiTBeCIlfOv5HwUQ?edit

### Submit a session proposal!

[Open an issue](https://github.com/openjs-foundation/summit/issues/new?assignees=ovflowd%2C+mcollina&labels=London+2024%2C+Collaborator+Summit%2C+Session+Proposal&projects=&template=summit-topic-proposal.md&title=Session+Proposal%3A+%3CProject+Name%3E+%3CSession+Title%3E) to submit a session proposal.

Please keep in mind that the format of the Collab Summit is for collaboration, so we highly suggest submitting sessions that include collaboration (Panels, Fire-side chats, Discussions).

One of the goals of the Node.js Collaborator Summit is to enable collaborators to discuss and collaborate on long-term and critical strategic initiatives and topics of the Node.js project.

### If you have questions

- **OpenJS Foundation Slack:** https://slack-invite.openjsf.org/
- **#collab-summit-london-2024 channel:** https://openjs-foundation.slack.com/archives/C06S8MG9DU6
#### Is there any registration fee?

No! This year's attendance will not require any pre-payment.

#### Will there be remote attendance?

Yes. We will be allowing remote attendance through Zoom, but we won't be livestreaming.

#### I want to submit a session

This edition will only accept submissions from existing collaborators or contributors around the Node.js space. The topics also need to be related to Node.js, and the format of the submissions needs to intentionally be a panel, fire-side chat, or any discussion format.

We are going to try and accept sessions from virtual facilitators this time. For hybrid attendance to work, everybody must raise their hands first and wait for their turn to speak.

**Comment by joyeecheung** [comment]
I've already sent an email about this to those who answered that they need travel fund support in the attendance poll, but just in case anyone is missing out all other channels but watch this issue: please submit your travel fund request before Feb 27 by following https://github.com/openjs-foundation/cross-project-council/blob/main/community-fund/COMMUNITY_FUND_POLICY.md#how-to-apply (more background in https://github.com/openjs-foundation/cross-project-council/issues/1254#issuecomment-1955240234)

**Comment by littledan** [comment]
Bloomberg is excited to host the upcoming Node Collaboration Summit in London, April 3-4. You can sign up here: https://go.bloomberg.com/attend/invite/join-bloomberg-and-the-openjs-foundation-for-the-node-js-collaborator-summit/

**Comment by rluvaton** [comment]
Should we update the README with the new upcoming event instead of Bilbao?

**Comment by joyeecheung** [comment]
Updated agenda and attendance information (including Zoom registration links) in the OP.

**Comment by joyeecheung** [comment]
Should we close the issues now?

**Comment by joyeecheung** [comment]
Links to the recordings:

- Day 1 morning: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712132193000
- Day 1 afternoon: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712148446000
- Day 2 morning: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712218676000
- Day 2 afternoon: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712234786000

Links to the notes (very inaccurate, we should try harder at getting dedicated note takers the next time):

- Day 1: https://hackmd.io/erevKHb6RVihtWpdPgFWCw
- Day 2: https://hackmd.io/poOBiqFiTBeCIlfOv5HwUQ

Drafted trip report, would appreciate some reviews. Expect to publish on the official blog next week: https://hackmd.io/5vvP8o5bTmqcbNh-3oHpag
