### ISSUE TITLE
Session Proposal: Node.js Tooling Group meeting

### ISSUE THREAD

**Issue by ruyadorno** [openjs-foundation/summit#390]
### Proposal

**Topic of the session**

Node.js Tooling Group Collaboration Session

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1 hour (maybe more?)

**Date and Time of the session**

TBD

**Level**

- [X] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

- Experience with building or maintaining Node.js based tooling is good (CLI tools, etc)
- Familiarity with past and current work could be helpful: https://github.com/nodejs/tooling

**Describe the session**

- Introduction to the Tooling Group, get new people interested in participating
- Catch up on what has been happening in the developer tools domain for the last year or so
- Regular session agenda items

**Session facilitator(s), Github handle(s) and timezone(s)**

Ruy Adorno (@ruyadorno) - EST

**Meeting notes and Virtual Meeting Link**

TBD

**Comment by darcyclarke** [comment]
Just wanted to note I'd like to attend this virtually if possible. My timezone is EST.

**Comment by joyeecheung** [comment]
For the remote participants: we've scheduled Zoom Webinars for the sessions, please register using the links provided in https://github.com/openjs-foundation/summit/issues/387 and you'll get a link in an email to join the sessions. More info in the issue mentioned.

**Comment by ruyadorno** [comment]
Tentative Agenda:

- Intro & recap
- Tooling wishlist:
  - Things like adding a StaticHttpServer: https://github.com/nodejs/node/pull/45096
  - Feel free to add more, brainstorm during the session
- Sub commands & `node run`:
  - https://github.com/nodejs/node/pull/52267
  - https://github.com/nodejs/node/pull/52190
- Conclusion & next steps for the group

**Comment by joyeecheung** [comment]
Closing as the session has ended.

Links to the recordings:

- Day 1 morning: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712132193000
- Day 1 afternoon: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712148446000
- Day 2 morning: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712218676000
- Day 2 afternoon: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712234786000

Links to the notes (very inaccurate, we should try harder at getting dedicated note takers the next time):

- Day 1: https://hackmd.io/erevKHb6RVihtWpdPgFWCw
- Day 2: https://hackmd.io/poOBiqFiTBeCIlfOv5HwUQ

Drafted trip report, would appreciate some reviews. Expect to publish on the official blog next week: https://hackmd.io/5vvP8o5bTmqcbNh-3oHpag
