### ISSUE TITLE
Session Proposal: Node.js Undici - planning for the next major

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/summit#391]
### Proposal

**Topic of the session**

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

**Date and Time of the session**

**Level**

- [ ] Beginner
- [ ] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

**Describe the session**

**Session facilitator(s), Github handle(s) and timezone(s)**

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by mcollina** [comment]
cc @ronag

**Comment by ronag** [comment]
Refs: https://github.com/nodejs/undici/issues/2722

Some topics:

- Developer Experience (split core and web etc...)
- Composition (dispatchers, dispath, undici.compose, handlers etc...)
- Dispatcher interface and hooks

**Comment by mcollina** [comment]
Added topic:

* How can we expose `ProxyAgent` to Node.js core? https://github.com/nodejs/undici/issues/1650 is very relevant.

**Comment by joyeecheung** [comment]
Closing as the session has ended.

Links to the recordings:

- Day 1 morning: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712132193000
- Day 1 afternoon: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712148446000
- Day 2 morning: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712218676000
- Day 2 afternoon: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712234786000

Links to the notes (very inaccurate, we should try harder at getting dedicated note takers the next time):

- Day 1: https://hackmd.io/erevKHb6RVihtWpdPgFWCw
- Day 2: https://hackmd.io/poOBiqFiTBeCIlfOv5HwUQ

Drafted trip report, would appreciate some reviews. Expect to publish on the official blog next week: https://hackmd.io/5vvP8o5bTmqcbNh-3oHpag
