### ISSUE TITLE
Session Proposal: Future of HTTP client

### ISSUE THREAD

**Issue by ronag** [openjs-foundation/summit#393]
### Proposal

**Topic of the session**

Should we mark existing HTTP client as legacy and what/how should we replace it?

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

**Date and Time of the session**

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

**Describe the session**

**Session facilitator(s), Github handle(s) and timezone(s)**

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by kettanaito** [comment]
Hi! The author of MSW here. Please count me in on this one. Thanks!

**Comment by joyeecheung** [comment]
For the remote participants: we've scheduled Zoom Webinars for the sessions, please register using the links provided in https://github.com/openjs-foundation/summit/issues/387 and you'll get a link in an email to join the sessions. More info in the issue mentioned.

**Comment by joyeecheung** [comment]
Closing as the session has ended.

Links to the recordings:

- Day 1 morning: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712132193000
- Day 1 afternoon: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712148446000
- Day 2 morning: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712218676000
- Day 2 afternoon: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712234786000

Links to the notes (very inaccurate, we should try harder at getting dedicated note takers the next time):

- Day 1: https://hackmd.io/erevKHb6RVihtWpdPgFWCw
- Day 2: https://hackmd.io/poOBiqFiTBeCIlfOv5HwUQ

Drafted trip report, would appreciate some reviews. Expect to publish on the official blog next week: https://hackmd.io/5vvP8o5bTmqcbNh-3oHpag
