### ISSUE TITLE
Session Proposal: Node.js involvement in standards

### ISSUE THREAD

**Issue by littledan** [openjs-foundation/summit#398]
### Proposal

**Topic of the session**

In Kilkenny, we discussed encouraging more feedback from Node.js in standards https://github.com/nodejs/admin/issues/841 . Let's get started!

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1 hour

**Date and Time of the session**

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

None

**Describe the session**

Dual goals:
- Inform collaborators about what's going on and how they can get involved as individuals
- Start collecting feedback that can eventually coalesce into Node-level standards positions

Let's go over various things happening in standards these days, including
- WinterCG
- New features in DOM, fetch, etc
- What's going on in TC39 (besides modules)
- IETF? Unicode?
- OpenJS effort on package.json

Maybe we could squeeze in a small amount of meta-conversation shoring up how we'll work together the nodejs/standards-positions repo, but I feel like we got to a pretty good point on the thread https://github.com/nodejs/admin/issues/841 .

**Session facilitator(s), Github handle(s) and timezone(s)**

@littledan 

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

```[tasklist]
### Tasks
```

**Comment by rxmarbles** [comment]
Could also add to the list of the standards collab space in Open JS

**Comment by joyeecheung** [comment]
Planning to pin this at 16:00-17:00 at the second day of the summit, which overlaps with the WinterCG monthly call

**Comment by joyeecheung** [comment]
For the remote participants: we've scheduled Zoom Webinars for the sessions, please register using the links provided in https://github.com/openjs-foundation/summit/issues/387 and you'll get a link in an email to join the sessions. More info in the issue mentioned.

**Comment by littledan** [comment]
Let’s use this session to develop this new repo: https://github.com/nodejs/standards-positions/blob/main/README.md
