### ISSUE TITLE
Session Proposal: Node.js PMWG & Version Management Working Session

### ISSUE THREAD

**Issue by wesleytodd** [openjs-foundation/summit#400]
### Proposal

**Topic of the session**

Working session for the Node.js Package Maintenance Working Group to advance discussions around version management tools within Node.js. This includes discussion of `corepack` scope, as well as alternatives, more official documentation for the relationship with npm and chartering the group for ownership of this domain.

**Type of the session**

- [X] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1 hour (open for discussion, might need longer?)

**Date and Time of the session**

**Level**

- [X] Beginner
- [X] Intermediate
- [X] Advanced

**Pre-requisite knowledge**

**Describe the session**

We will start with a re-cap of the history of discussions around shipping a version manager for node, corepack and npm, and the current discussions around the contentious topic. After that we will discuss goals for a proposed version manager for both Node.js and package managers. Lastly we will attempt to arrive at a decision if chartering the PMWG to own this domain is a good path forward.

**Session facilitator(s), Github handle(s) and timezone(s)**

@wesleytodd
@aduh95
@ruyadorno

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by ruyadorno** [comment]
we should pb ask for a 2 hour block, I don't think 1h will be enough to make meaningful progress.

**Comment by wesleytodd** [comment]
Updated to 2h.

**Comment by wesleytodd** [comment]
So for the agenda, I was thinking something like this (assuming we do 2 hours):

1. Do a small history recap (10 min)
2. Goal brainstorming session (30min)
3. Dive into technical requirements based on our goals (30min)
4. To charter or not? (20min)
5. Working time. Either continue other discussions or actually try to write some docs or code to move foward (30min)

Thoughts on this?

**Comment by darcyclarke** [comment]
Just wanted to note I'd like to attend this virtually if possible. My timezone is EST.

**Comment by joyeecheung** [comment]
We plan to make it the last session of the first day of the summit (May 3). We should probably start leaving around 17:00 London time (procrastinating a bit is okay but for security reasons we can't stay later than 18:00). So looking at 15:15-17:00 with some break time in between.

**Comment by wesleytodd** [comment]
Will we have all the setup in the room for streaming and remote participation or do we need to prepare to run that as the facilitators?

**Comment by joyeecheung** [comment]
Still need to figure it out. Current plan is to use Zoom (preferably the OpenJSF account), and we should have some microphones in the room, both people in the room and remote folks use Zoom to raise hands and we speak in turns.

**Comment by joyeecheung** [comment]
Streaming probably won't happen because of regulations (GDPR), but joining via Zoom is open.

**Comment by richardlau** [comment]
> We plan to make it the last session of the first day of the summit (May 3). We should probably start leaving around 17:00 London time (procrastinating a bit is okay but for security reasons we can't stay later than 18:00). So looking at 15:15-17:00 with some break time in between.

April 3 🙂

**Comment by GeoffreyBooth** [comment]
Maybe this can happen in the session, but I think it might help if beforehand each of the attendees can write down a list of use cases or problems they want solved? With more specificity than a vague notion like “Improve the experience of Yarn users.” I feel like part of the problem we’re facing is that we don’t have agreed-upon goals, so having a bunch of lists of what each person wants to achieve and seeing the common themes there might help us in finding that consensus.

In particular, I just don’t know what to do with requests like https://github.com/nodejs/node/pull/51981#issuecomment-2017973347 and https://github.com/nodejs/node/pull/51981#issuecomment-2017973347 that ask for a Corepack alternative without specifying either what’s wrong with Corepack or what they would prefer instead. A new Corepack . . . that’s better! 😄 I feel like the alignment of goals is by far the most important thing that needs to happen; implementation can happen async over time.

**Comment by wesleytodd** [comment]
> is that we don’t have agreed-upon goals

Agreed! I was hoping by having it start with brainstorming goals we would be better setup to have the deep discussions. If you think pre-work would help I am down, but I am not sure how reliable asking folks to do that will be.

> that ask for a Corepack alternative without specifying either what’s wrong with Corepack or what they would prefer instead.

Yeah, lol, I have been a bit guilty of this myself. I have referenced a replacement without any specification on what that could even mean. I was going to write up a formal document on the session (hopefully tomorrow morning) and think adding this stuff would be good.

**Comment by GeoffreyBooth** [comment]
I sketched out one possible alternative here: https://github.com/nodejs/package-maintenance/issues/591#issuecomment-2019048381

For the use cases of:
- I want an easy way to run different versions of Node.js for different projects that I develop.
- I want an easy way to run different package managers and/or versions of package managers for different projects that I develop.

With the intended goals of:
- Don’t reinvent the wheel: if there’s a solution out there that does what we need, let’s just reference or recommend it in our docs rather than building something new ourselves.
- Small core: if the solution works without needing to be bundled with Node, _don’t_ bundle it in our distribution.
- Encourage competition: whenever possible, allow the user to choose between various approaches rather than picking a winner, to provide space for new alternatives to emerge in the future from the ecosystem.

cc @mcollina @BridgeAR

**Comment by gulbanana** [comment]
> In particular, I just don’t know what to do with requests like [nodejs/node#51981 (comment)](https://github.com/nodejs/node/pull/51981#issuecomment-2017973347) and [nodejs/node#51981 (comment)](https://github.com/nodejs/node/pull/51981#issuecomment-2017973347) that ask for a Corepack alternative without specifying either what’s wrong with Corepack or what they would prefer instead. A new Corepack . . . that’s better! 😄 I feel like the alignment of goals is by far the most important thing that needs to happen; implementation can happen async over time.

I didn't read those comments as asking for a corepack alternative. It seems more likely that they're asking for corepack to not be removed *because* there is no alternative. This isn't a statement that there's something wrong with corepack.

**Comment by wesleytodd** [comment]
> This isn't a statement that there's something wrong with corepack.

Agreed those statements are not. The answers to "why not corepack" are in the threads in there. That said, I think the goal of this session is to get to the bottom of that question in a more approachable way for folks who were not able to read the pages and pages of comments across multiple issues and 4 years on this topic. Anyway, I don't think we should litigate the topic in the planning thread here, so please lets keep this to planning the sessions goals and structure.

**Comment by joyeecheung** [comment]
For the remote participants: we've scheduled Zoom Webinars for the sessions, please register using the links provided in https://github.com/openjs-foundation/summit/issues/387 and you'll get a link in an email to join the sessions. More info in the issue mentioned.

**Comment by joyeecheung** [comment]
You can also get invited to be a panelist beforehand to save the registration & promotion step. Ping in the OpenJS slack with your email or send a email to the email in my GitHub profile to get an invitation.

**Comment by trivikr** [comment]
## Time

**UTC Wed 03-Apr-2024 14:00 (03:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Wed 03-Apr-2024 08:00 (08:00 AM) |
| US / Mountain | Wed 03-Apr-2024 09:00 (09:00 AM) |
| US / Central  | Wed 03-Apr-2024 10:00 (10:00 AM) |
| US / Eastern  | Wed 03-Apr-2024 11:00 (11:00 AM) |
| EU / Western  | Wed 03-Apr-2024 16:00 (04:00 PM) |
| EU / Central  | Wed 03-Apr-2024 17:00 (05:00 PM) |
| EU / Eastern  | Wed 03-Apr-2024 18:00 (06:00 PM) |
| Moscow        | Wed 03-Apr-2024 18:00 (06:00 PM) |
| Chennai       | Wed 03-Apr-2024 20:30 (08:30 PM) |
| Hangzhou      | Wed 03-Apr-2024 23:00 (11:00 PM) |
| Tokyo         | Wed 04-Apr-2024 00:00 (12:00 AM) |
| Sydney        | Thu 04-Apr-2024 02:00 (02:00 AM) |

Or in your local time:
* https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+PMWG+%26+Version+Management+Working+Session&iso=20240403T1500
* or https://www.wolframalpha.com/input?i=03PM+UTC%2C+Apr+03%2C+2024+in+local+time

**Comment by joyeecheung** [comment]
BTW I just noticed that the comment above https://github.com/openjs-foundation/summit/issues/400#issuecomment-2032405363 gave incorrect times (we were using London time, not UTC, which had a 1 hour difference) and that was probably why some people missed the first hour of the session. Next time please check the timezone before generating the table.

**Comment by joyeecheung** [comment]
Closing as the session has ended.

Links to the recordings:

- Day 1 morning: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712132193000
- Day 1 afternoon: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712148446000
- Day 2 morning: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712218676000
- Day 2 afternoon: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712234786000

Links to the notes (very inaccurate, we should try harder at getting dedicated note takers the next time):

- Day 1: https://hackmd.io/erevKHb6RVihtWpdPgFWCw
- Day 2: https://hackmd.io/poOBiqFiTBeCIlfOv5HwUQ

Drafted trip report, would appreciate some reviews. Expect to publish on the official blog next week: https://hackmd.io/5vvP8o5bTmqcbNh-3oHpag
