### ISSUE TITLE
Session Proposal: Node.js Next-10 meeting

### ISSUE THREAD

**Issue by sheplu** [openjs-foundation/summit#401]
### Proposal

**Topic of the session**

Node.js Next-10 Collaboration Session

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1.5h-2h 

**Date and Time of the session**

TBD

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

* previous projects and initiatives part of the Next-10 would be great

**Describe the session**

* Quick presentation of the group
* feedback on the latest mini-summit (Advocacy feedback)
* Next steps to discuss

**Session facilitator(s), Github handle(s) and timezone(s)**

* @sheplu (in London)

**Meeting notes and Virtual Meeting Link**

TBD

**Comment by joyeecheung** [comment]
I don't think we can squeeze a 1.5h-2h slot for this. Would 1h be good?

**Comment by sheplu** [comment]
it will be a bit speedy and not optimal but 1h can work

**Comment by joyeecheung** [comment]
Planning t o put it around the lunch break on the second day. I am not sure if we even need that long a lunch break (currently, 1h45m), so may be able to split some time out of that after we figure out how long it needs to be.

**Comment by joyeecheung** [comment]
For the remote participants: we've scheduled Zoom Webinars for the sessions, please register using the links provided in https://github.com/openjs-foundation/summit/issues/387 and you'll get a link in an email to join the sessions. More info in the issue mentioned.

**Comment by joyeecheung** [comment]
Closing as the session has ended.

Links to the recordings:

- Day 1 morning: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712132193000
- Day 1 afternoon: https://zoom.us/rec/share/UmLZkxbAqBGgEUh8GptGvS_5qXXxKqEpT-rcTMX4ncTTS715-OTIJFv4nLZ40Tj5.Q4gNxJPbpTLH0W-X?startTime=1712148446000
- Day 2 morning: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712218676000
- Day 2 afternoon: https://zoom.us/rec/share/UcbGphrblwjuE2jL9dlsv-4hMv6uC0M_dS96N1xByyJcXfELAvrakmjHNguiS-Nc.5wjMJg55LA891PxO?startTime=1712234786000

Links to the notes (very inaccurate, we should try harder at getting dedicated note takers the next time):

- Day 1: https://hackmd.io/erevKHb6RVihtWpdPgFWCw
- Day 2: https://hackmd.io/poOBiqFiTBeCIlfOv5HwUQ

Drafted trip report, would appreciate some reviews. Expect to publish on the official blog next week: https://hackmd.io/5vvP8o5bTmqcbNh-3oHpag
