### ISSUE TITLE
Session Proposal: Documentation Improvements

### ISSUE THREAD

**Issue by Qard** [openjs-foundation/summit#403]
### Proposal

With the new website now launched, there's a new doc structure and some great new docs in there. A few sections are a bit light on content though so it might be worth a conversation about what new content we want to add to improve those sections.

**Topic of the session**

Space to discuss improving documentation on newly designed nodejs.org website.

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1h? Maybe less? Depends on how many people have ideas.

**Date and Time of the session**

**Level**

- [x] Beginner
- [x] Intermediate
- [x] Advanced

**Pre-requisite knowledge**

None.

**Describe the session**

Ideation on areas we can improve our docs.

**Session facilitator(s), Github handle(s) and timezone(s)**

Stephen Belanger (@qard)

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by joyeecheung** [comment]
hmm, it seems a bit too late to squeeze another session in, we have a packed agenda. Would it make sense to move it to the hallway track? (We have scheduled 1h45m for lunch. There should be plenty of room for more casual discussions)

**Comment by Qard** [comment]
Hallway track is fine if space is not available. Just wanted to prompt folks to be thinking about docs improvements now that we've got the better website structure for it and to hopefully come up with some ideas on what we could add or expand. I don't think that would be a long discussion. 😅

**Comment by joyeecheung** [comment]
Should this remain open? Sounds like a good session for the next summit.

**Comment by Qard** [comment]
Sounds reasonable to me. 👍🏻

**Comment by Ceres6** [comment]
Hey I wanted to bring this up again now that the new Dublin Summit is scheduled. I'm trying to put up streams [documentation/guide](https://github.com/nodejs/node/issues/8646) and I think this could be a good opportunity to discuss it among other posible doc improvements

**Comment by JakobJingleheimer** [comment]
@Qard would you be interested in hosting this talk for the Dublin summit?

**Comment by bmuenzenmeyer** [comment]
If there isn't another slot for this yet (cc @ovflowd) it'd be a good place to talk about our https://github.com/nodejs/api-docs-tooling efforts via https://github.com/nodejs/node/issues/52343

**Comment by ovflowd** [comment]
I'm also fine co-hosting this one, if that's up :)

**Comment by Qard** [comment]
I'm up for that. Anything docs improvement related is relevant, I think.

I'll be at the collab summit, though I'm leaving Datadog so I'm not sure yet how much time I'll have to prepare for things.
