### ISSUE TITLE
Node.js Collaborator Summit 2024 / Dublin

### ISSUE THREAD

**Issue by ovflowd** [openjs-foundation/summit#419]
# Node.js Collaboration Summit 2024 / Dublin

** REGISTRATIONS ARE OPEN !!!! ** https://forms.gle/sRE1MCi7Nm5Qs5B76

**Date:** November 7-8, 2024 _(We recommend staying from the 7th to the 9th in a Hotel)_
**Venue:** [Baseline Community, 3rd Floor, 61 Thomas St., Dublin D08 W250, Ireland](https://maps.app.goo.gl/GiXJAxoQP3AUomZs9)
**Cost:** 0.
**Agenda:** https://docs.google.com/spreadsheets/d/1URn0hy4Mj-vSmZmZL8Z6_LPz5U5-WAAV-ueqVM4EVeY/edit?usp=sharing
  - The AGENDA is going to be drafted in the upcoming weeks based on the current session submissions!

---

### Registration

Since we are borrowing space in an office building, for security reasons, in-person attendance is reserved for collaborators or people who can find a collaborator to vouch for them.

### Attending in person

[The Linux Foundation Events Code of Conduct](https://events.linuxfoundation.org/about/code-of-conduct/) applies to all event spaces.

1. We plan to have a camera capture the room for the Zoom call. According to local regulations, we need to collect consent from those who appear on camera and are recorded. This applies especially to session facilitators.
1. We won't be able to provide an all-masked environment, so wearing a mask is not mandatory, but it is OK to wear one during the event.
1. The summit starts at 9:00 with breakfast. Sessions begin at 9:30 and end at 17:00 each day. After the summit, we should leave the building by 18:00.

#### Suggested Hotels

- [The Spencer Hotel](https://maps.app.goo.gl/GzPTi1Hu9q5P9WE96)
- [The Samuel Hotel](https://maps.app.goo.gl/jugRdELivFCxfgwu8)
- [Hyatt Centric](https://maps.app.goo.gl/TZ7dWRZw46jg4vRM6)
- [StayCity Tivoli](https://maps.app.goo.gl/E9QcksyyyHj5yRrw7)

### Submit a session proposal!

[Open an issue](https://github.com/openjs-foundation/summit/issues/new?assignees=ovflowd%2C+mcollina&labels=London+2024%2C+Collaborator+Summit%2C+Session+Proposal&projects=&template=summit-topic-proposal.md&title=Session+Proposal%3A+%3CProject+Name%3E+%3CSession+Title%3E) to submit a session proposal.

Please remember that the Collab Summit format is for collaboration, so we highly suggest submitting sessions that include collaboration (Panels, Fire-side chats, Discussions).

One goal of the Node.js Collaborator Summit is to enable collaborators to discuss and collaborate on long-term and critical strategic initiatives and topics of the Node.js project.

### If you have questions

- **OpenJS Foundation Slack:** https://slack-invite.openjsf.org/
- **#collabsummit channel:** https://openjs-foundation.slack.com/archives/CPE10404W
#### Is there any registration fee?

No! This year's attendance will not require any pre-payment.

#### Will there be remote attendance?

Yes. We will be allowing remote attendance through Zoom, but we won't be livestreaming.

#### I want to submit a session

This edition will only accept submissions from existing collaborators or contributors in the Node.js space. The topics must also be related to Node.js, and the submission format must intentionally be a panel, fire-side chat, or any discussion format.

This time, we will accept sessions from virtual facilitators. For hybrid attendance to work, everybody must raise their hands first and wait their turn to speak.

#### Is the Summit part of NodeConf EU or somewhat related?

No. The Node.js Collaborator Summit has no link or connection whatsoever with NodeConf. Although it is being organized to happen after the NodeConf EU event, given the nature of the conference, which focuses on Node.js, a larger Node.js contributor audience would be attending it, creating a more substantial opportunity to organize a Collaborator Summit.

**Comment by ovflowd** [comment]
FYI! Please feel free to submit proposals already!

**Comment by rluvaton** [comment]
Hey, can you add to the poll `How certain are you about attending the summit?` I'll be joining remotely as none of the answers match

**Comment by ovflowd** [comment]
> Hey, can you add to the poll `How certain are you about attending the summit?` I'll be joining remotely as none of the answers match

At this point no changes to the poll will happen. Sorry. The poll is only for in-person attendance.

We are not sure yet remote attendance will happen during this edition yet as we need to check equipment.

**Comment by rluvaton** [comment]
I really hope there will be, I will not be able to make it for the in-person as this is around my wife due date

**Comment by joyeecheung** [comment]
@rluvaton We can probably schedule a deep-dive call about the noderc proposal. It seems a bit funny to wait for the collaborator summit ;)

**Comment by rluvaton** [comment]
> @rluvaton We can probably schedule a deep-dive call about the noderc proposal. It seems a bit funny to wait for the collaborator summit ;)

Do you wanna do it part out the loader team meeting?

**Comment by joyeecheung** [comment]
Sure - it's already on the loaders agenda

**Comment by ovflowd** [comment]
**Here are the transcripts and recordings of all the Zoom sessions:**

- Please note that due to organizational issues, the recordings on Both the 7th of November and the 8th of November started after the initial sessions started, + the transcripts also started way later. Apologies for that!
- **7th of November:**
  - [Recordings](https://hubspot.zoom.us/rec/share/MNfSM4XshOWbzMBh4cQDGALIygQejbIMk8NK0HwkimP4D37dd8i2QYWD9a4cN0U7.h34h8CPVK2zUBadX) -- Password: `&lKn5M&^`
- **8th of November:**
  - [Recordings](https://hubspot.zoom.us/rec/share/BI7Z5-IsYm1Zb9kKzOaFGS0QygpP01QtUhrdgyHzkjNOfzu7vik3_Q5qoa-Qc4kq.-yIZNAdKgNmztNos) -- Password: `QJab8e.@`

<details>
<summary>AI Summary for 7th of November</summary>

```
Quick recap
The meeting covered various aspects of improving the Node.js project, including addressing CI system issues, enhancing testing processes, and refining contributor experiences. Discussions also focused on a proposed design approval process and potential voting mechanisms for community input on design decisions. Additionally, the results of a recent survey were presented, highlighting increased participation, diverse respondent demographics, and key areas for project improvement.

Next steps
Node.js team to add documentation about CI health tools and commands to the collaborator guide.

Node.js team to improve visibility and communication about the project roadmap and duration.

Node.js team to explore implementing a design proposal process for complex initiatives.

Node.js team to investigate ways to increase community participation in decision-making processes.

Node.js team to review and potentially update the survey questions for clarity and accuracy.

Node.js team to focus on improving documentation as a priority based on survey feedback.

Summary
Addressing CI System Issues and Formatting

Claudio discussed the process of identifying and addressing issues in the CI system. He explained how to use the terminal to view the results of the last 400 runs, and how to use the 'ncu' command to check for failing Jenkins. He also mentioned the importance of locking down outreach and the use of the 'dash, markdown' option for better formatting. Claudio suggested that anyone interested in helping with CI health could start by checking out a specific repository, which shows the top offenders and their issues. He also mentioned the need to check out what's wrong with a particular test and the importance of reproducing issues on Mac OS.


Improving Node.js Project Testing Experience

Claudio discusses several topics related to improving the Node.js project's testing and contributor experience. He suggests adding a command to pull requests that shows failing tests and their history, as well as linking to documentation on debugging flaky tests. There is some discussion around using third-party tools for detecting and avoiding flaky tests. Claudio also mentions the need for better onboarding of new contributors and making it easier to identify good first issues to work on. The group seems to agree that having documentation and tooling is not enough - there needs to be dedicated effort from people actively triaging issues and fixing flaky tests.


Design Approval Process Discussion

Claudio proposed a new process for design approval to avoid last-minute changes and discussions. He suggested that design proposals could be reviewed and approved before implementation, allowing for faster iteration and refinement. Richard mentioned a past attempt at a similar process, but it was not continued. Claudio also suggested that design approval could be optional, but beneficial for complex initiatives. The team discussed the potential for a voting mechanism to gather community input on design decisions. However, there was concern about making decisions binding, as it could lead to unnecessary resistance. The team agreed to continue the discussion in the next session.


Survey Results and Technology Usage Trends

Claudio discussed the results of a survey conducted last year, noting an 80% increase in participants and a significant presence of European countries. He highlighted the diverse nature of the respondents, including startups, tech companies, universities, and individuals. The majority of respondents were application developers. Claudio also presented data on operating systems, noting a significant increase in Mac usage and a smaller but still notable presence of Windows users. He emphasized the importance of modernization and transparency in project duration, with many respondents expressing a desire for better documentation and visibility. Claudio also mentioned the popularity of certain technologies, such as type screens, and the challenges of understanding their usage in production environments.
```

</details>

**Comment by ovflowd** [comment]
![Image](https://github.com/user-attachments/assets/2d8cddbf-fe9b-4e62-b2f5-b89b1c11f889)
![Image](https://github.com/user-attachments/assets/70b4d051-7364-44f7-be08-7c01af512412)

**Comment by tlhunter** [comment]
Here are some more photos from the event:

https://thomashunter.name/photos/2024-nodeconf-eu-and-nodejs-collaboration-summit
