### ISSUE TITLE
Session Proposal: module loading customization/optimization and CJS/ESM interoperability

### ISSUE THREAD

**Issue by joyeecheung** [openjs-foundation/summit#422]
### Proposal

**Topic of the session**

Discuss recent module loading customization and interoperability efforts

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1h

**Date and Time of the session**

TBD

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

Familarity with module loading in Node.js

**Describe the session**

Recap and review recent module loading work, brainstorm ideas

- Documenting dual package shipping patterns and updating ecosystem practices: https://github.com/nodejs/package-examples/issues/2
  - What are some projects that might already be hitting require(esm) that we should check for regressions from unflagging
  - What patterns are people using to ship modules
  - What else is blocking them from migration to ESM
  - What are the practices that are used to migrate
  - What else can be done to help
  - What kind of content should we put out there, where...
- Missing pieces of ESM
  - Performance
  - Snapshot & SEA support
  - ?
- Synchronous, in-thread & universal module loader cutomization hooks: https://github.com/nodejs/loaders/pull/198
  - What are the things not supported in module.register() that we can use the new API to fix
  - Is sync resolve + sync load + startGraph enough
  - deasync for certain workloads
- File-based preload configurations (noderc): https://github.com/nodejs/node/issues/53787
  - What are people using doing for preloaded configurations, what fields should be in there
  - What format is deseirable
  - Pain points of runtime configurations
  - Conflicts with other runtime configurations?

**Session facilitator(s), Github handle(s) and timezone(s)**

- @joyeecheung 
- @mcollina
- @ShogunPanda 
- @GeoffreyBooth 

**Meeting notes and Virtual Meeting Link**

TBD

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

TBD

----

**Comment by joyeecheung** [comment]
Updated the agenda a bit to include https://github.com/nodejs/package-examples/issues/2

**Comment by joyeecheung** [comment]
Session has been scheduled to 10:45 Dublin time on Nov 8. Not sure remote participation would be possible yet (I believe it is?)

**Comment by joyeecheung** [comment]
Remote participation worked today so should also work tomorrow. Zoom link is in https://docs.google.com/spreadsheets/d/1URn0hy4Mj-vSmZmZL8Z6_LPz5U5-WAAV-ueqVM4EVeY/edit?usp=sharing

**Comment by charlieforward9** [comment]
To whom it may interest, I made a request [here](https://github.com/nodejs/package-examples/issues/2#issuecomment-2465890983) pertaining to my own task of reaching CJS/ESM interoperability and am seeking a brief review from someone more experienced in this scope.

**Comment by dygabo** [comment]
Sorry that I could not attend as I was on a plane back home when this session happened. Thanks for publishing the notes. Was there also a recording of the zoom call that could be made available?

**Comment by joyeecheung** [comment]
> Sorry that I could not attend as I was on a plane back home when this session happened. Thanks for publishing the notes. Was there also a recording of the zoom call that could be made available?

There was a recording being recorded on either @ovflowd 's Zoom cloud or his laptop locally. Not sure if he's got them or when it would be uploaded somewhere.

**Comment by ovflowd** [comment]
Let me add the recordings to the main issue 🙏

**Comment by joyeecheung** [comment]
Recording has been posted to https://github.com/openjs-foundation/summit/issues/419#issuecomment-2470241971 . Closing.
