### ISSUE TITLE
Session Proposal: Node.js Next-10 Survey Results

### ISSUE THREAD

**Issue by sheplu** [openjs-foundation/summit#423]
### Proposal

Node.js Next-10 Collaboration Session
Feedback from this year open survey

**Topic of the session**

**Type of the session**

- [ ] Collaborate
- [ ] Workshop
- [x] Talk

**Estimated duration of the session**

0.5 hour

**Date and Time of the session**

It would be great to have the first 0.5h of the collaborator summit

**Level**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

N/A

**Describe the session**

Presentation of result from the last Next-10 survey

**Session facilitator(s), Github handle(s) and timezone(s)**

@sheplu 

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by mhdawson** [comment]
@sheplu I think we agreed you were going to lead this one right? If so we should probably update the Session facilitator(s),

**Comment by ovflowd** [comment]
Can the results of the survey be shared?
