### ISSUE TITLE
Session Proposal: Node.js Next-10 Healthy Collaborator Base

### ISSUE THREAD

**Issue by sheplu** [openjs-foundation/summit#424]
### Proposal

Node.js Healthy collaborator base & sustainability

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1.5h - 2h

**Date and Time of the session**

N/A

**Level**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

**Describe the session**

Discussion and review of result from a survey dedicated to collaborators
Collaborate on feedback on what need to be improved
What are the core issues? What is missing?
How can we have more new contributors

**Session facilitator(s), Github handle(s) and timezone(s)**

@marco-ippolito @mhdawson 

**Meeting notes and Virtual Meeting Link**

**Follow-up / Set-up sessions (if any)**

**Additional context (optional)**

----

**Comment by mhdawson** [comment]
@ruyadorno do we have too many sessions? I think this and #423 are really different topics but if there are too many sessions we can consider how to compress the submissions
