### ISSUE TITLE
Session Proposal: Node.js Tooling Group meeting

### ISSUE THREAD

**Issue by ruyadorno** [openjs-foundation/summit#430]
### Proposal

**Topic of the session**

Node.js Tooling Group Collaboration Session

**Type of the session**

- [x] Collaborate
- [ ] Workshop
- [ ] Talk

**Estimated duration of the session**

1 hour

**Date and Time of the session**

TBD

**Level**

- [] Beginner
- [X] Intermediate
- [ ] Advanced

**Pre-requisite knowledge**

- Experience with Node.js core
- Experience with building or maintaining Node.js based tooling is good (CLI tools, etc)
- Familiarity with past and current work could be helpful: https://github.com/nodejs/tooling

**Describe the session**

- Introduction to the Tooling Group, get new people interested in participating
- Catch up on what has been happening in the developer tools domain for the last year or so
- Bluesky social media presence
- How to handle Experimental status when adoption is significant ([nodejs/TSC#1397](https://github.com/nodejs/TSC/issues/1397))

**Session facilitator(s), Github handle(s) and timezone(s)**

- Ruy Adorno (@ruyadorno) - EST
- Stephen Belanger (@Qard)
- Wes Todd (@wesleytodd)

**Meeting notes and Virtual Meeting Link**

TBD

**Comment by ovflowd** [comment]
Added to the agenda.
